### ISSUE TITLE
[BUG] copy_bom misleading error message

### ISSUE THREAD

**Issue by mythi** [occlum/occlum#1009]
# Describe the bug
when running `copy_bom` without `rsync` installed, the error does not give the real reason:
```
[2022-09-19T13:30:07Z ERROR copy_bom::util] copy dir /foo to image /bar failed. No such file or directory (os error 2)
```

# Expected behavior
Error message that says `rsync` cannot be run.

**Comment by qzheng527** [comment]
@mythi Thanks for the info. We will fix this misleading error message.

**Comment by mythi** [comment]
I think this was fixed
