### ISSUE TITLE
[BUG] Run demo remote_attestation/init_ra_flow/occlum_server error

### ISSUE THREAD

**Issue by solio** [occlum/occlum#1013]
`
[get_platform_quote_cert_data ../qe_logic.cpp:377] Error returned from the p_sgx_get_quote_config API. 0xe046
thread '<unnamed>' panicked at 'IOCTRL IOCTL_GET_DCAP_QUOTE_SIZE failed', src/occlum_dcap.rs:70:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
`

docker image occlum/occlum:0.28.0-ubuntu20.04

docker run -it --privileged -v /dev/sgx_enclave:/dev/sgx/enclave -v /dev/sgx_provision:/dev/sgx/provision occlum/occlum:0.28.0-ubuntu20.04

I didn't know how to detect this error, please help, thanks!

**Comment by qzheng527** [comment]
@solio Did you set correct PCCS_URL in your running container? It is in the file /etc/sgx_default_qcnl.conf.
Also, please make sure there is avaiable PCCS service you can access in you env.
You can refer to https://github.com/occlum/occlum/tree/master/example#start-the-tensorflow-serving.
It is the aliyun PCCS service which we verified but you have to work on aliyun ECS.
Otherwise, you have to set up your personal PCCS service, which you can refer to https://github.com/occlum/occlum/tree/master/example#start-the-tensorflow-serving

**Comment by solio** [comment]
> 

Sorry, I didn't read the document in a correct order LoL. I try that later.
Thank you.

**Comment by solio** [comment]
@qzheng527 
When added PCCS it report a new error.
`thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "IOCTRL IOCTL_GEN_DCAP_QUOTE failed"', src/lib.rs:39:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5`

**Comment by qzheng527** [comment]
@solio Can you just run the simple [`dcap demo`](https://github.com/occlum/occlum/tree/master/demos/remote_attestation/dcap) first to make sure your environment is ok?

**Comment by solio** [comment]
> @solio Can you just run the simple [`dcap demo`](https://github.com/occlum/occlum/tree/master/demos/remote_attestation/dcap) first to make sure your environment is ok?

@qzheng527 Yeah, it's ok in dcap demo.

**Comment by qzheng527** [comment]
@solio In which step did you meet the problem?
https://github.com/occlum/occlum/tree/master/demos/remote_attestation/init_ra_flow#how-to-run

**Comment by solio** [comment]
> docker run -it --privileged -v /dev/sgx_enclave:/dev/sgx/enclave -v /dev/sgx_provision:/dev/sgx/provision occlum/occlum:0.28.0-ubuntu20.04

@qzheng527 When I manually run `occlum run /bin/server localhost:50051` in container (docker run -it --privileged -v /dev/sgx_enclave:/dev/sgx/enclave -v /dev/sgx_provision:/dev/sgx/provision occlum/occlum:0.28.0-ubuntu20.04)

but, it's ok when I run container `sevenzheng/init_ra_server` directly.

**Comment by solio** [comment]
I've build the demo remote_attestation/init_ra_flow success

**Comment by qzheng527** [comment]
@solio It is werid. All the recent HW CI init_ra case passed. Can you just use the latest Occlum 0.29.0 docker image to try again?

**Comment by solio** [comment]
> 0.29.0

@qzheng527 0.29.0 is ok, that's sooooooooooooo great, thank you!

**Comment by TY-cc** [comment]
Hi, I have problem about demo of dcap. How to set the pccs in docker?
I have succeed about intel's demo. I want to test the occlum's dacp demo

**Comment by qzheng527** [comment]
@TY-cc More precisely it is not to set the PCCS in docker, it is to set the PCCS URL in docker which it is in the file `/etc/sgx_default_qcnl.conf`.  To set up PCCS service by yourself please refer to https://www.intel.com/content/www/us/en/developer/articles/guide/intel-software-guard-extensions-data-center-attestation-primitives-quick-install-guide.html.

**Comment by Mrkuib** [comment]
> 

Please ask how you installed pccs in docker, I installed it according to your method or failed, and the occlum command could not be parsed after installation
