### ISSUE TITLE
DCAP: Error returned from the p_sgx_get_quote_config API. 0xe019[BUG]

### ISSUE THREAD

**Issue by TY-cc** [occlum/occlum#1029]
# Describe the bug
It return error when I want to test the dcap remote_attestation.

# To reproduce
1. I use the docker create a contain with "docker run -it --device /dev/sgx/enclave --device /dev/sgx/provision occlum/occlum:latest-ubuntu20.04"
2. Then i run the command "./run_dcap_quote_on_occlum.sh" in /demos/remote_attestation/dcap/

I get return as follw:
> [get_platform_quote_cert_data ../qe_logic.cpp:378] Error returned from the p_sgx_get_quote_config API. 0xe019
thread 'main' panicked at 'IOCTRL IOCTL_GET_DCAP_QUOTE_SIZE failed', src/occlum_dcap.rs:70:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

This is why?

**Comment by TY-cc** [comment]
It does't have "sgx_enclave" and "sgx_provision" in /dev of docker container.
you should use the follow instruction：

> docker run -it --privileged -v /dev/sgx_enclave:/dev/sgx/enclave -v /dev/sgx_provision:/dev/sgx/provision occlum/occlum:[version]-ubuntu20.04

**Comment by Mrkuib** [comment]
hello，I used this command to start the container, but still reported the same error, and later looked at the information may be a PCCS configuration problem, I want to ask you how to configure PCCS
