### ISSUE TITLE
Python flask Demo [BUG]

### ISSUE THREAD

**Issue by Klein920116** [occlum/occlum#1049]
I want to run Python with Occlum, and I pull the docker of Occlum.

When I run with occlum run  /bin/app.py, there is a error message "failed to boot up LibOS: EACCES (#13, Permission denied): file is not executable [line = 94, file = src/process/do_spawn/exec_loader.rs]
[ERROR] occlum-pal: occlum_ecall_new_process returns EACCES (line 209, file src/pal_api.c) ".

And I want to know what's wrong with it.

**Comment by Klein920116** [comment]
There is a sample flask project and it is used to test api whethere can be accessed in Occlum.

**Comment by ClawSeven** [comment]
Because the latest python package from conda is non-PIE and it is unsafe in TEE, occlum would crash directly.
Please use python version before 3.8.13, such as python 3.8.10.

**Comment by Klein920116** [comment]
> Because the latest python package from conda is non-PIE and it is unsafe in TEE, occlum would crash directly. Please use python version before 3.8.13, such as python 3.8.10.

But I download the version of python is 3.7.10, is it correct?

**Comment by Klein920116** [comment]
> > Because the latest python package from conda is non-PIE and it is unsafe in TEE, occlum would crash directly. Please use python version before 3.8.13, such as python 3.8.10.
> 
> But I download the version of python is 3.7.10, is it correct?

The errors are still occured even though I have updated python version.

**Comment by ClawSeven** [comment]
@Klein920116 Python 3.7.10 is OK. Could you use `file ./python` and show me the results?

**Comment by qzheng527** [comment]
@Klein920116 Please use the latest flask demo in github, which is successful in our CI.

**Comment by Klein920116** [comment]
> @Klein920116 Please use the latest flask demo in github, which is successful in our CI.

Actually, I just write a sample flask code in my python project.

**Comment by Klein920116** [comment]
> @Klein920116 Python 3.7.10 is OK. Could you use `file ./python3.7` and show me the results?

The same error.

**Comment by Klein920116** [comment]
When I try to occlum run your demo code. The error shows below:

failed to boot up LibOS: ENOEXEC (#8, Exec format error): scrip interpreter is not ELF format [line = 36, file = src/process/do_spawn/exec_loader.rs]
[ERROR] occlum-pal: occlum_ecall_new_process returns ENOEXEC (line 209, file src/pal_api.c)

**Comment by Klein920116** [comment]
> > @Klein920116 Python 3.7.10 is OK. Could you use `file ./python3.7` and show me the results?
> 
> The same error.

@ClawSeven

**Comment by Klein920116** [comment]
> When I try to occlum run your demo code. The error shows below:
> 
> failed to boot up LibOS: ENOEXEC (#8, Exec format error): scrip interpreter is not ELF format [line = 36, file = src/process/do_spawn/exec_loader.rs] [ERROR] occlum-pal: occlum_ecall_new_process returns ENOEXEC (line 209, file src/pal_api.c)

@qzheng527
