### ISSUE TITLE
Running Python app with third-party Python libs

### ISSUE THREAD

**Issue by qiyuangong** [occlum/occlum#105]
Hi, I have tried this [Python example](https://github.com/occlum/occlum/tree/master/demos/python). I works well in my SGX env. 

Then, I want to extend it to a more complicate Python app with a few third-party libs, such as numpy, pandas or matplotlib etc. I'm wondering:

1. Do I need to find a alpine version for these libs, and import them with apk? 
2. If there isn't alpine version libs availabe, what should I do?

**Comment by tatetian** [comment]
Did you try the old version of the demo (a simple Python hello world) or the new version (a CSV processing Python program that uses NumPy, pandas, and sckit-learn)? I think the new version has made it clear how to reuse third-party Python libraries in Occlum: just `pip3 install` those libraries in Alpine and then copy those libraries to Occlum's image directory before `occlum build`. Check out the two scripts in the demo.

As for your second question, I suppose `pip3 install` is independent from Linux distributions. That is, `pip3` allows you to install the same set of Python libraries on any Linux distribution. I could be wrong. If you found any trouble installing your interested Python libraries, you are always welcome to post issues on Github.

**Comment by qiyuangong** [comment]
Got it. Thanks :)

Issue closed.
