### ISSUE TITLE
Why mpx_bndxx define in mpx_utils , but not been call in anywhere[BUG]

### ISSUE THREAD

**Issue by Marshalzxy** [occlum/occlum#1054]
# Describe the bug
Why mpx_bndxx define in mod mpx_utils , but not been call in anywhere.
mpx_utils define 4 pub functions:
mpx_bndmk
mpx_bndcu
mpx_bndcu
mpx_enable
Only mpx_enable is called, why the rest three pub funcs are not called anywhere in this project. Are these funcs useless for now ?
I read occlume paper which pulished in 2020 'Occlum: Secure and Efficient Multitasking Inside a
Single Enclave of Intel SGX'(https://arxiv.org/pdf/2001.07450.pdf). According to that paper description, mpx_bndcu and 
mpx_bndcu were need in confinding memory access and confiding control transfer which were  discribed in section 4 of that paper. Why occlume project not calls these functions now? And how call occlume releasize MMDSFI frame without those bondary checks/protections?

# To reproduce
Read src\libos\src\util\mpx_util.rs 

# Expected behavior
mpx_bndmk
mpx_bndcu
mpx_bndcu
be called or depricated

# Logs
If applicable, add logs to help explain your problem.

# Environment

- HW: [e.g. SGX1, SGX2] 
- OS: [e.g. Ubuntu20.04, CentOS8.2]
- Occlum version:.0.28.0

# Additional context

# Possible solution/Implementation
Not obligatory, but suggest a fix/reason for the bug.

@tatetian @jessehui

**Comment by jessehui** [comment]
MPX has been given up by Intel and is no longer supported in Occlum.

**Comment by Marshalzxy** [comment]
Thanks!
