### ISSUE TITLE
Python flask demo bug

### ISSUE THREAD

**Issue by Klein920116** [occlum/occlum#1055]
failed to boot up LibOS: EACCES (#13, Permission denied): file is not executable [line = 94, file = src/process/do_spawn/exec_loader.rs]
[ERROR] occlum-pal: occlum_ecall_new_process returns EACCES (line 210, file src/pal_api.c)

Does anyone solve this problem? no words to say but fxxk

**Comment by Klein920116** [comment]
The error encounter several weeks, nobody solve it?

**Comment by Klein920116** [comment]
> The error message`file is not executable`has told you the reason, please make sure the file is executable before executing it.

It's ridiculous. I just copy your demo code to my python file and rename it.

**Comment by tychobrailleur** [comment]
> > The error message`file is not executable`has told you the reason, please make sure the file is executable before executing it.
> 
> It's ridiculous. I just copy your demo code to my python file and rename it.

FWIW, I pulled the latest docker image, ran the flask demo with no problem.  I also tried to rename the python file and re-built the enclave – and again no problem.  Did you change the `flask.yaml` with the new filename, and re-built the enclave before running?

**Comment by Klein920116** [comment]
> > > The error message`file is not executable`has told you the reason, please make sure the file is executable before executing it.
> > 
> > 
> > It's ridiculous. I just copy your demo code to my python file and rename it.
> 
> FWIW, I pulled the latest docker image, ran the flask demo with no problem. I also tried to rename the python file and re-built the enclave – and again no problem. Did you change the `flask.yaml` with the new filename, and re-built the enclave before running?

Thanks for your answer. The issue has been solved. The problem is I need to chmod 777 files(relavant python files), otherwise would get same error forever for me.
