### ISSUE TITLE
occlum run[BUG]

### ISSUE THREAD

**Issue by Klein920116** [occlum/occlum#1059]
When I run the command "occlum run /bin/app.py" to start a flask project, the error shows below.

And when I run the command **second time**, the project could be run normally.

thread '<unnamed>' panicked at 'data dirty when dropping', /root/occlum/deps/sefs/rcore-fs/src/dirty.rs:60:9
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
             at library/core/src/panicking.rs:142
   2: rcore_fs_sefs::SEFS::_new_inode
   3: rcore_fs_sefs::SEFS::new_inode
   4: <rcore_fs_sefs::INodeImpl as rcore_fs::vfs::INode>::create
   5: <rcore_fs_unionfs::UnionINode as rcore_fs::vfs::INode>::create
   6: <rcore_fs_mountfs::MNode as rcore_fs::vfs::INode>::create
   7: occlum_libos_core_rs::fs::fs_view::FsView::open_file
   8: occlum_libos_core_rs::fs::file_ops::open::do_openat
   9: occlum_libos_core_rs::fs::syscalls::do_openat
  10: occlum_libos_core_rs::syscall::do_syscall
  11: occlum_syscall
  12: <unknown>
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
/opt/occlum/build/bin/occlum: line 340:  2344 Illegal instruction     (core dumped) RUST_BACKTRACE=1 "$instance_dir/build/bin/occlum-run" "$@"

**Comment by liqinggd** [comment]
Hi, this problem may be caused by the memory resource issue, I think you can try to increase `kernel_space_heap_size` of Occlum.json.
