### ISSUE TITLE
[BUG]Any plan to implement the syscall table?

### ISSUE THREAD

**Issue by thempp66** [occlum/occlum#1068]
# Describe the bug

I found this error when using syscall "madvise":
Function not implemented (os error 38)

So, is there any plan to continue to implement the syscall (such as madvise)?
https://github.com/occlum/occlum/blob/3fa049df470b4ff90c84a6a53860d16548be8dae/src/libos/src/syscall/mod.rs

Thanks!

**Comment by guzongmin** [comment]
@thempp66 Can you please share your application, which depends on the madvise syscall? Most of the time, the missing madvise syscall did not block the applications. So it is not on the priority list.

**Comment by thempp66** [comment]
> @thempp66 Can you please share your application, which depends on the madvise syscall? Most of the time, the missing madvise syscall did not block the applications. So it is not on the priority list.

Application:
[node-template](https://github.com/paritytech/substrate/tree/master/bin/node-template)
It's simple and quick to reproduce the error. Just need to `occlum-cargo build --release` and run in an occlum instance.

**Comment by volcano0dr** [comment]
@thempp66 I understand that `mdvise` will affect wasmtime's strategy for creating instances, but it will not block wasmtime.

**Comment by guzongmin** [comment]
> @thempp66 I understand that `mdvise` will affect wasmtime's strategy for creating instances, but it will not block wasmtime.

I agree. In most of the time, Occlum does not need to add this syscall.

**Comment by qzheng527** [comment]
@guzongmin @volcano0dr Recently when debugging pytorch + pbert (Pre-Training BERT with Permuted Language Model), it just error return if no `madvice` syscall supported. Making `madvice` just return success can work-around it. Perhaps for such kind of syscall (just advice or hint to improve system performace), Occlum can just return success with some warning message for most compatibility.

**Comment by thempp66** [comment]
> @thempp66 Can you provide Occlum run logs?

```
root@8cabbf9f6983:/repo/occlum_instance# occlum run /bin/node-template

2022-12-12 02:43:08 Substrate Node    
2022-12-12 02:43:08 ✌️  version 4.0.0-dev-59ca8df2cbc    
2022-12-12 02:43:08 ❤️  by Substrate DevHub <https://github.com/substrate-developer-hub>, 2017-2022    
2022-12-12 02:43:08 📋 Chain specification: Local Testnet    
2022-12-12 02:43:08 🏷  Node name: free-gun-4379    
2022-12-12 02:43:08 👤 Role: FULL    
2022-12-12 02:43:08 💾 Database: RocksDb at /root/.local/share/node-template/chains/local_testnet/db/full    
2022-12-12 02:43:08 ⛓  Native runtime: node-template-100 (node-template-1.tx1.au1)    
2022-12-12 02:43:08 Failed to check whether `madvise(MADV_DONTNEED)` works: madvise failed: Function not implemented (os error 38)    
2022-12-12 02:43:08 You're running on a system with a broken `madvise(MADV_DONTNEED)` implementation. This will result in lower performance.    
2022-12-12 02:43:08 🔨 Initializing Genesis block/state (state: 0xf0f7…dfa4, header-hash: 0xd125…2f91)    
2022-12-12 02:43:08 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.    
=========

Version: 4.0.0-dev-59ca8df2cbc

   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: libc_start_main_stage2


Thread 'main' panicked at 'failed to decommit linear memory pages: madvise failed to decommit: {}

Caused by:
    Function not implemented (os error 38)', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmtime-runtime-1.0.0/src/instance/allocator/pooling.rs:467

This is a bug. Please report it at:

        support.anonymous.an

2022-12-12 02:43:09 Evicting failed runtime instance error=Runtime panicked: failed to decommit linear memory pages: madvise failed to decommit: {}

Caused by:
    Function not implemented (os error 38)
Error: Service(Client(RuntimeApiError(Application(Execution(RuntimePanicked("failed to decommit linear memory pages: madvise failed to decommit: {}\n\nCaused by:\n    Function not implemented (os error 38)"))))))
```

**Comment by volcano0dr** [comment]
@thempp66 You can try disabling the `pooling-allocator` feature at wasm-runtime.

**Comment by thempp66** [comment]
> @guzongmin @volcano0dr Recently when debugging pytorch + pbert (Pre-Training BERT with Permuted Language Model), it just error return if no `madvice` syscall supported. Making `madvice` just return success can work-around it. Perhaps for such kind of syscall (just advice or hint to improve system performace), Occlum can just return success with some warning message for most compatibility.

It works. Thanks!

**Comment by thempp66** [comment]
> @thempp66 You can try disabling the `pooling-allocator` feature at wasm-runtime.

It works. But it has a poorer performace comparing to implementing madvise with just return succ.
Thanks!
