### ISSUE TITLE
How to enable SFI

### ISSUE THREAD

**Issue by Bonjourz** [occlum/occlum#111]
Hi, the paper published in ASPLOS' 20 mentioned that Occlum use Intel MPX to achieve SFI. And in the wiki, you mentioned that:
> In addition, Occlum offers an optional multi-domain Software Fault Isolation scheme to isolate the Occlum LibOS processes if needed.

But I couldn't find any instructions to enable the SFI support... Also, I build some apps under the `demos/` directory using the scripts you provide, and then I disassemble the binaries using `objdump`. There is no assembly codes related to MPX.

I wonder whether the SFI implemented by MPX has been integrated into current. If so, is there any instructions showing how to enable it?

**Comment by tatetian** [comment]
We don't have the bandwidth to maintain the SFI feature in the latest versions of Occlum. For a version of Occlum with SFI support, checkout [this repo](https://github.com/occlum/reproduce-asplos20). Using this repo, the research artifact review committee of ASPLOS'20 has successfully reproduced our results reported in the paper.

**Comment by Bonjourz** [comment]
Got it. Thank you!

**Comment by chrisi2045** [comment]
@tatetian , I want to ask if occlum supports the SFI feature in its current version (The feature is mentioned in the current readme and the last post is 2 years old).

If it is, the same question as above: Are there instructions on how to enable it? :)

**Comment by Bonjourz** [comment]
Hi, @chrisi2045 , as mentioned above, SFI feature has not maintained in the latest versions of Occlum. For a version of Occlum with SFI support, checkout [this repo](https://github.com/occlum/reproduce-asplos20).

The **Artifact Appendix** section of our ASPLOS'20 [paper](https://dl.acm.org/doi/pdf/10.1145/3373376.3378469) shows the instructions for how to build the Occlum with SFI feature, and how to reproduce the results reported in the paper.

If you want to enhance the ability of fault isolation for Occlum, you may enable PKU feature (more details in [this page](https://github.com/occlum/occlum/blob/master/docs/pku_manual.md)). Such feature is for fault isolation between LibOS and user space applications.

**Comment by chrisi2045** [comment]
Hey @Bonjourz , many thanks for the fast awnser.

And also thanks for the hints about the Artifact Appendix and the PJU feature. I will have a look if this can solve my problem. :)
