### ISSUE TITLE
Question about "Experimental setup"

### ISSUE THREAD

**Issue by bronzeMe** [occlum/occlum#112]
Hi, does this paper use Intel SGX and Intel MPK feature simultaneously? However, it seems that no Intel CPU supports both SGX and MPX.
As stated in paper "We use machines with a two-core, 3.5GHz Intel Core i7 CPU (hyper-threading disabled)", 
Could you please give more detail about the CPU's information?
Thanks.

**Comment by tatetian** [comment]
Hi, do you mean MPK or MPX? There are many CPU models in the current generation of Intel Core or Xeon CPUs (SkyLake) can support both SGX and MPX. The next generation of Intel Xeon CPUs (IceLake) can support both SGX and MPK.

**Comment by bronzeMe** [comment]
@tatetian ,Thank you so much ! I am so sorry, I confused the word "MPK" with the word "MPX", In fact, occlum used Intel MPX rather than Intel MPK.

**Comment by tatetian** [comment]
Glad to help 😄
