### ISSUE TITLE
how to find the definition of sgx_interrupt_init

### ISSUE THREAD

**Issue by duanbing** [occlum/occlum#113]
sgx_interrupt_init as an extern function of occlum,   is defined in `intel/sgxsdk/lib64/libsgx_trts.a`,  which is supposed to be found in `occlum/intel-sgx`,  however, that's not true now.  

In other words, Have we simulated the Interruption Handle in  SGX SDK by AEX?  

Thanks

**Comment by tatetian** [comment]
Hi, the interrupt mechanism for Intel SGX SDK can be found in the [sgx_2.9.1_for_occlum](https://github.com/occlum/linux-sgx/tree/sgx_2.9.1_for_occlum) branch of occlum/linux-sgx. The APIs of the interrupt mechanism can be found [here](https://github.com/occlum/linux-sgx/blob/sgx_2.9.1_for_occlum/common/inc/sgx_interrupt.h) and the implementation is [here (the trusted part)](https://github.com/occlum/linux-sgx/blob/sgx_2.9.1_for_occlum/sdk/trts/trts_interrupt.cpp) and [here (the untrusted part)](https://github.com/occlum/linux-sgx/blob/sgx_2.9.1_for_occlum/psw/urts/linux/sig_handler.cpp#L158).

Regarding some descriptions of the design, allow me to repeat the comments in the C header:
```c
// File: common/inc/sgx_interrupt.h

// An interrupt mechanism for dynamically-loaded workloads in enclaves.
//
// Workloads in an enclave can be classified into two categories: statically-loaded and
// dynamically-loaded workloads. Statically-loaded workloads are application code that
// are built into the enclave; that is, they are part of the enclave since enclave initialization.
// Dynamically-loaded workloads, as the name suggests, are application code loaded after
// the enclave gets running.
//
// One typical example of dynamically-loaded workloads is user programs loaded by a SGX
// LibOS. The user programs could be arbitrary code. As a result, once the user program
// gets executed, the LibOS may never have the opportunity to take control of the CPU.
// Without the ability to regain the control, it is impossible for the LibOS to implement
// features like interruptible signal handler or preemptive in-enclave thread scheduling.
//
// To address the issue above, we implement the signal-based interrupt mechanism for
// dynamically-loaded workloads. With the provided APIs, the users can now interrupt the
// dynamically-loaded workloads executed in a SGX thread by simply sending a real-time
// POSIX signal (whosenumber is 64, the max value of signal numbers on Linux) to the SGX
// thread. The signal will be captured and (if the timing is good) a pre-registered
// interrupt handler will get executed inside the enclave.
//
// Note that the interrupt mechanism only performs the signal-to-interrupt conversion
// described above is in a best-effort manner. That is, sending a signal may not
// result in the interrupt handler getting called. For example, if the target SGX thread is
// executing some code outside the enclave, then the signal received will be simply
// ignored, thus not triggering the interrupt handler to be executed. So the users of
// the interrupt mechanism should find other means to determine if an interrupt has been
// delivered, and if not, whether and when to resend the interrupt (via POSIX signal).
```

**Comment by duanbing** [comment]
Thanks for your kind replying.   BTW, any changelog for us to trace all the changes against the upstream of intel-sgx?

**Comment by tatetian** [comment]
Occlum's fork of Intel SGX SDK has been constantly rebased to the latest version of Intel SGX SDK. So all Occlum's modifications are the last N commits in a branch. For the sgx_2.9.1_for_occlum branch of Occlum, its changes related to vanilla 2.9.1 can be found [here](https://github.com/occlum/linux-sgx/compare/4bb545cde056010293d0388bfa3a19882aa2ec4c...sgx_2.9.1_for_occlum).

**Comment by duanbing** [comment]
Thanks a billion!
