### ISSUE TITLE
[BUG]panic!("IOCTRL IOCTL_GET_DCAP_QUOTE_SIZE failed") when run dcap_test.rs

### ISSUE THREAD

**Issue by prz23** [occlum/occlum#1133]
# Describe the bug
run dcap ra test with a panic "IOCTRL IOCTL_GET_DCAP_QUOTE_SIZE failed".
https://github.com/occlum/occlum/blob/master/tools/toolchains/dcap_lib/examples/dcap_test.rs

# To reproduce
![image](https://user-images.githubusercontent.com/29329767/216218020-1c07897a-5473-4a06-878b-4e37fc20c3dc.png)

     Running `/root/occlum/tools/toolchains/dcap_lib/target/x86_64-unknown-linux-musl/debug/examples/dcap_test`
thread 'main' panicked at 'IOCTRL IOCTL_GET_DCAP_QUOTE_SIZE failed', src/occlum_dcap.rs:70:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by qzheng527** [comment]
@prz23 You can't simply run the dcap_test by occlum-cargo. The dcap_test has to be running inside TEE/Occlum.
Please refer to the [dcap demo](https://github.com/occlum/occlum/blob/master/demos/remote_attestation/dcap/run_dcap_quote_on_occlum.sh) about how.

**Comment by prz23** [comment]
I copy code from [dcap example](https://github.com/occlum/occlum/blob/master/tools/toolchains/dcap_lib/examples/dcap_test.rs) to [dcap demo](https://github.com/occlum/occlum/blob/master/demos/remote_attestation/dcap/run_dcap_quote_on_occlum.sh) 
and run it with `./run_rust_demo_on_occlum.sh`   in HW mode and  `docker run -it --rm --privileged -v /dev/sgx_enclave:/dev/sgx/enclave -v /dev/sgx_provision:/dev/sgx/provision -v /mnt/occlum:/root/occlum occlum/occlum:0.29.1-ubuntu20.04`

The same error is still reported

![image](https://user-images.githubusercontent.com/29329767/216250192-7bfd6b33-9814-42d0-bc1c-27248606fb5d.png)

![image](https://user-images.githubusercontent.com/29329767/216249652-d3dd59fd-1059-4bc9-ad47-dedcb2b94333.png)

[get_platform_quote_cert_data ../qe_logic.cpp:378] Error returned from the p_sgx_get_quote_config API. 0xe019
thread 'main' panicked at 'IOCTRL IOCTL_GET_DCAP_QUOTE_SIZE failed', /root/occlum/tools/toolchains/dcap_lib/src/occlum_dcap.rs:70:13

**Comment by qzheng527** [comment]
@prz23 Not the same errot. Using our demo, the "0xe019" means network error.
So please make sure:
1. There is available PCCS service your container can access.
2. Modify the PCCS URL in the container file "/etc/sgx_default_qcnl.conf" to point to the right address.

**Comment by prz23** [comment]
I set the PCCS URL to `https://sgx-dcap-server.cn-shanghai.aliyuncs.com/sgx/certification/v3/` in "/etc/sgx_default_qcnl.conf"
and it works fine.
![image](https://user-images.githubusercontent.com/29329767/216499886-83ad98ac-69ef-4b6d-a436-d04ccf357fda.png)
