### ISSUE TITLE
support proxy-friendly docker cmd ?

### ISSUE THREAD

**Issue by yang8621** [occlum/occlum#114]
Is it possible to add proxy support to docker cmd? 

1. tools/docker/build_image.sh
docker build --build-arg http_proxy="XXXX" --build-arg https_proxy="XXXX" -f "$script_dir/Dockerfile.$os_name" -t "occlum/occlum:$occlum_label-$os_name" .

2. docker run -it --env HTTP_PROXY="XXXX" --env HTTPS_PROXY="XXXX" --device /dev/isgx occlum/occlum:0.14.0-ubuntu18.04

**Comment by tatetian** [comment]
Sure. Sounds great. Could you kindly send us a PR for this feature?

**Comment by tatetian** [comment]
As discussed in the other PR, this is better supported with `~/.docker/config.json`. So I am closing this issue.

For more info about Docker proxy, see [the doc here](https://docs.docker.com/network/proxy/).
