### ISSUE TITLE
Is this the right way to seal data in occlum ?

### ISSUE THREAD

**Issue by prz23** [occlum/occlum#1140]
Assuming this code is run in oclum:

![image](https://user-images.githubusercontent.com/29329767/216937713-78ab443d-8270-4ff0-9334-aa87b6d16d5c.png)

 Will the secret be sealed automatically and saved after `std::fs::write()` is called?

**Comment by liqinggd** [comment]
Correct, the data will be encrypted automatically if you write to SEFS.

**Comment by prz23** [comment]
I tried it and it was right.
