### ISSUE TITLE
[BUG]Can the occlum-cargo version be updated?

### ISSUE THREAD

**Issue by prz23** [occlum/occlum#1147]
Can the version of the occlum-cargo`cargo 1.61.0-nightly (ea2a21c 2022-02-15)` be updated? There will be this error when compiling the rayon library, but there will be no problem with older or newer versions of cargo.

If the update is not possible, the only option is to fork the library, add the feature `#![feature(const_fn_trait_bound)]` , and then patch it？

![image](https://user-images.githubusercontent.com/29329767/217710393-6748d5e0-15dd-48db-8b3e-dae07373c0a7.png)

**Comment by liqinggd** [comment]
The `occlum-cargo` is a bash script wrapper of the cargo installed in, you can just modify it to use another version of cargo.

The installation of `occlum-cargo` is here: https://github.com/occlum/occlum/blob/master/tools/toolchains/rust/build.sh

**Comment by prz23** [comment]
thanks
