### ISSUE TITLE
How Can I access the mysql running in the Occlum?

### ISSUE THREAD

**Issue by Klein920116** [occlum/occlum#1148]
Can I access mysql database via ip:port?

**Comment by qzheng527** [comment]
@Klein920116 Yes，Occlum mysql demo makes mysql completely running in Occlum (TEE). In default, users can access mysql DB via 127.0.0.1:3306. You can refer to the [script ](https://github.com/occlum/occlum/blob/master/demos/mysql/run_mysql_client.sh#L28)for more details.

**Comment by Klein920116** [comment]
> 


> @Klein920116 Yes，Occlum mysql demo makes mysql completely running in Occlum (TEE). In default, users can access mysql DB via 127.0.0.1:3306. You can refer to the [script ](https://github.com/occlum/occlum/blob/master/demos/mysql/run_mysql_client.sh#L28)for more details.

If I wanna connect mysql outside Occlum docker container, what should I do?

**Comment by qzheng527** [comment]
> > 
> 
> > @Klein920116 Yes，Occlum mysql demo makes mysql completely running in Occlum (TEE). In default, users can access mysql DB via 127.0.0.1:3306. You can refer to the [script ](https://github.com/occlum/occlum/blob/master/demos/mysql/run_mysql_client.sh#L28)for more details.
> 
> If I wanna connect mysql outside Occlum docker container, what should I do?

That is beyond Occlum. But generally, just image Occlum mysql as the general mysql running in the container.
Using the same way to access the service in container, such as port mapping or starting the container with "--network host".

**Comment by Klein920116** [comment]
> > > 
> > 
> > 
> > > @Klein920116 Yes，Occlum mysql demo makes mysql completely running in Occlum (TEE). In default, users can access mysql DB via 127.0.0.1:3306. You can refer to the [script ](https://github.com/occlum/occlum/blob/master/demos/mysql/run_mysql_client.sh#L28)for more details.
> > 
> > 
> > If I wanna connect mysql outside Occlum docker container, what should I do?
> 
> That is beyond Occlum. But generally, just image Occlum mysql as the general mysql running in the container. Using the same way to access the service in container, such as port mapping or starting the container with "--network host".

Cool, will try it.

**Comment by Klein920116** [comment]
> > > 
> > 
> > 
> > > @Klein920116 Yes，Occlum mysql demo makes mysql completely running in Occlum (TEE). In default, users can access mysql DB via 127.0.0.1:3306. You can refer to the [script ](https://github.com/occlum/occlum/blob/master/demos/mysql/run_mysql_client.sh#L28)for more details.
> > 
> > 
> > If I wanna connect mysql outside Occlum docker container, what should I do?
> 
> That is beyond Occlum. But generally, just image Occlum mysql as the general mysql running in the container. Using the same way to access the service in container, such as port mapping or starting the container with "--network host".

**Hi, I try to use command “mysql -h 172.17.0.1 -u root -p”on host machine to access mysql database, the errors show below:
ERROR 1130 (HY000): Host '172.17.0.1' is not allowed to connect to this MySQL server**

**Comment by Ariel08081214** [comment]
@Klein920116 Hai，can you show me how did you deal with this case？ Thank you so much
