### ISSUE TITLE
Some problems starting under substrate

### ISSUE THREAD

**Issue by yingjun-wu** [occlum/occlum#1151]
Hello, when I use occlum to run substrate, there is the following problem:
1. After I start substrate successfully, when I try to restart again it will fail.
```
root@554e4e12b9b1:~/test# occlum run /bin/node-template --chain=local --alice
Error: Service(Client(Backend("Corruption: no log_file_number, next_file_number, last_sequence entry in MANIFEST in file /root/.local/share/node-template/chains/local_testnet/db/full/MANIFEST-000009")))
2023-02-13 07:58:16 Substrate Node    
2023-02-13 07:58:16 ✌️  version 4.0.0-dev-5d9e5ebb98a    
2023-02-13 07:58:16 ❤️  by Substrate DevHub <https://github.com/substrate-developer-hub>, 2017-2023    
2023-02-13 07:58:16 📋 Chain specification: Local Testnet    
2023-02-13 07:58:16 🏷  Node name: Alice    
2023-02-13 07:58:16 👤 Role: AUTHORITY    
2023-02-13 07:58:16 💾 Database: RocksDb at /root/.local/share/node-template/chains/local_testnet/db/full    
2023-02-13 07:58:16 ⛓  Native runtime: node-template-100 (node-template-1.tx1.au1)
```
2. Find out whether the encrypted files saved in sefs can be saved separately, because this involves the need to rebuild when the code is updated, resulting in the loss of original data

Thanks!!

### Environment
- HW: Intel SGX
- OS: Ubuntu20.04
- Occlum version: 0.29.4

**Comment by jessehui** [comment]
When you update the code and rebuild the Occlum instance with `occlum build`, all previous data will be cleaned including the files saved by SEFS. You can try using the hostFS to save data. The data will be saved to the host directory and will not be cleaned after the rebuild. For more info, please take a look here: https://github.com/occlum/occlum/blob/master/docs/fs_overview.md#hostfs .

**Comment by yingjun-wu** [comment]
@jessehui thank you for your reply! 
Use hostFS to save data, how do I encrypt data?

**Comment by jessehui** [comment]
I am not familiar with your application. As far as I know, most applications don't need to rebuild in the deployment stage. Thus, you can safely use SEFS for encryption. If you must rebuild even in the deployment stage, one way is to encrypt by yourself, by enabling or adding encryption capabilities for your application.

**Comment by yingjun-wu** [comment]
> I am not familiar with your application. As far as I know, most applications don't need to rebuild in the deployment stage. Thus, you can safely use SEFS for encryption. If you must rebuild even in the deployment stage, one way is to encrypt by yourself, by enabling or adding encryption capabilities for your application.

In occlum, what encryption method has the same effect as the seal_data in sgx?

**Comment by liqinggd** [comment]
> In occlum, what encryption method has the same effect as the seal_data in sgx?

You can send the ioctl() command to "/dev/sgx" to generate a seal key, then encrypt it with some encryption method(e.g. openssl).

**Comment by yingjun-wu** [comment]
> > In occlum, what encryption method has the same effect as the seal_data in sgx?
> 
> You can send the ioctl() command to "/dev/sgx" to generate a seal key, then encrypt data with some encryption method(e.g. openssl).

Thanks!
