### ISSUE TITLE
[BUG]Cannot open Quote Provider Library in deployment demos

### ISSUE THREAD

**Issue by prz23** [occlum/occlum#1153]
Fitst I modify the DEVICE_OPTION in [script](https://github.com/occlum/occlum/blob/master/demos/deployment/deploy_image_test.sh
) by`--device /dev/sgx/enclave --device /dev/sgx/provision`

Then I build it with `./deploy_image_test.sh ubuntu20.04`

The image built report this error when starting:

`Cannot open Quote Provider Library libdcap_quoteprov.so.1 and libdcap_quoteprov.so `

https://github.com/occlum/occlum/blob/master/demos/deployment/Dockerfile_template.ubuntu20.04
![image](https://user-images.githubusercontent.com/29329767/218415631-dd5eaec5-a711-48e3-84a2-40fc590f5991.png)
![image](https://user-images.githubusercontent.com/29329767/218423500-fa20621e-6c52-499d-9179-d3acb551eaf7.png)

Ps. DCAP and other sgx functions are working properly in occlum/occlum:0.29.1-ubuntu20.04 with this platform.

**Comment by jessehui** [comment]
I have never met this problem. I think it is related to the device you mapped into the container. Please check if the property of the device file is the same as the files on the host. If there is nothing wrong, please raise an issue at the Intel SGX SDK's community. The error message is from the AESM service.

**Comment by prz23** [comment]
```
 dmesg | grep sgx
[    2.907283] systemd[1]: Set hostname to <sgx007>.
[    3.053442] intel_sgx: loading out-of-tree module taints kernel.
[    3.054246] intel_sgx: module verification failed: signature and/or required key missing - tainting kernel
[    3.055146] intel_sgx: EPC section 0x140000000-0x237ffffff
[    3.063237] intel_sgx: Intel SGX DCAP Driver v1.41
```

**Comment by prz23** [comment]
Install this, and the aesm is fixed
`apt-get install libsgx-urts libsgx-dcap-ql libsgx-dcap-default-qpl`
