### ISSUE TITLE
How to locate or debug the following error when running /demos/hello_c

### ISSUE THREAD

**Issue by xyzhao2018** [occlum/occlum#116]
Meet the following error for both HW and SIM sgx on both 13.1 and 14.0 when running /demos/hello_c, 
root@053bc286b5d0:~/demos/hello_c/occlum_context#  occlum run /bin/hello_world
/opt/occlum/build/bin/occlum: line 248:   295 Illegal instruction     (core dumped) RUST_BACKTRACE=1 "$context_dir/build/bin/occlum-run" "$@"

Sgx driver/sdk/psw has been installed, the following steps can pass. 
$ occlum-gcc -o hello_world hello_world.c
$ ./hello_world
Hello World
$ mkdir occlum_context && cd occlum_context
$ occlum init
$ cp ../hello_world image/bin/
$ occlum build or $SGX_MODE=SIM occlum build

**Comment by tatetian** [comment]
Some questions to aid debugging:
1. Was enable_rdfsbase kernel module installed? If not, install it.
2. Did you use the Occlum Docker image or build you own environment? If you built your own environment, refer to Occlum's Dockerfile to follow the exact steps.
3. Could you try to run Intel SGX SDK's sample code (which can be found at `/opt/intel/sgxsdk/SampleCode`)?

**Comment by xyzhao2018** [comment]
Actually, I have installed enable_rdfsbase align with sgx driver/SDK/PSW. 
But after build occlum environment with "./build_image.sh  0.14.0 ubuntu18.04", the sgx driver/SDK are gone. 
So I have to re-install that component. 

Previously, enable_rdfsbase can pass compile and install successfully. 
But it is failed with the following error when try again just now. 
What's the error and how to fix it? 

~/enable_rdfsbase$ make
make -C /lib/modules/5.4.0-42-generic/build SUBDIRS=/home/shirey/enable_rdfsbase  modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-42-generic'
arch/x86/Makefile:147: CONFIG_X86_X32 enabled but no binutils support
  HOSTCC  scripts/basic/fixdep
scripts/basic/fixdep.c:410:1: fatal error: opening dependency file scripts/basic/.fixdep.d: Permission denied
 }
 ^
compilation terminated.
scripts/Makefile.host:107: recipe for target 'scripts/basic/fixdep' failed
make[3]: *** [scripts/basic/fixdep] Error 1
Makefile:527: recipe for target 'scripts_basic' failed
make[2]: *** [scripts_basic] Error 2
Makefile:704: recipe for target 'include/config/auto.conf.cmd' failed
make[1]: *** [include/config/auto.conf.cmd] Error 2
make[1]: *** [include/config/auto.conf.cmd] Deleting file 'include/config/tristate.conf'
make[1]: unlink: include/config/tristate.conf: Permission denied
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-42-generic'
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by xyzhao2018** [comment]
Running the sample under /opt/intel/sgxsdk/SampleCode/SampleEnclave, seems successfully. Please have a look. 

root@83dc34c67aee:/opt/intel/sgxsdk/SampleCode/SampleEnclave# make
make[1]: Entering directory '/opt/intel/sgxsdk/SampleCode/SampleEnclave'
GEN  =>  App/Enclave_u.h
CC   <=  App/Enclave_u.c
CXX  <=  App/App.cpp
CXX  <=  App/Edger8rSyntax/Types.cpp
CXX  <=  App/Edger8rSyntax/Pointers.cpp
CXX  <=  App/Edger8rSyntax/Arrays.cpp
CXX  <=  App/Edger8rSyntax/Functions.cpp
CXX  <=  App/TrustedLibrary/Thread.cpp
CXX  <=  App/TrustedLibrary/Libc.cpp
CXX  <=  App/TrustedLibrary/Libcxx.cpp
LINK =>  app
GEN  =>  Enclave/Enclave_t.h
CC   <=  Enclave/Enclave_t.c
CXX  <=  Enclave/Edger8rSyntax/Arrays.cpp
CXX  <=  Enclave/Edger8rSyntax/Functions.cpp
CXX  <=  Enclave/Edger8rSyntax/Pointers.cpp
CXX  <=  Enclave/Edger8rSyntax/Types.cpp
CXX  <=  Enclave/Enclave.cpp
CXX  <=  Enclave/TrustedLibrary/Libc.cpp
CXX  <=  Enclave/TrustedLibrary/Libcxx.cpp
CXX  <=  Enclave/TrustedLibrary/Thread.cpp
LINK =>  enclave.so
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>0x40000</StackMaxSize>
    <HeapMaxSize>0x100000</HeapMaxSize>
    <TCSNum>10</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>
tcs_num 10, tcs_max_num 10, tcs_min_pool 1
The required memory is 4100096B.
The required memory is 0x3e9000, 4004 KB.
Succeed.
SIGN =>  enclave.signed.so
The project has been built in debug hardware mode.
make[1]: Leaving directory '/opt/intel/sgxsdk/SampleCode/SampleEnclave'
root@83dc34c67aee:/opt/intel/sgxsdk/SampleCode/SampleEnclave# ./app
Checksum(0x0x7fff09e72130, 100) = 0xfffd4143
Info: executing thread synchronization, please wait...  
Info: SampleEnclave successfully returned.
Enter a character before exit ...

**Comment by yang8621** [comment]
seems a compatibility issue with kernel 5.4. 
switch to 5.3 or older and have a try.

**Comment by xyzhao2018** [comment]
Yes, switch to 5.3 and install enable_rdfsbase, it works for both HW and SIM now.

**Comment by guzongmin** [comment]
below patch may help you to make it work in new kernel.

diff --git a/Makefile b/Makefile
index bc0a80e..60d7d1a 100644
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,6 @@
 obj-m += enable_rdfsbase.o

-KERNEL_MAKE := $(MAKE) -C /lib/modules/$(shell uname -r)/build SUBDIRS=$(PWD)
+KERNEL_MAKE := $(MAKE) -C /lib/modules/$(shell uname -r)/build M=$(shell pwd)

 all:
        $(KERNEL_MAKE) modules

**Comment by yang8621** [comment]
> below patch may help you to make it work in new kernel.
> 
> diff --git a/Makefile b/Makefile
> index bc0a80e..60d7d1a 100644
> --- a/Makefile
> +++ b/Makefile
> @@ -1,6 +1,6 @@
> obj-m += enable_rdfsbase.o
> 
> -KERNEL_MAKE := $(MAKE) -C /lib/modules/$(shell uname -r)/build SUBDIRS=$(PWD)
> +KERNEL_MAKE := $(MAKE) -C /lib/modules/$(shell uname -r)/build M=$(shell pwd)
> 
> all:
> $(KERNEL_MAKE) modules

Thanks. It works.
