### ISSUE TITLE
[BUG]fail to run 'system()' in .C when using 'occlum run', without any error output

### ISSUE THREAD

**Issue by wydxyreh** [occlum/occlum#1174]
# Describe the bug
2023-02-27，with Occlum 0.29.4
I followed the Occlum docs, and run `helloworld` successfully. But when I add `system("ls");` to `helloworld.c` and repeat last operations. Occlum works correctly in libos, but failed with SGX without any error output.
For example, I run `occlum-gcc -o hello_world hello_world.c` and `./hello_world`, then I will get:
```
root@5fdd9947b371:~/test# ./hello_world 
hello_world  hello_world.c  occlum_instance
Hello World
```
but after `occlum build` and `occlum run`, I can only get
```
root@5fdd9947b371:~/test/occlum_instance# occlum run /bin/hello_world 
Hello World
```
I'm using `ls` command for example. Actually my real command is `system("rabbitmq-server -detached");`. All the thing works same as `ls`, and I'm sure that `ls` didn't get executed in the example.
I'm now wondering what caused this problem. Maybe I missed something or it is an inner problem in Occlum?

# To reproduce
1. vim helloworld.c:
```
#include <stdio.h>
#include <stdlib.h>

int main() {
    //system("rabbitmq-server -detached");
    system("ls");
    printf("Hello World\n");
    //system("rabbitmqctl status");
    return 0;
}
```

3.follow 'Occlun introduction' in Occlum docs
```
occlum-gcc -o hello_world hello_world.c
./hello_world
```

4.
`occlum new occlum_instance`

5.
```
cp ../hello_world image/bin/
occlum build
occlum run /bin/hello_world
```

# Expected behavior
I need to get:
```
root@5fdd9947b371:~/test/occlum_instance# occlum run /bin/hello_world 
hello_world  hello_world.c  occlum_instance
Hello World
```
But now I actually get:
```
root@5fdd9947b371:~/test/occlum_instance# occlum run /bin/hello_world 
Hello World
```

# Logs
No logs and no output.

# Environment
- HW: SGX2
- OS: Ubuntu20.04
- Occlum version: 0.29.4

# Possible solution/Implementation
I'm working on a subject about combine MQ with TEE. 
I suppose this problem may have some relation with `Socket`. Like `SCM_RIGTHS` or something else.

**Comment by wydxyreh** [comment]
> Thank you for using Occlum. There are actually two things you were missing:
> 
> 1. Take a closer look at `system`, it is executing the shell command. Thus, it needs a shell to execute the command. For Occlum, it is a completely isolated environment with the host, thus, you need to provide everything needed, including the shell. You can take a look at the [bash demo](https://github.com/occlum/occlum/tree/master/demos/bash). As same as the shell, if you want to execute other binaries with the shell, you must provide those binaries, in your example, the `rabbitmq-server` binaries.
> 2. Please make sure to check the return value of your code. So that you can know if there is any mistake as soon as possible.
> 
> What's more, If there is anything weird during running your application, you can enable logging for Occlum by setting the env variable `OCCLUM_LOG_LEVEL=trace`. And try to solve the error if you are familiar and can send us the log if you can't handle.



Thanks for your reply! I spent some time relearning about 'Mount Support' part in Occlum docs and 'bash' part in 'demos'. And I modified 'bash' demo to try to run 'rabbitmq-server' command in it.

First, I use 'which rabbitmq-server' and 'which erl' in docker, and I get '/usr/sbin/rabbitmq-server' and '/usr/bin/erl'. So I modified 'bash.yaml' like this:
```
includes:
  - base.yaml
# bash
targets:
  # copy bash and busybox
  - target: /bin
    copy:
      - files:
        - /opt/occlum/toolchains/bash/glibc/bash
        - /opt/occlum/toolchains/busybox/glibc/busybox
        - ../occlum_bash_test.sh
        - /usr/sbin/rabbitmq-server
        - /usr/bin/erl
```
Second, to setting the env variable `OCCLUM_LOG_LEVEL=trace`, I modify `run_bash_demo.sh` like this:
```
new_json="$(jq '.resource_limits.user_space_size = "600MB" |
                .resource_limits.kernel_space_stack_size ="2MB" |
                .env.OCCLUM_LOG_LEVEL = trace ' Occlum.json)" && \
    echo "${new_json}" > Occlum.json
```
Last, I add codes in `occlum_bash_test.sh`:
```
#Test RBMQ
rabbitmq-server -detached
busybox ls /root
rabbitmqctl status
```
The goal of first line is to run rabbitmq, and the second is `nop`, the third is to check the running state of rabbitmq.
But I got:
```
+ rabbitmq-server -detached
/bin/occlum_bash_test.sh: posix_spawn error code = 2
: No such file or directory
/bin/occlum_bash_test.sh: posix_spawn: No such file or directory
+ busybox ls /root
+ rabbitmqctl status
/bin/occlum_bash_test.sh: posix_spawn: No such file or directory
+ busybox echo 'Test is done'
Test is done
```
I‘ve thought about it for a long time and I don't konw where the problem lies.

**Comment by qzheng527** [comment]
@wydxyreh Please use the absolute path for "rabbitmq-server" in the bash script.

**Comment by wydxyreh** [comment]
> @wydxyreh Please use the absolute path for "rabbitmq-server" in the bash script.

I've used absolute path for `rabbitmq-server` in `occlum_bash_test.sh` , but I still get the same error:
```
+ /usr/sbin/rabbitmq-server -detached
/bin/occlum_bash_test.sh: posix_spawn: No such file or directory
+ busybox ls /root
+ rabbitmqctl status
/bin/occlum_bash_test.sh: posix_spawn: No such file or directory
+ busybox echo 'Test is done'
Test is done
```
I also tried to run `rabbitmq-server` in /occlum_instance/image, but also failed:
```
+ /root/bash/occlum_instance/image/bin/rabbitmq-server -detached
/bin/occlum_bash_test.sh: posix_spawn: No such file or directory
+ busybox ls /root
+ rabbitmqctl status
/bin/occlum_bash_test.sh: posix_spawn: No such file or directory
+ busybox echo 'Test is done'
Test is done
```
I can separately run `rabbitmq` successfully in the shell, but both failed in the `.sh` file.

**Comment by qzheng527** [comment]
> > @wydxyreh Please use the absolute path for "rabbitmq-server" in the bash script.
> 
> I've used absolute path for `rabbitmq-server` in `occlum_bash_test.sh` , but I still get the same error:
> 
> ```
> + /usr/sbin/rabbitmq-server -detached
> /bin/occlum_bash_test.sh: posix_spawn: No such file or directory
> + busybox ls /root
> + rabbitmqctl status
> /bin/occlum_bash_test.sh: posix_spawn: No such file or directory
> + busybox echo 'Test is done'
> Test is done
> ```
> 
> I also tried to run `rabbitmq-server` in /occlum_instance/image, but also failed:
> 
> ```
> + /root/bash/occlum_instance/image/bin/rabbitmq-server -detached
> /bin/occlum_bash_test.sh: posix_spawn: No such file or directory
> + busybox ls /root
> + rabbitmqctl status
> /bin/occlum_bash_test.sh: posix_spawn: No such file or directory
> + busybox echo 'Test is done'
> Test is done
> ```
> 
> I can separately run `rabbitmq` successfully in the shell, but both failed in the `.sh` file.

The path in Occlum should be `/bin/rabbitmq-server` according to your yaml file.

**Comment by wydxyreh** [comment]
Thanks for your help! After I modified the path into `/bin/rabbitmq-server -detached` , I still get the same error:
```
+ /bin/rabbitmq-server -detached
/bin/occlum_bash_test.sh: posix_spawn error code = 2
: No such file or directory
/bin/occlum_bash_test.sh: posix_spawn: No such file or directory
+ busybox ls /root
+ rabbitmqctl status
/bin/occlum_bash_test.sh: posix_spawn: No such file or directory
+ busybox echo 'Test is done'
Test is done
```

**Comment by qzheng527** [comment]
Please add the below into your script.
```
busybox ls -l /bin/
/bin/rabbitmq-server --help
```

**Comment by wydxyreh** [comment]
> Please add the below into your script.
> 
> ```
> busybox ls -l /bin/
> /bin/rabbitmq-server --help
> ```

I add the above into `occlum_bash_test.sh` and put them to the top of my `#rabbitmq test`, so here is the result:
```
+ busybox ls -l /bin/
total 0
-rwxr-xr-x    1 0        0          5983472 Jan  1  1970 bash
-rwxr-xr-x    1 0        0          1039048 Jan  1  1970 busybox
-rwxr-xr-x    1 0        0             1478 Jan  1  1970 erl
-rwxr-xr-x    1 0        0             1951 Jan  1  1970 occlum_bash_test.sh
-rwxr-xr-x    1 0        0             2759 Jan  1  1970 rabbitmq-server
+ /bin/rabbitmq-server --help
/bin/occlum_bash_test.sh: posix_spawn error code = 2
: No such file or directory
/bin/occlum_bash_test.sh: posix_spawn: No such file or directory
```

**Comment by qzheng527** [comment]
You can try `occlum run /bin/rabbitmq-server --help` directly.
If works, try `occlum run /bin/rabbitmq-server -detached`.
If still not working, please try `OCCLUM_LOG_LEVEL=trace occlum run /bin/rabbitmq-server --help`.

**Comment by wydxyreh** [comment]
> OCCLUM_LOG_LEVEL=trace occlum run /bin/rabbitmq-server --help

I tried `occlum run /bin/rabbitmq-server --help` directly, but still failed:
```
failed to boot up LibOS: ENOENT (#2, No such file or directory): EntryNotFound
[ERROR] occlum-pal: occlum_ecall_new_process returns ENOENT (line 210, file src/pal_api.c)
```
So I try `OCCLUM_LOG_LEVEL=trace occlum run /bin/rabbitmq-server --help` directly and get the error information:
```
[2023-03-06T09:54:29.369Z][ INFO][T0][#0] Process created: elf = /bin/init, pid = 1
[2023-03-06T09:54:29.369Z][TRACE][T1][#1][ArchPrctl] Syscall { num = ArchPrctl, code = 4098, addr = 0x7f1975c94d88 }
[2023-03-06T09:54:29.370Z][DEBUG][T1][#1][ArchPrctl] do_arch_prctl: code: ARCH_SET_FS, addr: 0x7f1975c94d88
[2023-03-06T09:54:29.370Z][TRACE][T1][#1][ArchPrctl] Retval = 0x0
[2023-03-06T09:54:29.370Z][TRACE][T1][#2][SetTidAddress] Syscall { num = SetTidAddress, tidptr = 0x7f1975c95364 }
[2023-03-06T09:54:29.370Z][DEBUG][T1][#2][SetTidAddress] set_tid_address: tidptr: 0x7f1975c95364
[2023-03-06T09:54:29.370Z][TRACE][T1][#2][SetTidAddress] Retval = 0x1
[2023-03-06T09:54:29.370Z][TRACE][T1][#3][····Open] Syscall { num = Open, path = 0x7f19781ff9a0, flags = 524288, mode = 0 }
[2023-03-06T09:54:29.370Z][DEBUG][T1][#3][····Open] openat: fs_path: FsPath { Absolute("/opt/occlum/toolchains/gcc/x86_64-linux-musl/lib/libgcc_s.so.1") }, flags: 0o2000000, mode: 0o0
[2023-03-06T09:54:29.370Z][DEBUG][T1][#3][····Open] lookup_inode: cwd: "/", path: "/opt/occlum/toolchains/gcc/x86_64-linux-musl/lib/libgcc_s.so.1"
[2023-03-06T09:54:29.370Z][ERROR][T1][#3][····Open] Error = ENOENT (#2, No such file or directory): EntryNotFound
[2023-03-06T09:54:29.370Z][TRACE][T1][#3][····Open] Retval = 0xfffffffffffffffe
[2023-03-06T09:54:29.370Z][TRACE][T1][#4][····Open] Syscall { num = Open, path = 0x7f19781ff750, flags = 524288, mode = 438 }
[2023-03-06T09:54:29.370Z][DEBUG][T1][#4][····Open] openat: fs_path: FsPath { Absolute("/etc/ld-musl-x86_64.path") }, flags: 0o2000000, mode: 0o666
[2023-03-06T09:54:29.370Z][DEBUG][T1][#4][····Open] lookup_inode: cwd: "/", path: "/etc/ld-musl-x86_64.path"
[2023-03-06T09:54:29.370Z][ERROR][T1][#4][····Open] Error = ENOENT (#2, No such file or directory): EntryNotFound
[2023-03-06T09:54:29.370Z][TRACE][T1][#4][····Open] Retval = 0xfffffffffffffffe
[2023-03-06T09:54:29.370Z][TRACE][T1][#5][····Open] Syscall { num = Open, path = 0x7f19781ff9a0, flags = 524288, mode = 0 }
[2023-03-06T09:54:29.370Z][DEBUG][T1][#5][····Open] openat: fs_path: FsPath { Absolute("/lib/libgcc_s.so.1") }, flags: 0o2000000, mode: 0o0
[2023-03-06T09:54:29.370Z][DEBUG][T1][#5][····Open] lookup_inode: cwd: "/", path: "/lib/libgcc_s.so.1"
[2023-03-06T09:54:29.370Z][DEBUG][T1][#5][····Open] convert_to_abs_path: cwd: "/", path: "/lib/libgcc_s.so.1"
```
The outputs above are all the error information in the shell. In my opinion, the error may have something to do with `fs.mount`.

**Comment by qzheng527** [comment]
Please try `readelf -h occlum_instance/image/bin/rabbitmq-server` in your container.
I think it is not a executable binary.

**Comment by wydxyreh** [comment]
> 

After I try `readelf -h occlum_instance/image/bin/rabbitmq-server` in my container, I get:
```
readelf: Error: Not an ELF file - it has the wrong magic bytes at the start
```
I uesd to try `head occlum_instance/image/bin/rabbitmq-server`, so I used to think it is a executable binary.
```
root@52b3166ebf5f:~/bash# head occlum_instance/image/bin/rabbitmq-server
#!/bin/sh

## This Source Code Form is subject to the terms of the Mozilla Public
## License, v. 2.0. If a copy of the MPL was not distributed with this
## file, You can obtain one at https://mozilla.org/MPL/2.0/.
##
## Copyright (c) 2018-2020 VMware, Inc. or its affiliates.  All rights reserved.
##

SCRIPT="$(basename "$0")"
```
