### ISSUE TITLE
[BUG]Why ltp cannot run success?

### ISSUE THREAD

**Issue by Antone077** [occlum/occlum#1179]
# Describe the bug
I want to run linux-ltp, and I follow the Readme.md's steps. But I'm not find the /opt/ltp this folder. Then I run `bash run-ltp.sh -f syscalls-occlum ` this command, it cann't exec successful.
# To reproduce
1. `docker run -it --privileged -v /dev/sgx:/dev/sgx occlum/occlum:0.29.5-ubuntu20.0`
2. `cd demos/linux-ltp`
3. `./dl_and_build_ltp.sh`
4. `prepare_ltp.sh`
5. `bash run-ltp.sh -f syscalls-occlum ` 

# Expected behavior
Expected behavior should be like ltp on linux.

# Logs
`FATAL: LTP not installed correctly
INFO:  Follow directions in INSTALL!`

# Environment

- HW: [SGX1] 
- OS: [Ubuntu22.04]
- Occlum version: [0.29.5]

**Comment by qzheng527** [comment]
@Antone077 To run the LTP in Occlum, the step 5 command is "occlum run /opt/ltp/run-ltp.sh -f syscalls-occlum".
We will update the README.

**Comment by Antone077** [comment]
@qzheng527 Thanks!Another I have a question,hope you can Solve the confusion. In this /demos/linux-ltp/syscalls-occlum folder，like these syscall tests 
`chdir01 chdir01
chdir01A symlink01 -T chdir01
#chdir04 chdir04`

The chdir04 is not pass in Occlum? The other can pass?

**Comment by Antone077** [comment]
@qzheng527 But when I run `./dl_and_build_ltp.sh` this command, it not report other error. I suppose this can make install successfully. When I check `opt/` folder, I'm not find `ltp/` folder, only `intel/` and `occlum/`

**Comment by qzheng527** [comment]
@Antone077 The purpose of LTP test in Occlum is to verify the stability and compatibility to Linux app. There is no guarantee that all the test cases defined in syscalls-occlum can pass. The bottom line is they may fail but they can't panic the Occlum.

**Comment by qzheng527** [comment]
> @qzheng527 But when I run `./dl_and_build_ltp.sh` this command, it not report other error. I suppose this can make install successfully. When I check `opt/` folder, I'm not find `ltp/` folder, only `intel/` and `occlum/`

The occlum has different file system view compared with Host OS. You can find the occlum FS content in the ltp_instance/image/.

**Comment by Antone077** [comment]
@qzheng527 OK, I get it! Thank you very much!
