### ISSUE TITLE
How to export log file from the occlum?

### ISSUE THREAD

**Issue by nengc** [occlum/occlum#119]
I need to export log file from the occlum, but can not find the file location.

**Comment by guzongmin** [comment]
You can put the log file in the /host folder. Then you will get the log file in same folder of image.

**Comment by nengc** [comment]
Hi, @guzongmin, I tried and got the log file in the /host folder, but it is not the encrypted contents?

**Comment by liqinggd** [comment]
> Hi, @guzongmin, I tried and got the log file in the /host folder, but it is not the encrypted contents?

Yes, the filesystem mounted on /host is called hostfs, which is an untrusted filesystem.

If you want to write logs in to an encrypted filesystem, try to write into `/root` , and  the encrypted file will be located in `.occlum/run/mount/root` directory.

If you are using Occlum in simulation mode,  the tool `sefs-fuse` located in `/opt/occlum/build/bin` can also be used to decrypt the files created in Occlum.

**Comment by tatetian** [comment]
With the release of 0.16.0, a third option emerges: the `occlum mount` command. See [the doc](https://github.com/occlum/occlum/blob/master/docs/occlum_mount.md) here.

**Comment by guzongmin** [comment]
No more active discussion, close this issue.
