### ISSUE TITLE
server: error while loading shared libraries: libgrpc_ratls_server.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lidh15** [occlum/occlum#1211]
To reproduce:
1. pull occlum latest image from docker hub, run it on a machine with Intel SGX
2. enter `~/demos/ra_tls`, run `./download_and_prepare.sh`, `./build_and_install.sh` and `./build_occlum_instance.sh` without error
3. `./run.sh server` and it reported `server: error while loading shared libraries: libgrpc_ratls_server.so: cannot open shared object file: no such file or directory`.
4. similarly, `./run.sh client cert` and it reported `client: error while loading shared libraries: libgrpc_ratls_client.so: cannot open shared object file: no such file or directory`.

I can find following libs:
```
./grpc-src/examples/cpp/ratls/build/libhw_grpc_proto.so
./grpc-src/examples/cpp/ratls/build/libgrpc_ratls_server.so
./grpc-src/examples/cpp/ratls/build/libgrpc_ratls_client.so
./grpc-src/third_party/bloaty/tests/testdata/linux-x86/04-simple.so
./grpc-src/third_party/bloaty/tests/testdata/linux-x86_64/04-simple.so
./grpc-src/build/third_party/zlib/libz.so
./cJSON-1.7.15/build/libcjson.so
./cJSON-1.7.15/build/libcjson_utils.so
./occlum_client/initfs/lib/libc.so
./occlum_client/build/lib/libocclum-libos.so
./occlum_client/build/lib/libocclum-libos.signed.so
./occlum_client/build/lib/libocclum-pal.so
./occlum_server/initfs/lib/libc.so
./occlum_server/build/lib/libocclum-libos.so
./occlum_server/build/lib/libocclum-libos.signed.so
./occlum_server/build/lib/libocclum-pal.so
```
should I copy `./grpc-src/examples/cpp/ratls/build/libgrpc_ratls_server.so` to some place?

**Comment by qzheng527** [comment]
@lidh15 This demo works well on our side. 
From your log, somehow the two libraries were not automatically detected by `copy_bom` tool.
You can manually copy the two libraries to occlum_<server/clinet>/image/opt/occlum/glibc/lib/, then rebuild the occlum.
Also, you can refer to the demo [init_ra_flow](https://github.com/occlum/occlum/tree/master/demos/remote_attestation/init_ra_flow) for how to utilize the ra_tls library.

**Comment by qzheng527** [comment]
Please add OCCLUM_LOG_LEVEL=debug before the copy_bom command, such as:
`OCCLUM_LOG_LEVEL=debug copy_bom -f $bomfile --root image --include-dir /opt/occlum/etc/template`
I want to know what is wrong in your env.

Besides, you could manually copy all the missing libraris from `/opt/occlum/glibc/lib/` to `occlum_<server/clinet>/image/opt/occlum/glibc/lib/` then do the rebuild.

**Comment by lidh15** [comment]
The debug logs are:
```
WARNING: image is not an empty directory before running copy_bom.
[2023-03-21T00:51:10Z DEBUG copy_bom::util] the loader of ../grpc-src/examples/cpp/ratls/build/client is /lib64/ld-linux-x86-64.so.2.
[2023-03-21T00:51:10Z DEBUG copy_bom::util] occlum elf loaders: {"ld-linux-x86-64.so.2": "/opt/occlum/glibc/lib/ld-linux-x86-64.so.2", "ld-musl-x86_64.so.1": "/lib/ld-musl-x86_64.so.1"}
[2023-03-21T00:51:10Z DEBUG copy_bom::util] occlum ld_library_path envs: {"/opt/occlum/glibc/lib/ld-linux-x86-64.so.2": "/opt/occlum/glibc/lib:/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/lib64", "/lib/ld-musl-x86_64.so.1": "/lib:/opt/occlum/toolchains/gcc/x86_64-linux-musl/lib"}
[2023-03-21T00:51:10Z DEBUG copy_bom::util] default lib dirs: {"/opt/occlum/glibc/lib/ld-linux-x86-64.so.2": ["/opt/occlum/glibc/lib", "/usr/lib/x86_64-linux-gnu", "/lib/x86_64-linux-gnu", "/lib64"], "/lib/ld-musl-x86_64.so.1": ["/lib", "/opt/occlum/toolchains/gcc/x86_64-linux-musl/lib"]}
[2023-03-21T00:51:10Z DEBUG copy_bom::bom] default loader in autodep: Some(("/opt/occlum/glibc/lib/ld-linux-x86-64.so.2", "/lib64/ld-linux-x86-64.so.2"))
[2023-03-21T00:51:10Z DEBUG copy_bom::util] the loader of ../grpc-src/examples/cpp/ratls/build/client is /lib64/ld-linux-x86-64.so.2.
[2023-03-21T00:51:10Z DEBUG copy_bom::util] LD_LIBRARY_PATH='/opt/occlum/glibc/lib:/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/lib64' /opt/occlum/glibc/lib/ld-linux-x86-64.so.2 --list ../grpc-src/examples/cpp/ratls/build/client
[2023-03-21T00:51:10Z DEBUG copy_bom::util] The loader output of ../grpc-src/examples/cpp/ratls/build/client:

[2023-03-21T00:51:10Z WARN  copy_bom::util] cannot autodep for ../grpc-src/examples/cpp/ratls/build/client. stderr: ../grpc-src/examples/cpp/ratls/build/client: error while loading shared libraries: libocclum_dcap.so.0.1.0: cannot open shared object file: No such file or directory

[2023-03-21T00:51:10Z DEBUG copy_bom::util] find objects: {}
[2023-03-21T00:51:10Z DEBUG copy_bom::bom] default loader in autodep: None
[2023-03-21T00:51:10Z INFO  copy_bom::util] mkdir -p image
[2023-03-21T00:51:10Z INFO  copy_bom::util] mkdir -p image/bin
[2023-03-21T00:51:10Z INFO  copy_bom::util] mkdir -p image/usr/share/grpc
[2023-03-21T00:51:10Z INFO  copy_bom::util] mkdir -p image/lib64
[2023-03-21T00:51:10Z INFO  copy_bom::util] rsync -aL ../grpc-src/examples/cpp/ratls/build/client image/bin/client
[2023-03-21T00:51:10Z INFO  copy_bom::util] rsync -aL dynamic_config.json image/dynamic_config.json
[2023-03-21T00:51:10Z INFO  copy_bom::util] rsync -aL ../grpc-src/etc/roots.pem image/usr/share/grpc/roots.pem
[2023-03-21T00:51:10Z DEBUG copy_bom::util] copy shared object /opt/occlum/glibc/lib/ld-linux-x86-64.so.2 to image/lib64/ld-linux-x86-64.so.2.
[2023-03-21T00:51:10Z INFO  copy_bom::util] rsync -aL /opt/occlum/glibc/lib/ld-linux-x86-64.so.2 image/lib64/ld-linux-x86-64.so.2
[2023-03-21T00:51:10Z INFO  copy_bom::util] mkdir -p image/dev
[2023-03-21T00:51:10Z INFO  copy_bom::util] mkdir -p image/etc
[2023-03-21T00:51:10Z INFO  copy_bom::util] mkdir -p image/host
[2023-03-21T00:51:10Z INFO  copy_bom::util] mkdir -p image/lib
[2023-03-21T00:51:10Z INFO  copy_bom::util] mkdir -p image/opt
[2023-03-21T00:51:10Z INFO  copy_bom::util] mkdir -p image/proc
[2023-03-21T00:51:10Z INFO  copy_bom::util] mkdir -p image/root
[2023-03-21T00:51:10Z INFO  copy_bom::util] mkdir -p image/sys
[2023-03-21T00:51:10Z INFO  copy_bom::util] mkdir -p image/tmp
```
and I manually copied libdl, no it is looking for `libocclum_dcap.so.0.1.0`, which is not seen in `/opt/occlum/glibc/lib/`
```
root@joe2:~/demos/ra_tls# ls /opt/occlum/glibc/lib/
Mcrt1.o                  libBrokenLocale.so    libcrypt-2.31.so  libm.so                libnss_compat.so.2     libnss_hesiod.so.2  librt.so
Scrt1.o                  libBrokenLocale.so.1  libcrypt.a        libm.so.6              libnss_db-2.31.so      libpcprofile.so     librt.so.1
audit                    libSegFault.so        libcrypt.so       libmcheck.a            libnss_db.so           libpthread-2.31.so  libthread_db-1.0.so
crt1.o                   libanl-2.31.so        libcrypt.so.1     libmemusage.so         libnss_db.so.2         libpthread.a        libthread_db.so
crti.o                   libanl.a              libdl-2.31.so     libmvec-2.31.so        libnss_dns-2.31.so     libpthread.so       libthread_db.so.1
crtn.o                   libanl.so             libdl.a           libmvec.a              libnss_dns.so          libpthread.so.0     libutil-2.31.so
gconv                    libanl.so.1           libdl.so          libmvec.so             libnss_dns.so.2        libresolv-2.31.so   libutil.a
gcrt1.o                  libc-2.31.so          libdl.so.2        libmvec.so.1           libnss_files-2.31.so   libresolv.a         libutil.so
ld-2.31.so               libc.a                libg.a            libnsl-2.31.so         libnss_files.so        libresolv.so        libutil.so.1
ld-linux-x86-64.so.2     libc.so               libm-2.31.a       libnsl.so.1            libnss_files.so.2      libresolv.so.2
libBrokenLocale-2.31.so  libc.so.6             libm-2.31.so      libnss_compat-2.31.so  libnss_hesiod-2.31.so  librt-2.31.so
libBrokenLocale.a        libc_nonshared.a      libm.a            libnss_compat.so       libnss_hesiod.so       librt.a
```

**Comment by lidh15** [comment]
Okay, I found the link shared in wechat group https://occlum.readthedocs.io/en/latest/remote_attestation.html and libocclum_dcap.so.0.1.0 is at `/opt/occlum/toolchains/dcap_lib/glibc/`

**Comment by lidh15** [comment]
after all the libs were found, when I ran the server, it reported:
```
root@joe2:~/demos/ra_tls# ./run.sh server
~/demos/ra_tls/occlum_server ~/demos/ra_tls
[get_platform_quote_cert_data ../qe_logic.cpp:378] Error returned from the p_sgx_get_quote_config API. 0xe019
thread '<unnamed>' panicked at 'IOCTRL IOCTL_GET_DCAP_QUOTE_SIZE failed', src/occlum_dcap.rs:70:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```
and the same error was reported by the client.

**Comment by qzheng527** [comment]
@lidh15 0xe019 means network issue. Please make sure your env have accessible PCCS service, and also set the correct PCCS URL in the `sgx_default_qcnl.conf`. 
BTW， we will move the ra_tls to the prebuilt libraries in Occlum Docker image in near future. So I recommend you try the `[init_ra_flow](https://github.com/occlum/occlum/tree/master/demos/remote_attestation/init_ra_flow)` demo directly which utilizes the ra_tls libraries.

**Comment by lidh15** [comment]
the default PCCS URL in `sgx_default_qcnl.conf` is errorless, I followed intel SGX document:
> Run the following command to make sure the PCCS service is working correctly (assume the service 
> is running on localhost with an insecure certificate):
> $ curl -k -G "https://localhost:8081/sgx/certification/v3/rootcacrl"
> The root CA CRL should be retrieved successfully.

the results were as expected. 
And I tried to set false to `use_secure_cert` in `sgx_default_qcnl.conf`, it now reports a different code:
```
~/demos/ra_tls/occlum_server ~/demos/ra_tls
[get_platform_quote_cert_data ../qe_logic.cpp:378] Error returned from the p_sgx_get_quote_config API. 0xe011
thread '<unnamed>' panicked at 'IOCTRL IOCTL_GET_DCAP_QUOTE_SIZE failed', src/occlum_dcap.rs:70:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```

**Comment by qzheng527** [comment]
@lidh15 Where is your PCCS service set up? 0xe011 means "The platform library doesn't have any platfrom cert data".
If you set up the PCCS service by yourself, please follow [intel guide](https://www.intel.com/content/www/us/en/developer/articles/guide/intel-software-guard-extensions-data-center-attestation-primitives-quick-install-guide.html) strictly.

BTW, you don't need ra_tls demo to try PCCS. You can just run demo [dcap](https://github.com/occlum/occlum/tree/master/demos/remote_attestation/dcap) to see if PCCS works well.

**Comment by qzheng527** [comment]
You can try this prebuilt PCCS docker from https://github.com/intel-analytics/BigDL/tree/main/ppml/services/pccs/docker.
Also if you have SGX ECS in Aliyun, you could directly use the PCCS service provided by Aliyun.
Details please refer to https://help.aliyun.com/document_detail/208095.html

**Comment by lidh15** [comment]
I finally found a valid PCCS, now it said: 
```
~/demos/ra_tls/occlum_server ~/demos/ra_tls
thread '<unnamed>' panicked at 'explicit panic', src/fs/rootfs.rs:28:13
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
             at library/core/src/panicking.rs:142
   2: core::panicking::panic
             at library/core/src/panicking.rs:48
   3: spin::once::Once<T>::call_once
   4: occlum_libos_core_rs::fs::fs_view::FsView::lookup_inode
   5: occlum_libos_core_rs::fs::fs_view::FsView::open_file
   6: occlum_libos_core_rs::util::host_file_util::write_host_file
   7: occlum_ecall_init
   8: sgx_occlum_ecall_init
             at /root/occlum/build/internal/src/libos/src/Enclave_t.c:1328
   9: sgx_occlum_ecall_init
             at /root/occlum/build/internal/src/libos/src/Enclave_t.c:1123
  10: do_ecall
  11: enter_enclave
  12: <unknown>
  13: <unknown>
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
/opt/occlum/build/bin/occlum: line 354:   104 Illegal instruction     (core dumped) RUST_BACKTRACE=1 "$instance_dir/build/bin/occlum-run" "$@"
```
why is there illegal instructions? I build and run it with the same machine and the same CPU all the time.

**Comment by lidh15** [comment]
Okay, I don't know what happened but after rerunning build_occlum_instance the illegal instruction disappeared.
Now the error is
```
ret = -1
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "IOCTRL IOCTL_VER_DCAP_QUOTE failed"', src/lib.rs:84:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```
The host machine is using sbx license, what should I do to fix `IOCTRL IOCTL_VER_DCAP_QUOTE failed`

**Comment by qzheng527** [comment]
@lidh15 Please run demo [dcap](https://github.com/occlum/occlum/tree/master/demos/remote_attestation/dcap) first to check if everything works fine.

**Comment by lidh15** [comment]
> @lidh15 Please run demo [dcap](https://github.com/occlum/occlum/tree/master/demos/remote_attestation/dcap) first to check if everything works fine.

The same error
![mmexport1679467286628.jpg](https://user-images.githubusercontent.com/14806954/226822726-0fd97006-cb60-4e00-8b92-204392b28210.jpg)

**Comment by qzheng527** [comment]
@lidh15 What is your kernel version? What is the Occlum container verson?
Also, please try intel SGX DCAP QuoteVerificationSample directly in the Occlum container.
https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/DCAP_1.14/SampleCode/QuoteVerificationSample

You can directly do the build & run as below.
![image](https://user-images.githubusercontent.com/23373702/226825459-c1860c7a-c132-4725-ac6d-8d5caba251f8.png)

**Comment by lidh15** [comment]
That worked well:
```
root@joe2:/workspace/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample# SGX_AESM_ADDR=1 ./app

Step1: Call sgx_qe_get_target_info:succeed!
Step2: Call create_app_report:succeed!
Step3: Call sgx_qe_get_quote_size:succeed!
Step4: Call sgx_qe_get_quote:succeed!cert_key_type = 0x5
```
Occlum container is occlum/occlum:latest-ubuntu20.04
uname -r said `5.15.0-spr.bkc.pc.16.1.23.x86_64`

**Comment by qzheng527** [comment]
> That worked well:
> 
> ```
> root@joe2:/workspace/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample# SGX_AESM_ADDR=1 ./app
> 
> Step1: Call sgx_qe_get_target_info:succeed!
> Step2: Call create_app_report:succeed!
> Step3: Call sgx_qe_get_quote_size:succeed!
> Step4: Call sgx_qe_get_quote:succeed!cert_key_type = 0x5
> ```
> 
> Occlum container is occlum/occlum:latest-ubuntu20.04 uname -r said `5.15.0-spr.bkc.pc.16.1.23.x86_64`

No, you don't need `SGX_AESM_ADDR=1`. Just follow the guide I showed above step by step, including QuoteGenaration and QuoteVerification demos.

**Comment by qzheng527** [comment]
@lidh15 So weird. You don't have `/usr/lib/x86_64-linux-gnu/libdcap_quoteprov.so.1` in your Occlum container?
I feel there is something wrong in your Occlum docker image.
Can you try `docker pull occlum/occlum:0.29.5-ubuntu20.04` ?

**Comment by lidh15** [comment]
No, we have that in the container:
```
-rw-r--r-- 1 root root 1716032 Jun  7  2022 /usr/lib/x86_64-linux-gnu/libdcap_quoteprov.so.1.13.100.3
lrwxrwxrwx 1 root root 31 Jun  7  2022 /usr/lib/x86_64-linux-gnu/libdcap_quoteprov.so.1 -> libdcap_quoteprov.so.1.13.100.3
```
I don't know why it cannot be found.

**Comment by lidh15** [comment]
> Can you try docker pull occlum/occlum:0.29.5-ubuntu20.04 ?

It is exactly the same image

**Comment by lidh15** [comment]
Seems that we failed to run even the official demo, I always support Ali and Ant but this time I have to turn to a substitution of Occlum.
