### ISSUE TITLE
[BUG] demo linux-ltp

### ISSUE THREAD

**Issue by Antone077** [occlum/occlum#1226]
When I run linux-ltp demo, it shows errors below:

[ERROR] occlum-pal: Failed to create enclave with error code 0x1: Unexpected error occurred. (line 152, file src/pal_enclave.c)

steps: 

      cd demo/linux-ltp

      ./dl_and_build_ltp.sh

      ./prepare_ltp.sh

      cd ltp_instance

      occlum run /opt/ltp/run-ltp.sh -f syscall-occlum -s getdents

The linux-ltp can run in occlum-0.29.3, but i test it in 0.29.4 & 0.29.5. It will show this error.

**Comment by Antone077** [comment]
Another question, when I run LTP, some syscalls will return me some Segmentation faults. It shows log below:

`/opt/ltp/run-ltp.sh: line 38:    11 Segmentation fault      /opt/ltp/testcases/bin/getdents01`

 I want to analyze them. How can I locate them?

**Comment by qzheng527** [comment]
> When I run linux-ltp demo, it shows errors below:
> 
> [ERROR] occlum-pal: Failed to create enclave with error code 0x1: Unexpected error occurred. (line 152, file src/pal_enclave.c)
> 
> steps:
> 
> ```
>   cd demo/linux-ltp
> 
>   ./dl_and_build_ltp.sh
> 
>   ./prepare_ltp.sh
> 
>   cd ltp_instance
> 
>   occlum run /opt/ltp/run-ltp.sh -f syscall-occlum -s getdents
> ```
> 
> The linux-ltp can run in occlum-0.29.3, but i test it in 0.29.4 & 0.29.5. It will show this error.

@Antone077 We will see if we can reproduce it in our side.
Also, if you want to debug, you can set the log level such as :
```
OCCLUM_LOG_LEVEL=trace occlum run xxx
```
