### ISSUE TITLE
Occlum hello_c demo on Azure confidential computing VM 

### ISSUE THREAD

**Issue by DNJha** [occlum/occlum#1228]
I'm trying to run Occlum on Azure Confidential Computing VM (Ubuntu 20.04). 

The Intel SGX sample codes are working fine but the Occlum examples are not working (in the hardware mode).

I don't want to use EKS to execute Occlum so I'm using a docker container to run the Occlum using `sudo docker run --rm -it --network host --device /dev/sgx/enclave --device /dev/sgx/provision occlum/occlum:0.29.3-ubuntu20.04 /bin/bash` and then following the README.md from the demos directory. 

I'm getting the error message `[ERROR] occlum-pal: Failed to create enclave with error code 0x1: Unexpected error occurred. (line 152, file src/pal_enclave.c)`. 

I'm not sure what I'm doing wrong. Any help is much appreciated.

**Comment by qzheng527** [comment]
@DNJha 
For the error message, probably it was due to the unsuccessful SGX device mapping.
Did you run the Intel SGX samples successfully also in the Occlum container?

**Comment by DNJha** [comment]
I'm able to run the Intel SGX sample code (after mapping the volume`-v /opt/intel/:/opt/intel/`) inside the Occlum container but still unable to execute the hello_c demo with the previous error. 

I'm not sure which else component to map to the Occlum container.

**Comment by qzheng527** [comment]
@DNJha Could you please try the intel sgx sdk samples installed in the container (path: /opt/intel/sgxsdk/SampleCode) directly? Also, please run the command `ls -al /dev/sgx*` in your VM  env and container env.
You could follow the guide on https://occlum.readthedocs.io/en/latest/quickstart.html#start-the-occlum-dev-container.
BTW, what is the kernel version in your VM?

**Comment by DNJha** [comment]
The `SampleEncleave` example works fine while the `RemoteAttestation` requires the `libsample_libcrypto.so` path to be specified otherwise gives me the error
```
# ./app 
./app: error while loading shared libraries: libsample_libcrypto.so: cannot open shared object file: No such file or directory

```

In VM
```
# ls -al /dev/sgx*
crw-rw-rw- 1 root root    10, 125 Apr  6 09:00 /dev/sgx_enclave
crw-rw---- 1 root sgx_prv 10, 126 Apr  6 09:00 /dev/sgx_provision

/dev/sgx:
total 0
drwxr-xr-x  2 root root   80 Apr  6 10:16 .
drwxr-xr-x 20 root root 4040 Apr  6 09:00 ..
lrwxrwxrwx  1 root root   14 Apr  6 10:16 enclave -> ../sgx_enclave
lrwxrwxrwx  1 root root   16 Apr  6 10:16 provision -> ../sgx_provision
```

In Occlum container
```
# ls -al /dev/sgx*
total 0
drwxr-xr-x 2 root root      80 Apr  6 10:17 .
drwxr-xr-x 6 root root     380 Apr  6 10:17 ..
crw-rw-rw- 1 root root 10, 125 Apr  6 10:17 enclave
crw-rw---- 1 root 1001 10, 126 Apr  6 10:17 provision
```

The kernel version of the vm
```
# uname -a
Linux DevkiConfComp1 5.15.0-1035-azure #42~20.04.1-Ubuntu SMP Wed Mar 1 19:17:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

While running the hello_c example, I'm still getting the same error 
```
# occlum run /bin/hello_world
[ERROR] occlum-pal: Failed to create enclave with error code 0x1: Unexpected error occurred. (line 152, file src/pal_enclave.c)
```

**Comment by DNJha** [comment]
Hi @qzheng527, just checking if you can regenerate the same issue with your end or not as I'm still struggling with this. I'm able to run the examples in the Simulation mode but not in the hardware mode on Azure Confidential Computing VM.

**Comment by qzheng527** [comment]
@DNJha We haven't met such issue before and no partners/customers in Azure complained about this.
I will doubel check with our partners.

**Comment by qzheng527** [comment]
@DNJha Just checked again with one of our partner, they haven't had such issue.
Here is the env info they have right now.
```
Standard DC8ds v3 (8 vcpus, 64 GiB memory)
Location: East US 2
OS: Ubuntu 20.04 LTS gen2
Kernel: Linux xxx 5.15.0-1033-azure
```

**Comment by DNJha** [comment]
The problem was in the OS kernel, it does not allow to load SGX properly. In a new Azure VM, the examples are running fine.

Thank you.
