### ISSUE TITLE
Question about the device /dev/sgx in remote attestation demo

### ISSUE THREAD

**Issue by xyzhao2018** [occlum/occlum#125]
In remote attestation demo, the quote is get from device, /dev/sgx, directly. 
Does this device is the real sgx device on HW? 
Why it didn't call sgx API to get quote? 

Thanks.

**Comment by duanbing** [comment]
Note that '/dev/sgx' in the libos is a SGX device to provide some SGX
functions,  (src/libos/src/fs/dev_fs/dev_sgx/mod.rs), which redirects the
request to an agent, namely SgxAttestationAgent (./src/libos/src/util/sgx/
sgx_attestation_agent.rs),  the SgxAttestationAgent will call the SGX API.

xyzhao2018 <notifications@github.com> 于2020年8月25日周二 上午10:23写道：

**Comment by tatetian** [comment]
Agree with @duanbing . `/dev/sgx` is a virtual device that exposes Intel SGX SDK's APIs through ioctl. So it does call Intel SGX SDK's APIs eventually.
