### ISSUE TITLE
Application executing in HW mode failing (Seccomp error)

### ISSUE THREAD

**Issue by DNJha** [occlum/occlum#1264]
I'm trying to run [swtpm](https://github.com/stefanberger/swtpm) in a socket mode inside the Azure confidential computing environment using Occlum. I'm running Occlum using a docker container and added the swtpm installation and run command following the demo examples given. 

The `install_swtpm.sh`:

```
#!/bin/bash

set -e
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}"  )" >/dev/null 2>&1 && pwd )"

# Prepare environment
DEPS="gcc-multilib fuse automake autoconf libtool make gcc libc-dev libssl-dev libc6-dev libgmp-dev libnspr4-dev libnss3-dev pkg-config libfuse-dev libglib2.0-dev expect libtasn1-dev socat tpm-tools python3-twisted gnutls-dev gnutls-bin libjson-glib-dev libseccomp-dev gawk net-tools"

apt-get update
apt-get install -y ${DEPS}

# 1. Init occlum workspace
[ -d occlum_instance ] || occlum new occlum_instance

# 2. Install libtpms and swtpm to specified position
[ -d $script_dir/libtpms ] || mkdir $script_dir/libtpms && 
	cd $script_dir/libtpms && 
	wget https://github.com/stefanberger/libtpms/archive/refs/heads/master.tar.gz && 
	tar -xf master.tar.gz -C . --strip-components 1 &&
	cd $script_dir/libtpms &&
	./autogen.sh --with-openssl --prefix=/usr --with-tpm2 &&
	make -j$(nproc) &&
	make all install &&
	rm master.tar.gz &&
	cd ..

[ -d $script_dir/swtpm ] || mkdir $script_dir/swtpm && cd $script_dir/swtpm && wget https://github.com/stefanberger/swtpm/archive/refs/heads/master.tar.gz && tar -xf master.tar.gz -C . --strip-components 1 &&
       	./autogen.sh &&
	./configure --prefix=/usr &&
	make &&
	make check &&
	make install && 
	rm master.tar.gz
```

The `swtpm.yaml`:

```
includes:
  - base.yaml
# copy directories 
targets:
  - target: /bin
    copy:
      - dirs:
         - /usr/bin/
         - /usr/lib/swtpm/
         - ../libtpms/src/.libs/
         - /usr/lib/x86_64-linux-gnu/

```
 and `run_swtpm.sh` is:

```
#!/bin/bash
set -e

BLUE='\033[1;34m'
NC='\033[0m'

cd occlum_instance && rm -rf image
copy_bom -f ../swtpm.yaml --root image --include-dir /opt/occlum/etc/template

new_json="$(jq '.resource_limits.user_space_size = "800MB" |
        .resource_limits.kernel_space_heap_size = "600MB"|
        .env.default += ["LD_LIBRARY_PATH=/bin/:/opt/occlum/glibc/lib/"] ' Occlum.json)" && \
echo "${new_json}" > Occlum.json

# Build Occlum
echo -e "${BLUE}Occlum build swtpm${NC}"
occlum build

# Run the python demo
echo -e "${BLUE}Occlum start swtpm${NC}"
[ -d /bin/myvtpm ] ||  mkdir /bin/myvtpm

occlum run /bin/swtpm socket --tpmstate dir=/bin/myvtpm --tpm2 --ctrl type=tcp,port=2322,bindaddr=0.0.0.0 --server type=tcp,port=2321,bindaddr=0.0.0.0 --flags not-need-init
```

It is working fine in the `SGX_MODE=SIM` but fails in the `HW` mode, I checked the trace file and it seems the failure is because of the `Seccomp `syscall or at least I think so. 

I also try to run the `swtpm` with the `seccomp` flag disabled (`occlum run /bin/swtpm socket --tpmstate dir=/bin/myvtpm --tpm2 --ctrl type=tcp,port=2322,bindaddr=0.0.0.0 --server type=tcp,port=2321,bindaddr=0.0.0.0 --flags not-need-init --seccomp action=none`), but it get in a continuous loop (only when it's executing in HW mode). 

I'm not sure what I'm doing wrong. Any help is appreciated.

**Comment by jessehui** [comment]
Hi @DNJha , thanks for using Occlum. The `seccomp` syscall is not supported in Occlum currently. I am not sure why it doesn't throw errors in SIM mode. One possible reason is that it is directly called with `syscall` instruction. In this case, the syscall is not handled by Occlum under SIM mode.

I would recommend to disable this feature if possible. Please make sure the way to disable `seccomp` is working. And if other error occurs, you can send us the complete log file by using `OCCLUM_LOG_LEVEL=trace occlum run /xxx`.

**Comment by DNJha** [comment]
Thanks @jessehui for your reply. I tested `swtpm` with `seccomp` disabled (`--seccomp action=none`) in non-SGX, SGX=SIM and SGX=HW environments, in both non-SGX and SGX=SIM environments, it's working fine. In the hardware SGX environment, it goes in an infinite loop, please find the log file attached.

[logs.docx](https://github.com/occlum/occlum/files/11450002/logs.docx)

As you can see from the log file, the below-given exception is continuously repeating without stopping.

```
[2023-05-11T08:09:28.997Z][TRACE][T2][#303][HandleException] Syscall { num = HandleException, info = 0x7f144297aed0, fpregs = 0x7f144297ac70, context = 0xb1c80eaf5c79caa5 }
[2023-05-11T08:09:28.997Z][DEBUG][T2][#303][HandleException] handle SYSCALL exception
[2023-05-11T08:09:28.998Z][TRACE][T2][#304][····Poll] Syscall { num = Poll, fds = 0x7f1577972a00, nfds = 5, timeout = -1 }
[2023-05-11T08:09:28.998Z][DEBUG][T2][#304][····Poll] poll: poll_fds: [PollFd { fd: 4294967295, events: IN | ERR | HUP, revents: Cell { value: (empty) } }, PollFd { fd: 6, events: IN | ERR | HUP, revents: Cell { value: (empty) } }, PollFd { fd: 3, events: IN | ERR | HUP, revents: Cell { value: (empty) } }, PollFd { fd: 4294967295, events: IN | ERR | HUP, revents: Cell { value: (empty) } }, PollFd { fd: 4, events: IN | ERR | HUP, revents: Cell { value: (empty) } }], timeout: None
[2023-05-11T08:09:28.998Z][TRACE][T2][#304][····Poll] Retval = 0x2
```

I'm not sure why this is happening.

**Comment by jessehui** [comment]
I took a look at the log file and find something weird. The poll syscall doesn't seem to poll the valid file which has the fd number `4294967295` which is `2^32 - 1`. As far as I know, this file number is used in mmap syscall when there is no mmap file and will set the fd to `-1`. I am not sure why this is polled but it looks like the parameters are set by the userspace.

You can use the `strace` to print the log running on Linux and compare the log in Occlum and see if we can find anything.

**Comment by DNJha** [comment]
Thanks @jessehui.

Please find the trace output for `swtpm` executing in the Ubuntu 20 environment. I deactivated the `seccomp` there as well. 

[swtpm log.docx](https://github.com/occlum/occlum/files/11461818/swtpm.log.docx)

I'm not able to find any big difference other than `/bin/myvtpm/tpm2-00.permall` which is saving the swtpm state. Please let me know if you can find the reason for the failure.

**Comment by jessehui** [comment]
It seems the return value of `poll` is different. I will try to reproduce this in my environment and see how to fix it. By the way, which Occlum version are you using?

**Comment by jessehui** [comment]
@DNJha Please apply the patch of #1271 and reinstall Occlum to see if it works. I have tested it with your script and the behavior is the same with or without Occlum. Thank you.

**Comment by jessehui** [comment]
Is there any particular reason you choose this version? If not, you can use the latest 0.29.5 image: `occlum/occlum:0.29.5-ubuntu20.04`. 
(1) Create a container with this image, then git clone this branch: https://github.com/jessehui/occlum/tree/fix_poll. 
(2) Install Occlum. The detailed installation steps can be found here: https://github.com/occlum/occlum#how-to-build

**Comment by DNJha** [comment]
Hi @jessehui, I appreciate your help very much.

I added the patch and tested it multiple times. Sorry, but the `swtpm` is still not accessible. Now it does not give any message while waiting as previously, but it's still waiting. From`tss` side when I'm trying to connect, it waits indefinitely as before. 

Please find the trace file for in `SGX=SIM mode` where  `swtpm` is available and is working fine. Also, find the trace file for `HW` attached.
[SIM_SGX_trace.docx](https://github.com/occlum/occlum/files/11487332/SIM_SGX_trace.docx)
[HW_SGX_trace.docx](https://github.com/occlum/occlum/files/11487333/HW_SGX_trace.docx)

**Comment by jessehui** [comment]
@DNJha Thank you for your verification. I did find a new bug introduced by my previous fix. Please try out my new fix with the same branch: https://github.com/jessehui/occlum/tree/fix_poll. Install Occlum as listed above. Looking forward to your result.

**Comment by DNJha** [comment]
@jessehui, thanks for the update, but it's still not working. Now I started getting some log messages again while waiting in the loop. I've attached the trace log.
[occlum_logs.docx](https://github.com/occlum/occlum/files/11505857/occlum_logs.docx)

**Comment by DNJha** [comment]
@jessehui  Thank you for all your help. You were right, I missed the new branch.

Tada, `swtpm` is now working fine with the new branch, allowing me to communicate from outside.

Thank you very much.

**Comment by jessehui** [comment]
This is wonderful! Thank you for your detailed instruction and script. If you have time, could you please raise a PR to make `swtpm` an officially supported and verified demo of Occlum project? You can refer to this #332 PR. Please feel free to ask anything.

**Comment by DNJha** [comment]
Sure, I'll do that. I will also add the basic documentation on `TSS` so that the working of `swtpm` can be validated.
