### ISSUE TITLE
[BUG] poll syscall disbehave in the Occlum

### ISSUE THREAD

**Issue by fengyuanyu1** [occlum/occlum#1269]
Hello, @jessehui @volcano0dr I mentioned a misbehavior when using Occlum.

# Describe the bug

When I use the poll with several FDs in the Occlum distance. It is polling all the time without handling the signals.

# To reproduce
1. Run a Occlum docker (version 0.29.05)
2. client program
```C
// server.c
#include <sys/types.h>
#include <sys/socket.h>
#include <stdio.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <string.h>
#include <sys/time.h>
#include <poll.h>

#define PORT 9990
#define SIZE 1024
#define MAX_CLIENTS 2

int creat_socket()
{
    int server_socket = socket(AF_INET, SOCK_STREAM, 0);
    struct sockaddr_in addr;

    addr.sin_family = AF_INET;
    addr.sin_port = htons(PORT);
    addr.sin_addr.s_addr = htonl(INADDR_ANY);

    int bindResult = bind(server_socket, (struct sockaddr *)&addr, sizeof(addr));
    if (bindResult == -1) { perror("bindResult");}
    int listenResult = listen(server_socket, 5); 
    if (listenResult == -1) { perror("listenResult");}
    printf("server start\n");
    return server_socket;
}

int wait_client(int server_socket)
{
    struct pollfd pollfds[MAX_CLIENTS];
    pollfds[0].fd = server_socket;
    pollfds[0].events = POLLIN | POLLPRI;
    while (1)
    {
        int pollResult = poll(pollfds, MAX_CLIENTS, -1);
        if (pollResult < 0) continue;
        if (pollfds[0].revents & POLLIN)
        {
            printf("POLLIN\n");
            struct sockaddr_in cliaddr;
            int addrlen = sizeof(cliaddr);
            int client_socket = accept(server_socket, (struct sockaddr *)&cliaddr, &addrlen);
            printf("accept success %s\n", inet_ntoa(cliaddr.sin_addr));
        }
    }
}

int main()
{
    int server_socket = creat_socket();
    int client_socket = wait_client(server_socket);
    printf("server end\n");
    close(client_socket);
    close(server_socket);
    return 0;
}
// client.c
#include <sys/socket.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <arpa/inet.h>
#include <stdlib.h>

#define PORT 9990
#define SIZE 1024

int main(int argc, char *argv[])
{
    int client_socket = socket(AF_INET, SOCK_STREAM, 0);
    struct sockaddr_in addr;
    addr.sin_family = AF_INET;
    addr.sin_port = htons(9990);
    addr.sin_addr.s_addr = htonl(INADDR_ANY);
    inet_aton("127.0.0.1", &(addr.sin_addr));

    int server_socket = connect(client_socket, (struct sockaddr *)&addr, sizeof(addr)); //连接服务器

    printf("Connect result ==> %d\n", server_socket);
    if (server_socket < 0) { perror("Connect result"); exit(1); }
    char buf[SIZE] = {0};
    while (1)
    {
        printf("Send to server：");
        scanf("%s", buf);
        write(client_socket, buf, strlen(buf));
        printf("\n");
        if (strncmp(buf, "end", 3) == 0)
        {
            break;
        }
    }
    close(server_socket);

    return 0;
}
```
3. build them and run server in the Occlum
```shell
# client.c and server.c in the Occlum directory
gcc -o client client.c
gcc -o server server.c
cp server image/bin
occlum build
OCCLUM_LOG_LEVEL=trace occlum run /bin/server
```
4. run the client 
```
./client
``` 

# Expected behavior
The server side print the POLLIN.
But when I set the MAX_CLIENTS as the value which is greater than one.
It traps the loops in the Polling.
# Logs
If applicable, add logs to help explain your problem.
[log.txt](https://github.com/occlum/occlum/files/11466854/log.txt)

# Environment

- HW: SGX
- OS:  Ubuntu20.04 in docker
- Occlum version: 0.29.05

# Additional context

# Possible solution/Implementation
Not obligatory, but suggest a fix/reason for the bug.

**Comment by jessehui** [comment]
Hi @fengyuanyu1 . Thanks for using Occlum. I try to understand your description and reproduce with your code. However, it seems the results for running `server` __with__ and __without__ Occlum are the same (client is running without Occlum in both cases).
![截屏2023-05-15 11 25 44](https://github.com/occlum/occlum/assets/13930406/094f3fab-c427-4cdc-aa5e-11cb730b8c65)
![截屏2023-05-15 11 25 55](https://github.com/occlum/occlum/assets/13930406/e37257c4-3ec5-4f4a-aa9c-a7d6b77bf424)

Please help verify if it is the same on your side.

**Comment by fengyuanyu1** [comment]
@jessehui Sorry for late reply cause I'm hit by COVID-19. When I set the MAX_CLIENTS  in `server.c` as 2, it behaves well. But when the value of MAX_CLIENTS is 3 or greater. It will disbehave.

**Comment by jessehui** [comment]
Take a closer look at your code, it looks like the arguments for `poll` is not handled well.  Please check the man page of poll.
In your code:
``` c
struct pollfd pollfds[MAX_CLIENTS];
    pollfds[0].fd = server_socket;
    pollfds[0].events = POLLIN | POLLPRI;
    while (1)
    {
        int pollResult = poll(pollfds, MAX_CLIENTS, -1);
```

The pollfds[1] and pollfds[2] are not initialized when using.

**Comment by fengyuanyu1** [comment]
Thanks for your reply. But I think the uninitialized  arguments is not the key of this problem. I try to fill the arguments for poll, It has same problem. In my opinion, it should deal the `if (pollfds[0].revents & POLLIN)` successfully as the no-Occlum environment. 
Similarly, when I ports the [swtpm](https://github.com/stefanberger/swtpm) into the Occlum, the phenomenon I described above happens again at [this line](https://github.com/stefanberger/swtpm/blob/master/src/swtpm/mainloop.c#L226). It loops consistently without entering the corresponding branch for the further handling. Its code has filled all the arguments for the poll, so I think it's not the arguments' issue. 
Please check again. Thanks a lot! 🥺

**Comment by fengyuanyu1** [comment]
I port the swtpm into Occlum successfully. Thanks!
