### ISSUE TITLE
[BUG] docker occlum/occlum:0.27.3-ubuntu20.04,hello_c,SGX_MODE=SIM occlum build error

### ISSUE THREAD

**Issue by pmpleader** [occlum/occlum#1285]
# Describe the bug
![image](https://github.com/occlum/occlum/assets/24772933/b2f8d0b8-e5f3-4399-82cc-4556901a6c48)

# To reproduce
1. cd /root/demos/hello_c ; occlum-gcc -o hello_world hello_world.c
2. mkdir occlum_instance && cd occlum_instance
3. occlum init
4. cp ../hello_world image/bin/
5. SGX_MODE=SIM occlum build

# Expected behavior
SGX_MODE=SIM occlum build  success;

# Environment
- HW: [no] 
- OS: [Ubuntu20.04]
- Occlum version: [0.27.3]

**Comment by jessehui** [comment]
Thanks for using Occlum. I never encounter such an error. What is the platform you are using to run SIM mode? Is it x86? If it is, then it must be a really old machine. If it is not x86, then we never did this kind of test. And it is possible that there are instructions that your platform doesn't support. 

As far as I know, SGX SIM mode is only verified for Intel CPUs with/without SGX hardware. Not for other ISAs.

**Comment by pmpleader** [comment]
info:

System:    Host: secret-ray-7 Kernel: 5.4.0-149-generic x86_64 bits: 64 Console: tty 0 
           Distro: Ubuntu 20.04.6 LTS (Focal Fossa) 
Machine:   Type: Kvm System: Red Hat product: KVM v: RHEL 7.0.0 PC (i440FX + PIIX, 1996) serial: N/A 
           Mobo: N/A model: N/A serial: N/A BIOS: Seabios v: 0.5.1 date: 01/01/2011 
CPU:       Topology: 16x Single Core model: Intel Core (Broadwell IBRS) bits: 64 type: SMP L2 cache: 64.0 MiB 
           Speed: 2095 MHz min/max: N/A Core speeds (MHz): 1: 2095 2: 2095 3: 2095 4: 2095 5: 2095 6: 2095 7: 2095 8: 2095 
           9: 2095 10: 2095 11: 2095 12: 2095 13: 2095 14: 2095 15: 2095 16: 2095 
Graphics:  Device-1: Cirrus Logic GD 5446 driver: cirrus v: kernel 
           Display: tty server: N/A driver: cirrus tty: 176x49 
           Message: Unable to show advanced data. Required tool glxinfo missing.

**Comment by pmpleader** [comment]
system：Ubuntu 20.04.6 LTS (Focal Fossa)
CPU model: Intel Core (Broadwell IBRS) 
在docker里面在模拟器模式下运行出错，是不是和CPU型号有关系呢？我在另外一台CPU model: Intel Xeon (Icelake)的服务器上运行模拟器模式成功，但真实sgx（去掉SGX_MODE=SIM）环境失败；所以在模拟器环境下测试是不是也需要cpu支持相应的指令，只是bios里面不开启的话，无法使用sgx里面的内存呢？谢谢；
![image](https://github.com/occlum/occlum/assets/24772933/d87d3676-fce2-461b-940d-90eed59baa3f)

**Comment by jessehui** [comment]
For SIM mode failure, Broadwell is a really old type. We haven't done any tests with Broadwell. If you are running SIM mode, it is OK that your platform doesn't have SGX support. Thus I would assume the error is due to unsupported instructions (Not SGX instructions, but others like AVX or AVX2 or something else).

For HW mode failure on Icelake, please make sure that the platform does support SGX and it is enabled correctly.

**Comment by pmpleader** [comment]
thanks.
