### ISSUE TITLE
Does occlum support Virtual Memory?

### ISSUE THREAD

**Issue by yingjun-wu** [occlum/occlum#1330]
When I use [wasmi](https://github.com/paritytech/wasmi) inside occlum, the application often terminates unexpectedly due to out of memory. By analyzing the reason, it is found that wasmi uses [region](https://github.com/darfink/region-rs) to create `virtual memory` when `create_runtime`. However, in the occlum environment, the memory created by the `region` seems to be physical memory. Is there any way to solve this problem?

**Comment by jessehui** [comment]
Current Occlum userspace will commit the physical memory when Occlum initializes. All allocated virtual memory is mapped with physical memory no matter if the application touches it.

**Comment by yingjun-wu** [comment]
> Current Occlum userspace will commit the physical memory when Occlum initializes. All allocated virtual memory is mapped with physical memory no matter if the application touches it.

Thanks for your reply. 
Okay, I got it. Do you have plans to change the way virtual memory is handled now? Or is there any difficulty in virtual memory?

**Comment by jessehui** [comment]
> Okay, I got it. Do you have plans to change the way virtual memory is handled now? Or is there any difficulty in virtual memory?

Yes. With EDMM (enclave dynamic memory management) in the future, Occlum will handle the memory more like virtual memory. The application only needs to pay for the memory that it really uses (touches). Allocating/deallocating a big range of memory will be easier to succeed. This feature is currently under active development and will be released soon.

**Comment by yingjun-wu** [comment]
Okay，and with the support of EDMM, is it possible to allocate more memory than the actual EPC (or available physical memory) size allows?

**Comment by jessehui** [comment]
With EDMM, it is possible to allocate more virtual memory than the actual EPC.

**Comment by yingjun-wu** [comment]
Ok, I got it. Thanks for your reply again.
