### ISSUE TITLE
Add installable packages for Ubuntu 22.04

### ISSUE THREAD

**Issue by mythi** [occlum/occlum#1361]
Is it possible to get installable packages for `jammy` too?

```
Step 6/20 : RUN echo "deb [arch=amd64 signed-by=/usr/share/keyrings/occlum.gpg] https://occlum.io/occlum-package-repos/debian jammy main" | tee -a /etc/apt/sources.list.d/occlum.list  && wget -qO - https://occlum.io/occlum-package-repos/debian/public.key | gpg --dearmor --output /usr/share/keyrings/occlum.gpg  && apt-get update
 ---> Running in 8bc28a1a0663
deb [arch=amd64 signed-by=/usr/share/keyrings/occlum.gpg] https://occlum.io/occlum-package-repos/debian jammy main
Hit:1 https://download.01.org/intel-sgx/sgx_repo/ubuntu jammy InRelease
Ign:2 https://occlum.io/occlum-package-repos/debian jammy InRelease
Err:3 https://occlum.io/occlum-package-repos/debian jammy Release
  404  Not Found [IP: 185.199.111.153 443]
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists...
E: The repository 'https://occlum.io/occlum-package-repos/debian jammy Release' does not have a Release file.
The command '/bin/sh -c echo "deb [arch=amd64 signed-by=/usr/share/keyrings/occlum.gpg] https://occlum.io/occlum-package-repos/debian jammy main" | tee -a /etc/apt/sources.list.d/occlum.list  && wget -qO - https://occlum.io/occlum-package-repos/debian/public.key | gpg --dearmor --output /usr/share/keyrings/occlum.gpg  && apt-get update' returned a non-zero code: 100
```

**Comment by qzheng527** [comment]
@mythi Ubuntu 22.04 is in our plan, but it won't be ready before Nov 2023.

**Comment by mythi** [comment]
> @mythi Ubuntu 22.04 is in our plan, but it won't be ready before Nov 2023.

Is v0.30.0 going to have Jammy packages?

**Comment by qzheng527** [comment]
> > @mythi Ubuntu 22.04 is in our plan, but it won't be ready before Nov 2023.
> 
> Is v0.30.0 going to have Jammy packages?

It is in our plan but may not happen in a short time because we need upgrade the glibc running in Occlum first.

**Comment by mythi** [comment]
@qzheng527 thanks for the update. It's a bit unfortunate that it takes so long time. 18.04 is already EOL which means Occlum users have only one LTS version to choose from.

**Comment by mythi** [comment]
> > @mythi Ubuntu 22.04 is in our plan, but it won't be ready before Nov 2023.
> 
> Is v0.30.0 going to have Jammy packages?

Or v0.30.1?

**Comment by qzheng527** [comment]
@mythi To have Jammy packages published, we have to redesign and re-layout [**occlum repo**](https://github.com/occlum/occlum-package-repos) to support both focal and jammy. This may take some time. But the Jammy debian package build is completed. You can refer to [Dockerfile](https://github.com/occlum/occlum/blob/0.30.1-dev/tools/docker/Dockerfile.ubuntu22.04-rt) for how to build and install Jammy packages through multi-stage docker build.

**Comment by mythi** [comment]
Thanks for the response. Building Occlum is not an option so I guess I'll have to keep using whatever exists today. What is the problem with "both focal and jammy" if the repo already has bionic and focal?

**Comment by qzheng527** [comment]
> Thanks for the response. Building Occlum is not an option so I guess I'll have to keep using whatever exists today. What is the problem with "both focal and jammy" if the repo already has bionic and focal?

@mythi Occlum doesn't support bionic and focal together. Before 0.27.0, Occlum supported bionic. Since 0.270, Occlum only supports focal.

**Comment by mythi** [comment]
I see. Is there a reason to stay with Focal?

**Comment by mythi** [comment]
The packages are available but failing: https://github.com/occlum/occlum/issues/1591#issuecomment-2244969258

**Comment by qzheng527** [comment]
@mythi Can you enable Occlum trace or debug log for us to do further investigation?

**Comment by mythi** [comment]
> @mythi Can you enable Occlum trace or debug log for us to do further investigation?

Full trace in my debug build here: https://github.com/confidential-containers/enclave-cc/actions/runs/10502382634/job/29093889761#step:13:19

**Comment by qzheng527** [comment]
@mythi Looks like the parameter **rootfs_config_ptr** passed from customized Occlum **init** is not in the correct memory range. It seems that last several bits got truncated somehow.
![image](https://github.com/user-attachments/assets/cefb27cf-ad1c-4ac5-9cb4-69bcea6a3823)
Can you check from your customized **init**? Also, how about the **rootfs_config_ptr** parameter in focal version?

**Comment by mythi** [comment]
> Can you check from your customized **init**? Also, how about the **rootfs_config_ptr** parameter in focal version?

This works with focal. The pointer is set to `std::ptr::null()` in this case: https://github.com/confidential-containers/enclave-cc/blob/dab7f6a4c5e1b511c2fdf491351bace2c288dfc3/src/runtime-boot/init/src/main.rs#L27-L28

**Comment by mythi** [comment]
And this also works Jammy `SGX_MODE=HW` and only fails with `SIM`

**Comment by qzheng527** [comment]
@mythi The Occlum customized syscall **SYS_MOUNT_FS** requires two parameters just like below.
https://github.com/confidential-containers/enclave-cc/blob/dab7f6a4c5e1b511c2fdf491351bace2c288dfc3/src/runtime-boot/init/src/main.rs#L82
In your Ok cases, probably the missing paramter happened to be null by luck.

**Comment by mythi** [comment]
> The Occlum customized syscall **SYS_MOUNT_FS** requires two parameters

thanks, good catch! It has worked quite long time without it. :-)

**Comment by mythi** [comment]
> > The Occlum customized syscall **SYS_MOUNT_FS** requires two parameters
> 
> thanks, good catch! It has worked quite long time without it. :-)

I got things working. There were other issues too like copy_bom not picking up certain Occlum glibc files that other parts of our code was expecting but things are OK now.

I'm fine closing.
