### ISSUE TITLE
[RFC]

### ISSUE THREAD

**Issue by saisai321123** [occlum/occlum#1378]
How to modify the time zone in Occlum？？？

includes:
  - base.yaml
targets:
  - target: /bin
    copy:
      - files:
        - ../team
        - ../etc/team.yaml
        - ../locales

  - target: /opt/occlum/glibc/etc
    copy:
      - files:
        - name: /usr/share/zoneinfo/Asia/Shanghai
          rename: localtime
          
          
This modification is not feasible
Do you know how to modify the time zone ？？？？？？？？？？？？？？？？？？？？

**Comment by ClawSeven** [comment]
By default, Occlum utilizes syscalls to access time, resulting in the time format of Occlum being the same as that of Linux, which is UTC. However, there is a localtime function provided by glibc which allows access to the local time using the path '/opt/occlum/glibc/etc/localtime', whereas musl uses the path '/etc/localtime'. Hence, if you are using glibc, you will need to modify the '/opt/occlum/glibc/etc/localtime' file.

**Comment by volcano0dr** [comment]
Related discussions are in #1379.
