### ISSUE TITLE
The mount command reports FUSE not found error

### ISSUE THREAD

**Issue by tatetian** [occlum/occlum#138]
# Summary

The new `occlum mount` command reports the following error:
```
fuse: device not found, try 'modprobe fuse' first
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

# Reproduction Steps

To reproduce the problem on a host OS of Ubuntu 18.04, follow the steps below:
```
$ docker run -it --device /dev/isgx occlum:occlum/0.16.0-ubuntu18.04
$ cd demos/hello_c
$ make
$ occlum init
$ cp hello_world image/bin/
$ occlum build
$ occlum run /bin/hello_world
$ mkdir mount
$ occlum mount /root/demos/hello_c/mount
```
The last command would generate the reported error message.

The Linux kernel seems to be built with fuse enabled:
```
$ cat /boot/config-`uname -r` | grep FUSE
CONFIG_FUSE_FS=y
# CONFIG_AUFS_BR_FUSE is not set
```
Is it a bug of the mount command or some misconfiguration of my test machine?

**Comment by tatetian** [comment]
It turns out that the `docker` must be given a `--privileged` or `--cap-add SYS_ADMIN --device /dev/fuse` flags so that a Docker container can use FUSE. See the discussion [here](https://github.com/docker/for-linux/issues/321).

**Comment by tatetian** [comment]
I think we need to improve doc to mention the necessary Docker flags to enable FUSE.

**Comment by liqinggd** [comment]
The root cause is that the docker container can not use FUSE functionality by default.

We can fix this by running the container with additional permissions --cap-add SYS_ADMIN --device /dev/fuse

I will update the README to explain it.
