### ISSUE TITLE
[BUG] SEFS external mount not work

### ISSUE THREAD

**Issue by enuoCM** [occlum/occlum#1382]
# Describe the bug
Add a mount config in Occlum.json like this, then build and start.
`{
  "target": "/mnt",
  "type": "sefs",
  "source": "/occlum_mnt"
}`

Write a file a.txt to /mnt in the Occlum libos sucessfully.
But there is nothing in /occlum_mnt.  
All data goes to run/mount/__ROOT.

# To reproduce
please follow https://github.com/occlum/occlum/issues/1311 and https://github.com/qzheng527/occlum/blob/external_mount/demos/bash/run_bash_demo.sh

# Expected behavior
The file a.txt should be encrypted under /occlum_mnt.

# Environment

- HW: [SGX2] 
- OS: [e.g. Ubuntu20.04
- Occlum version: [e.g. 0.29.6]

**Comment by qzheng527** [comment]
@enuoCM Please try 0.29.7. There is a known mount related issue in 0.29.6.

**Comment by enuoCM** [comment]
Thanks. 0.29.7 works!
