### ISSUE TITLE
[BUG] run java -version failed

### ISSUE THREAD

**Issue by fearlessfe** [occlum/occlum#1386]
# Describe the bug
when I run the occlum image, the java command have errors

the image is `occlum/occlum:latest-ubuntu20.04` , image hash is `571f295b580d`

I use the command to enter the container

`docker run -it --rm --device /dev/sgx_enclave --device /dev/sgx_provision occlum/occlum:latest-ubuntu20.04 bash`

Try the java -version command

`/opt/occlum/toolchains/jvm/java-11-alibaba-dragonwell/bin/java -version`

the error info are

![image](https://github.com/occlum/occlum/assets/21964308/4152e333-1340-467d-9ac7-76dfc1ad662d)

the same error with other java version

**Comment by jessehui** [comment]
May I ask why you are doing this? Based on your command, Java is not running inside Occlum. Please check out the Java demo we provided https://github.com/occlum/occlum/tree/master/demos/java.

**Comment by fearlessfe** [comment]
In previous version of `occlum/occlum:latest-ubuntu20.04` image(image hash is d5a78b0a431f), I install the `maven` and conffig the private repo. I commit the container to the new image `occlum/occlum:latest-ubuntu20.04-mvn` , this image is the build image for our java project.

```docker
FROM occlum/occlum:latest-ubuntu20.04-mvn AS builder

ENV LD_LIBRARY_PATH=/opt/occlum/toolchains/gcc/x86_64-linux-musl/lib \
    JAVA_HOME=/opt/occlum/toolchains/jvm/java-11-alibaba-dragonwell

WORKDIR /app

COPY . .

RUN /opt/apache-maven-3.8.8/bin/mvn -Dmaven.test.skip=true clean package

WORKDIR /app/occlum_instance

```

For some reason, I have to upgrade the `occlum/occlum:latest-ubuntu20.04` image, but now the maven cannot installed correctly because of the error above.

**Comment by jessehui** [comment]
OK, I see.

>  ![image](https://user-images.githubusercontent.com/21964308/266963333-4152e333-1340-467d-9ac7-76dfc1ad662d.png)


The error above indicates the loader can't find `libz.so.1` which provides the symbol shown below.  Thus, there are mainly two reasons:
1. `libz.so.1` is not installed in the current image. Please make sure you can find it under `/opt/occlum/toolchains/gcc/x86_64-linux-musl/lib`
2. The environment variable is not set correctly. Please try `LD_LIBRARY_PATH=/opt/occlum/toolchains/gcc/x86_64-linux-musl/lib /opt/occlum/toolchains/jvm/java-11-alibaba-dragonwell/bin/java -version`. If libz.so exists, you should get the correct result.

![截屏2023-09-14 10 28 37](https://github.com/occlum/occlum/assets/13930406/9078e2d9-7eca-4d6e-a26e-e9a0ecb41953)

**Comment by fearlessfe** [comment]
It works, thank you very much.
