### ISSUE TITLE
The mount command cannot handle relative path for mount point

### ISSUE THREAD

**Issue by tatetian** [occlum/occlum#139]
# Problem

The new `occlum mount` command, when given a relative path as the mount point, reports the following error:
```
error: Found argument 'mount' which wasn't expected, or isn't valid in this context

USAGE:
    sefs-cli <dir> mount

For more information try --help
```

# Expected behavior

A relative path should be accepted.

# Reproduction Steps

To reproduce the problem on a host OS of Ubuntu 18.04, follow the steps below:
```
$ docker run -it --device /dev/isgx --privileged occlum:occlum/0.16.0-ubuntu18.04
$ cd demos/hello_c
$ make
$ occlum init
$ cp hello_world image/bin/
$ occlum build
$ occlum run /bin/hello_world
$ mkdir mount
$ occlum mount mount
```
The last command would generate the reported error message.

**Comment by liqinggd** [comment]
The root cause is that the docker container can not use FUSE functionality by default, check out this [issue](https://github.com/docker/for-linux/issues/321)

We can fix this by running the container with additional permissions `--cap-add SYS_ADMIN --device /dev/fuse`

I will update the README to explain it.

**Comment by liqinggd** [comment]
This problem is not about the relative path,  the reason is that the argument `mount` as a path passed to `sefs-cli` is the same with the `mount` command used by `sefs-cli`, it cannot handle it.

**Comment by tatetian** [comment]
> The root cause is that the docker container can not use FUSE functionality by default, check out this [issue](https://github.com/docker/for-linux/issues/321)
> 
> We can fix this by running the container with additional permissions `--cap-add SYS_ADMIN --device /dev/fuse`
> 
> I will update the README to explain it.

I think this is intended to reply the other issue :)

**Comment by tatetian** [comment]
> This problem is not about the relative path, the reason is that the argument `mount` as a path passed to `sefs-cli` is the same with the `mount` command used by `sefs-cli`, it cannot handle it.

Ok. Then, let's fix this root cause.

**Comment by liqinggd** [comment]
> > The root cause is that the docker container can not use FUSE functionality by default, check out this [issue](https://github.com/docker/for-linux/issues/321)
> > We can fix this by running the container with additional permissions `--cap-add SYS_ADMIN --device /dev/fuse`
> > I will update the README to explain it.
> 
> I think this is intended to reply the other issue :)

Yes, I made a mistake about the issue number
