### ISSUE TITLE
[BUG] Mounting file from inside boot container is not available to be used by it

### ISSUE THREAD

**Issue by piotrpalcz** [occlum/occlum#1404]
This is a continuation from https://github.com/occlum/occlum/issues/1343
When I mount directory from host machine into the boot container I can do so only if it lands in the root of the container. But the boot agent is running inside /run/rune/boot_instance/initfs and treats that directory as its root. 
Tried also to mount the directory with a target of /run/rune/boot_instance/initfs or any directory inside there, also to /run/rune etc - getting an error of Error = ENOENT (#2, No such file or directory): EntryNotFound

# To reproduce
1.  Added mounting with nix into boot container 
```
let fs_type = String::from("hostfs");
let flags = MsFlags::empty();
let mount_path = Path::new("/run/rune/boot_instance/initfs/mnt");
let mountpoint_c = CString::new(mount_path.to_str().unwrap()).unwrap();
nix::mount::mount(
        Some(fs_type.as_str()),
        mountpoint_c.as_c_str(),
        Some(fs_type.as_str()),
        flags,
        Some("dir=/run/rune/boot_instance/host")
```
2. Run any pod/container
3. Build fails if target (last parameter for `nix::mount`) is set to be inside `/run/rune` subdirectory(so effectively to be available to runtime boot container). It does however work if mount is set to be in any directory in root of the container. For example it works for target `/mnt` so the mounting itself is working properly. 

# Expected behavior
I want to mount a file from host into runtime boot to be available during its operation, to read key value from it instead of hardcoded key. Mounting it inside `/mnt` and not in `/run/rune..` renders it unavailable 

# Logs
```2023-09-28T10:31:21.288Z][DEBUG][T1][#125][···Mount] mount: source: hostfs, target: /run/rune/boot_instance/initfs/mnt, flags: (empty), options: HostFS("/run/rune/boot_instance/host")`
[2023-09-28T10:31:21.288Z][ERROR][T1][#125][···Mount] Error = ENOENT (#2, No such file or directory): EntryNotFound```

# Environment

- HW: SIM
- OS:  Ubuntu22.04
- Occlum version: 0.29.7

# Additional context
This is continued from discussion here  https://github.com/occlum/occlum/issues/1343. Did exactly what was proposed there and it did help but does not solve the issue mentioned above hence this bug, as it does not do what was supposed to.

**Comment by dcmiddle** [comment]
cc: @guzongmin

**Comment by qzheng527** [comment]
@piotrpalcz 
I assumed you wanted to mount **/run/rune/boot_instance/host** ( in the host) into  **/run/rune/boot_instance/initfs/mnt** (boot instance initfs in init stage).
Thus you have to make sure the two directories are both existed in its corresponding fs ( host fs or occlum init fs).
From your description, probably the error was due to the **/run/rune/boot_instance/initfs/mnt** was not existed in Occlum boot instance initfs. You can create this folder by `fs::create_dir_all("/run/rune/boot_instance/initfs/mnt").unwrap();`  before the mount to confirm.

**Comment by piotrpalcz** [comment]
@qzheng527 
Thank you for reply
Added lines :
`let create_dir_path = "/run/rune/boot_instance/initfs/mnt";
    match fs::create_dir_all(create_dir_path ) {
        Ok(_) => println!("Directory '{}' created successfully!", create_dir_path),
        Err(err) => eprintln!("Error creating directory '{}': {}", create_dir_path, err),
    }
`
So now inside logs of Occlum i can see :
`Directory '/run/rune/boot_instance/initfs/mnt' created successfully!`
Yet still when I look inside the mount directory of my app there is :
`/run/containerd-test/io.containerd.runtime.v2.task/k8s.io/43c66768d80c47f94a0c4d13c7fc4ffd780b61ad1312b2e1b03f1f6e8ac16283/rootfs/run/rune/boot_instance/initfs# $ ll
total 48
bin/
dev/
etc/
host/
lib/
lib64/
opt/
proc/
root/
sys/
tmp/
`
So no mnt directory is visible there
mount_path for nix::mount is still  
`let mount_path = Path::new("/run/rune/boot_instance/initfs/mnt")`

**Comment by qzheng527** [comment]
@piotrpalcz Do not list Occlum FS (initfs and rootfs) directory in host env. The Occlum FS content (RW) is not visiable in host env. You can add some code to check when occlum run.

**Comment by mythi** [comment]
Just to recap our use-case: [we're looking to mount a directory from host that has files we want `init` to read](https://github.com/occlum/occlum/issues/1343#issuecomment-1698502382).

What would be the correct mount config to try this? We run this in a container so there's one extra level of "filesystem visibility" but can we look at this from Occlum perspective first.

**Comment by qzheng527** [comment]
@mythi Let's summarize.
1. Occlum can support hostfs mount in init process which discussed in this issue.
2. To make hostfs mount successful, the target diretory (in Occlum FS）and source directory (in Host FS) both have to be existed before mount action.
3. Users can check the content in target diretory (from Occlum, such as adding some code lines running in Occlum to check) or in source directory (from Host, such ls command).
4. Hostfs mount doesn't add any encrpytion thus the data is not proctected.

**Comment by piotrpalcz** [comment]
Thank you, was able to finally work through all of the layers and overlays thanks to yours comments
