### ISSUE TITLE
[BUG]clone example does not run in occlum

### ISSUE THREAD

**Issue by hhhcike567** [occlum/occlum#1434]
# Describe the bug
When running the [clone example](https://github.com/hhhcike567/test/blob/main/clone.c), an error occurs in occlum
```
# linux
$ ./clone 2
Hello, World!

INFO: This code is running under child process.
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20

INFO: Child process terminated.

# Occlum
$ occlum run /bin/clone 2
Hello, World!
ERROR: Unable to create the child process.
```

# Logs
run `OCCLUM_LOG_LEVEL=debug ` [log](https://github.com/hhhcike567/test/blob/main/clone.log)

# Environment

- HW: SGX1
- OS: Ubuntu20.04
- Occlum version: 0.29.6

How should I solve the clone error ?
Thanks a lot.

**Comment by jessehui** [comment]
Thanks for using Occlum. Currently, Occlum has not supported all the flags of `clone`.  And the logic to test clone flags is a bit different from Linux. Thus, there are different behaviors that you observe.

To address this issue, I would recommend using pthread library that we have heavily tested. If you still choose to use the `clone` syscall, please take a closer look at the comments here https://github.com/occlum/occlum/blob/19104ed3e74e382e85c4beac6a6cc0fc314b00ba/src/libos/src/process/do_clone.rs#L147 specify all the flags you need for clone.

**Comment by hhhcike567** [comment]
Thanks for your reply, I will try to use pthread library later.
