### ISSUE TITLE
[ERROR] occlum-pal: Failed to enter the enclave to execute a LibOS thread (host tid = 40444) with error code 0x1003: Out of TCS. (line 21, file src/ocalls/spawn.c)

### ISSUE THREAD

**Issue by baoqian426** [occlum/occlum#1454]
[ERROR] occlum-pal: Failed to enter the enclave to execute a LibOS thread (host tid = 40444) with error code 0x1003: Out of TCS. (line 21, file src/ocalls/spawn.c)

root@bc216f790123:~/demos/pytorch/standaloneR/occlum_instance# cat /proc/cpuinfo |grep processor
processor	: 0
processor	: 1
processor	: 2
processor	: 3
processor	: 4
processor	: 5
processor	: 6
processor	: 7
processor	: 8
processor	: 9
processor	: 10
processor	: 11

I set the "max_num_of_threads": 12,but get error,anyone can help me!

**Comment by zeroRains** [comment]
so, have you solve it? I also have the same problem

**Comment by baoqian426** [comment]
> so, have you solve it? I also have the same problem

I config max_num_of_threads=48,solve the problem
