### ISSUE TITLE
[BUG] Unexpected behavior of the clock_getres syscall

### ISSUE THREAD

**Issue by StanPlatinum** [occlum/occlum#1471]
# Describe the bug

The `clock_getres` is an important syscall that is needed by PHP.

When invoking this system call with both parameters set to -1 in Occlum, the expected outcome is an EINVAL (error code). However, Occlum surprisingly reports a successful execution instead.

# To reproduce

 Check the graph below.
![clock_getres](https://github.com/occlum/occlum/assets/7992257/20ea4cd3-e25f-4e45-b44b-a98b5e778d17)

# Expected behavior

The `clock_getres` system call is expected to return EINVAL. However, it returns Success within Occlum.

# Logs
If applicable, add logs to help explain your problem.

# Environment

- HW: [SGX1, SGX2] 
- OS: [Ubuntu20.04]
- Occlum version: [0.30.0]

**Comment by ClawSeven** [comment]
Thank you for bringing this important issue to our attention. The bug has been successfully addressed, and you can find the fix detailed in [Pull Request #1475](https://github.com/occlum/occlum/pull/1475) on GitHub. This fix PR is scheduled to be merged into the upcoming release of Occlum, version 0.30.1.

**Comment by StanPlatinum** [comment]
Thanks. Feel free to close the issue.
