### ISSUE TITLE
Faile to follow the instructions about occlum installer

### ISSUE THREAD

**Issue by ysminnpu** [occlum/occlum#151]
I am referring to https://github.com/occlum/occlum/releases/tag/0.16.0. One line says "apt install -y ./occlum.deb", although there is no  occlum.deb in the package. I guess it is occlum_0.16.0-1_amd64.deb.

**Comment by panaotizz** [comment]
Have you found a solution to this? Does the previous 'make'command work for you ?

**Comment by guzongmin** [comment]
The document is under review. You can try https://github.com/occlum/occlum/pull/200, if you need it now.

**Comment by guzongmin** [comment]
The document updated.
