### ISSUE TITLE
'std::bad_alloc' error when running C++ project

### ISSUE THREAD

**Issue by chiiips** [occlum/occlum#1511]
I meet this error when I run my C++ project, here is the occlum configuration:
``` shell
new_json="$(jq '.resource_limits.user_space_size = "10500MB" |
                .resource_limits.kernel_space_heap_size = "500MB" |
                .resource_limits.max_num_of_threads = 64 ' Occlum.json)" && \
echo "${new_json}" > Occlum.json
```
I've tried several user_space_size configure from 10000M to 10500M while fixing other configurations, but all got the bad_alloc error. After I raised the user_space_size to 11000M, it ran successfully. 
However, I ran the same project at REE environment with `usr/bin/time -v ./benchmark` and got the runtime info as below:
```
Command being timed: "./benchmark"
User time (seconds): 49.62
System time (seconds): 17.73
Percent of CPU this job got: 39%
Elapsed (wall clock) time (h:mm:ss or m:ss): 2:51.73
Average shared text size (kbytes): 0
Average unshared data size (kbytes): 0
Average stack size (kbytes): 0
Average total size (kbytes): 0
Maximum resident set size (kbytes): 9478160
Average resident set size (kbytes): 0
Major (requiring I/O) page faults: 8
Minor (reclaiming a frame) page faults: 3540591
Voluntary context switches: 36933
Involuntary context switches: 5788
Swaps: 0
File system inputs: 9402744
File system outputs: 12494992
Socket messages sent: 0
Socket messages received: 0
Signals delivered: 0
Page size (bytes): 4096
Exit status: 0
```
It seems like the peak usage of memory does not  exceed 9478160KB (about 9250MB). So I would like to know why the user space size needs to be set approximately 1GB higher than the usage in the REE. Since the project involves a lot of disk I/O, is that because there exists any large size of disk cache?

**Comment by jessehui** [comment]
@chiiips Thank you for using Occlum. Regarding the `Maximum resident set size (kbytes)` in the benchmark's output, we need to clarify whether this refers to physical memory usage or virtual memory usage. If it denotes physical memory usage, the explanation is straightforward. The `user_space_size` parameter in Occlum.json corresponds to virtual memory space, and it is a common scenario for a process to have a virtual memory space that exceeds the actual physical memory usage.

On the other hand, if it refers to virtual memory usage, the difference may result from different memory management algorithms used by Occlum compared to Linux for allocating virtual space. We have not previously observed such a significant difference, such as 1GB. However, it is conceivable in an extreme case where a user application attempts to allocate 900MB of memory. With Linux's memory allocator, there might be a contiguous space sufficient for this request. On the contrary, with Occlum's allocator, although there might be over 900MB of free memory, if it is split across separate ranges, Occlum would require an additional 900MB in user space that is not actively used by the application.

Lastly, regarding your question about disk caching: yes, Occlum does utilize disk caching, but the memory associated with this cache is considered part of the kernel’s memory space, not the user's.

**Comment by chiiips** [comment]
@jessehui Thanks for your reply!
