### ISSUE TITLE
Wrong sdk version mentioned in the installer how-to document 

### ISSUE THREAD

**Issue by ysminnpu** [occlum/occlum#152]
"Install Intel® SGX driver and Intel® SGX PSW Please follow Intel SGX Installation Guide to install SGX driver and SGX PSW." The embedded URL points to the document about SDK 2.9.1 instead of 2.11. I assume the installer feature is only available since the latest 0.16 release which relies on SDK 2.11. This needs to be fixed. 

Actually, maybe we need to  make this how-to independent of SDK versions.

**Comment by jessehui** [comment]
True, this should be updated to SDK 2.11. Thank you for reporting this.

**Comment by guzongmin** [comment]
The document updated.
