### ISSUE TITLE
Replacing ```fork``` with ```posix_spawn``` for Pre-Exec Preparation Work

### ISSUE THREAD

**Issue by hhhcike567** [occlum/occlum#1546]
- Feature Name: handling_fork_replacement_in_occlum
- Start Date: 2024-05-23

# Summary
This proposal addresses the challenge of replacing ```fork``` with ```posix_spawn``` in programs that require pre-exec preparation work, and seeks solutions or alternatives for running such programs on Occlum.

# Motivation
In the original program, after creating a child process using ```fork```, the child process performs some preparation work before calling ```execve``` to execute the target program. When replacing ```fork``` with ```posix_spawn```, the child process immediately executes the target program, skipping the necessary preparation steps. This results in the target program not functioning as expected.

Attempts to replace ```fork``` with ```vfork``` were not feasible. Therefore, a solution is needed to handle such scenarios in Occlum.

# Example
Here's a simplified example of the original program using fork:
```c
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>

int main() {
    pid_t pid = fork();

    if (pid == -1) {
        perror("fork failed");
        exit(EXIT_FAILURE);
    } else if (pid == 0) {
        // Child process
        // Preparation work before execve
        printf("Child: Preparing to execve...\n");

        // Example preparation work
        // (e.g., setting up environment, redirecting file descriptors, etc.)
        // If use posix_spawn, the above code cannot be run in occlum
        
        char *args[] = { "/path/to/target/program", NULL };
        execve(args[0], args, NULL);
        // If execve fails
        perror("execve failed");
        exit(EXIT_FAILURE);
    } else {
        // Parent process
        // Can perform other tasks or wait for the child process
        printf("Parent: Child process created with PID %d\n", pid);
        wait(NULL); // Optionally wait for child process to finish
    }

    return 0;
}
```
Could you please suggest a solution for this issue? Is it possible to run such a program on Occlum, or is there a fundamental limitation that prevents this?

Thanks!

**Comment by jessehui** [comment]
@hhhcike567 Thank you for using Occlum. Replacing `fork` with `posix_spawn` is possible.  Take a closer look at the man page of `posix_spawn`, it provides argument includes `posix_spawn_file_actions_t ` and `posix_spawnattr_t`  and `envp`. Actually, we have successfully utilize these arguments to run bash script inside Occlum by replacing `fork` with `posix_spawn`.  You can take a ook at this commit to get some inspiration: https://github.com/occlum/bash/pull/1/commits/ef4967a80e577b854268704db1e00bc09d8f3983

**Comment by hhhcike567** [comment]
Solved, thanks!
