### ISSUE TITLE
[BUG] EINVAL (#22, Invalid argument): cannot find the interpreter segment 

### ISSUE THREAD

**Issue by Arthur-Sk** [occlum/occlum#1558]
# Describe the bug
Trying to implement the [confidential containers](https://github.com/confidential-containers/confidential-containers) using [enclave-cc](https://github.com/confidential-containers/enclave-cc) runtime. The overall schema is shown [here](https://github.com/confidential-containers/enclave-cc/blob/main/docs/images/ecc_components_workflow.png).
Everything gets to the point of the app enclave container, where the app image is successfully decrypted, and then is tried to be launched in the app enclave, when the following exception is thrown. The image is built on top of the [frankenphp](https://github.com/dunglas/frankenphp), the resulting app image is available [here](https://hub.docker.com/layers/skarthur/php-test-app/pie/images/sha256-6160ad218cb46b72df66e6288135e3749ccc6820c20a9817c72ccc8563a0ec37?context=repo). 

# To reproduce
1. Builder the `docker.io/skarthur/php-test-app:pie` image
2. Run the webserver via `./occlum-run /app/frankenphp php-server`
3. Get the exception in the output

# Expected behavior
The test app is expected to be launced in the enclave, the port 80 listening for the requests, and returning test JSON responses.

# Logs
```
failed to boot up LibOS: EINVAL (#22, Invalid argument): cannot find the interpreter segment [line = 189, file = src/process/do_spawn/mod.rs]
[ERROR] occlum-pal: occlum_ecall_new_process returns EINVAL (line 210, file src/pal_api.c)
```

# Environment

- HW: SGX2
- OS: Ubuntu22.04
- Occlum version: 0.30.1-1
- SGX SDK version: 2.23.100

# Additional context
Any suggestions are welcome.

**Comment by qzheng527** [comment]
@Arthur-Sk The error message indicated that the interpreter was not found for the binary you tried to run (** /app/frankenphp**).
It maybe the binanry is musl-libc but your Occlum instance env is glibc based. You could enable occlum debug log to get more information.

**Comment by Arthur-Sk** [comment]
> @Arthur-Sk The error message indicated that the interpreter was not found for the binary you tried to run (** /app/frankenphp**). It maybe the binanry is musl-libc but your Occlum instance env is glibc based.
Is there a way to find out what libs my binary is based on? Is it possible to build occlum with these libs?


> You could enable occlum debug log to get more information.
I've already run my occlum instance with the OCCLUM_LOG_LEVEL=trace env var. Are there logs somewhere else other the output?

**Comment by qzheng527** [comment]
@Arthur-Sk I started the docker [image](https://hub.docker.com/layers/skarthur/php-test-app/pie/images/sha256-6160ad218cb46b72df66e6288135e3749ccc6820c20a9817c72ccc8563a0ec37?context=repo)  you shared and found out it was alpine OS which is musl-libc based. 
Genenelly, once you set OCCLUM_LOG_LEVEL=trace, the Occlum log will be printed out in the stdout/stderr. If no log, I think you'd better seek help from enclave-cc about how to get Occlum log.

**Comment by Arthur-Sk** [comment]
@qzheng527 thank you for the explanation
