### ISSUE TITLE
occlum build occupies full storage space, causing errors and failures

### ISSUE THREAD

**Issue by BuJianlin** [occlum/occlum#157]
When I tried to use the **xgboost** demo with **HIGGS** dataset for training tasks in the occlum container, the phenomenon is as follows:

- Xgboost without occlum can run successfully.
- Execution of **occlum build** failed, when using higgs data set.

 The process of occlum build is as follows:
1. Occlum init succeeded.
2. Execution of occlum build and output the following information:

> Enclave sign-tool: /opt/intel/sgxsdk/bin/x64/sgx_sign
> Enclave sign-key: /opt/occlum/etc/template/Enclave.pem
> SGX mode: HW
> Building new image...
> [+] Home dir is /root
> [+] Open token file success!
> [+] Token file invalid, will create new token file
> [+] Init Enclave Successful 2688671002132482!

3. Execution of occlum build is still executing, and the **occlum_instance/build** folder is gradually increasing until it occupies the full storage space, and occlum build failed, the error is as follows:

> [root@ occlum_instance]# thread 'main' panicked at 'write_at -1', src/sgx_dev.rs:76:18
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> thread 'main' panicked at 'flush -1', src/sgx_dev.rs:90:18
> stack backtrace:
>    0:     0x55c48b1ecb54 - backtrace::backtrace::libunwind::trace::hcdd38e03c5c0ae1d
>                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
>    1:     0x55c48b1ecb54 - backtrace::backtrace::trace_unsynchronized::he5bd7c616dadfd7d
>                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
>    2:     0x55c48b1ecb54 - std::sys_common::backtrace::_print_fmt::h5c76d4ca71f55821
>                                at src/libstd/sys_common/backtrace.rs:78
>    3:     0x55c48b1ecb54 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2c8c63d62d7bea1c
>                                at src/libstd/sys_common/backtrace.rs:59
>    4:     0x55c48b20e62c - core::fmt::write::h97d981a565c87982
>                                at src/libcore/fmt/mod.rs:1069
>    5:     0x55c48b1ea693 - std::io::Write::write_fmt::h76b54795ca4d1941
>                                at src/libstd/io/mod.rs:1439
>    6:     0x55c48b1ef175 - std::sys_common::backtrace::_print::h93fb2909159290d7
>                                at src/libstd/sys_common/backtrace.rs:62
>    7:     0x55c48b1ef175 - std::sys_common::backtrace::print::ha755c3134746c2d0
>                                at src/libstd/sys_common/backtrace.rs:49
>    8:     0x55c48b1ef175 - std::panicking::default_hook::{{closure}}::h3a7ab24b109d5437
>                                at src/libstd/panicking.rs:198
>    9:     0x55c48b1eeeb2 - std::panicking::default_hook::h2aa3c18a39936382
>                                at src/libstd/panicking.rs:218
>   10:     0x55c48b1ef7d2 - std::panicking::rust_panic_with_hook::h5035e60b675c5c99
>                                at src/libstd/panicking.rs:511
>   11:     0x55c48b1ef3bb - rust_begin_unwind
>                                at src/libstd/panicking.rs:419
>   12:     0x55c48b1ef32b - std::panicking::begin_panic_fmt::h500c392f8d4dbfb3
>                                at src/libstd/panicking.rs:373
>   13:     0x55c48b0cfeb9 - <sefs_cli::sgx_dev::SgxFile as rcore_fs_sefs::dev::File>::flush::h9d241aba0a33f60a
>   14:     0x55c48b1758f1 - rcore_fs_sefs::INodeImpl::update_mac::hdd50e1ad3dc2e81f
>   15:     0x55c48b177e42 - <rcore_fs_sefs::INodeImpl as core::ops::drop::Drop>::drop::h6bf8c126664a8809
>   16:     0x55c48b173f6d - core::ptr::drop_in_place::h79681329572f40e2
>   17:     0x55c48b18bbdb - alloc::sync::Arc<T>::drop_slow::he9f75fd4be900061
>   18:     0x55c48b187eb3 - rcore_fs_cli::zip::zip_dir::h92d325cfa7b7af54
>   19:     0x55c48b187621 - rcore_fs_cli::zip::zip_dir::h92d325cfa7b7af54
>   20:     0x55c48b0d3c7e - sefs_cli::main::h7974fef0dcbb7302
>   21:     0x55c48b0ce9f3 - std::rt::lang_start::{{closure}}::h2e3da2816c82bf8c
>   22:     0x55c48b1efc18 - std::rt::lang_start_internal::{{closure}}::h749f73f80f2a20f1
>                                at src/libstd/rt.rs:52
>   23:     0x55c48b1efc18 - std::panicking::try::do_call::h34ae69cab909f7d2
>                                at src/libstd/panicking.rs:331
>   24:     0x55c48b1efc18 - std::panicking::try::he6d9ae6f665ea78e
>                                at src/libstd/panicking.rs:274
>   25:     0x55c48b1efc18 - std::panic::catch_unwind::hb821659e1ed61148
>                                at src/libstd/panic.rs:394
>   26:     0x55c48b1efc18 - std::rt::lang_start_internal::hc7231d8ca9ca0aea
>                                at src/libstd/rt.rs:51
>   27:     0x55c48b0d4172 - main
>   28:     0x7f43e57286a3 - __libc_start_main
>   29:     0x55c48b0c786e - _start
>   30:                0x0 - <unknown>
> thread panicked while panicking. aborting.
> make: *** [/opt/occlum/build/bin/occlum_build.mk:131: /root/occlum_instance/build/mount/__ROOT/metadata] Illegal instruction (core dumped)
> make: *** Deleting file '/root/occlum_instance/build/mount/__ROOT/metadata'

My execution environment is as follows:

- centos: 8.1; linux kernel: 4.18.0; occlum container: 0.15.0-ubuntu18.04
- ubuntu: 18.04; linux kernel: 4.18.0; occlum container: 0.15.0-ubuntu18.04

**Comment by BuJianlin** [comment]
[issue.zip](https://github.com/occlum/occlum/files/5265390/issue.zip)

Reproduce steps:

1. Start occlum container [0.15.0-ubuntu18.04](https://hub.docker.com/layers/occlum/occlum/0.15.0-ubuntu18.04/images/sha256-a8d7ade64ba727a71199ee1319914ebd123f3c3bf9ce4ebf270bf209406ddc6a?context=explore)
2. Install taskset and numactl
3. Copy issue.zip and unzip.
4. prepare dataset:
`source ./prepare_dataset.sh`
5. prepare environments:
`source ./prepare_env.sh`
6. exec xgboost without occlum:
`./exec_host.sh`
7. **exec xgboost with occlum failed, when occlum build**:
`./exec_occlum.sh`

**Comment by liqinggd** [comment]
Hi @BuJianlin , this issue may be caused by a bug of sefs, which is a dependency of Occlum. The sefs cannot handle big file in 0.15.0, and we have already fixed it in 0.16.0, could you please try this in 0.16.0 ?

**Comment by BuJianlin** [comment]
> Hi @BuJianlin , this issue may be caused by a bug of sefs, which is a dependency of Occlum. The sefs cannot handle big file in 0.15.0, and we have already fixed it in 0.16.0, could you please try this in 0.16.0 ?

Thanks for your reply, and I will try to check whether the 0.16.0 of occlum can solve the problem.

**Comment by tatetian** [comment]
Another workaround is is to access the data through the host FS mounted at `/host`. Dataset is not the sort of data that one usually put into a Docker image. Or Occlum image, in our case. But I have to say that accessing the untrusted host files from `/host` (without any integrity check) is not a good idea, either. So using `/host` is only a workaround.

**Comment by BuJianlin** [comment]
> Another workaround is is to access the data through the host FS mounted at `/host`. Dataset is not the sort of data that one usually put into a Docker image. Or Occlum image, in our case. But I have to say that accessing the untrusted host files from `/host` (without any integrity check) is not a good idea, either. So using `/host` is only a workaround.

Agree with your opinion. The untrusted host files from /host (without any integrity check) is a insecure practice, it will bring unknown risks.

**Comment by yao-matrix** [comment]
@tatetian ,does Occlum support protected fs? If yes, we can use protected fs to protect data, no need to put data into Occlum image, which seems not the right thing to do from application perspective. Thx

**Comment by BuJianlin** [comment]
> > Hi @BuJianlin , this issue may be caused by a bug of sefs, which is a dependency of Occlum. The sefs cannot handle big file in 0.15.0, and we have already fixed it in 0.16.0, could you please try this in 0.16.0 ?
> 
> Thanks for your reply, and I will try to check whether the 0.16.0 of occlum can solve the problem.

@liqinggd It has been verified that the issue is resolved in version 0.16 of occlum. Thanks for your help.
