### ISSUE TITLE
[BUG] syscall() does not preserve XMM registers

### ISSUE THREAD

**Issue by thomasten** [occlum/occlum#1585]
# Describe the bug
According to the manpage, the libc syscall() wrapper, like SYSCALL in general, is supposed to preserve (most) registers, but it doesn't preserve XMM registers inside Occlum.

# To reproduce
```
docker run -it occlum/occlum:0.30.1-ubuntu20.04

cd demos/hello_c

cat << 'EOF' > hello_world.c

#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <sys/syscall.h>
#include <unistd.h>

int main() {
	uint64_t x[16][2];
	asm("vzeroall");
	syscall(SYS_open, "foo", O_CREAT, 0644);
	asm("movdqu %%xmm0, %0" : "=m"(x[0]));
	asm("movdqu %%xmm1, %0" : "=m"(x[1]));
	asm("movdqu %%xmm2, %0" : "=m"(x[2]));
	asm("movdqu %%xmm3, %0" : "=m"(x[3]));
	asm("movdqu %%xmm4, %0" : "=m"(x[4]));
	asm("movdqu %%xmm5, %0" : "=m"(x[5]));
	asm("movdqu %%xmm6, %0" : "=m"(x[6]));
	asm("movdqu %%xmm7, %0" : "=m"(x[7]));
	asm("movdqu %%xmm8, %0" : "=m"(x[8]));
	asm("movdqu %%xmm9, %0" : "=m"(x[9]));
	asm("movdqu %%xmm10, %0" : "=m"(x[10]));
	asm("movdqu %%xmm11, %0" : "=m"(x[11]));
	asm("movdqu %%xmm12, %0" : "=m"(x[12]));
	asm("movdqu %%xmm13, %0" : "=m"(x[13]));
	asm("movdqu %%xmm14, %0" : "=m"(x[14]));
	asm("movdqu %%xmm15, %0" : "=m"(x[15]));
	for (int i = 0; i < 16; ++i)
		printf("%d %lx %lx\n", i, x[i][0], x[i][1]);
}

EOF

make
mkdir occlum_workspace && cd occlum_workspace
occlum init && rm -rf image
copy_bom -f ../hello.yaml --root image --include-dir /opt/occlum/etc/template
SGX_MODE=SIM occlum build
occlum run /bin/hello_world
```

# Expected behavior
All printed register values should be 0.

# Actual behavior
Some register values have been clobbered by syscall().

**Comment by guzongmin** [comment]
This is a design compromise. If every syscall had to save the state of all XMM registers, the processing time for syscalls would increase. Of course, if all applications relied on "the values of these registers not changing after a syscall," then this cost would be justified. However, in reality, very few applications use XMM registers before and after a syscall and expect them to remain unchanged. Therefore, we decided to save and restore only a small number of XMM registers, leaving the rest for the user to handle. This is the best choice for most applications. We apologize for not emphasizing this point.

**Comment by thomasten** [comment]
Thank you for the explanation @guzongmin!
This behavior breaks Go starting with v1.21. So if you would update occlum-go to this version, do I understand correctly that you would fix this in your patch of the Go runtime instead of changing the behavior of syscall in Occlum?

**Comment by guzongmin** [comment]
Please try https://github.com/occlum/go/commits/ago1.20.0/

**Comment by thomasten** [comment]
Thanks for the hint. This is the answer to my question: https://github.com/occlum/go/commit/18cf01cb4f67f88eb185c9c1655552620ff8333a
