### ISSUE TITLE
[BUG] apt dependency issues

### ISSUE THREAD

**Issue by mythi** [occlum/occlum#1591]
# Describe the bug
Occlum deb packages have broken dependencies

# To reproduce
1. Install Occlum using apt from `https://occlum.io/occlum-package-repos/debian focal main` like https://github.com/confidential-containers/enclave-cc/blob/19a663883093be51df191fc4af8e2dcd6d69b66d/tools/packaging/build/unified-bundle/Dockerfile#L49-L53

# Expected behavior
no dependency problems (it was like this 3 weeks ago)

# Logs
```
#13 1.368 Some packages could not be installed. This may mean that you have
#13 1.368 requested an impossible situation or if you are using the unstable
#13 1.368 distribution that some required packages have not yet been created
#13 1.368 or been moved out of Incoming.
#13 1.368 The following information may help to resolve the situation:
#13 1.368 
#13 1.368 The following packages have unmet dependencies:
#13 1.435  occlum : Depends: occlum-toolchains-gcc (= 0.27.0-1) but 0.27.0-focal-1 is to be installed
#13 1.446 E: Unable to correct problems, you have held broken packages.
```

**Comment by qzheng527** [comment]
@mythi Occlum has released both focal and jammy packages since 0.30.1. Thus the package names need add focal or jammy.
So for your case, please refer to [Dockerfile.ubuntu20.04-rt](https://github.com/occlum/occlum/blob/0.30.1-dev/tools/docker/Dockerfile.ubuntu20.04-rt#L30) and [Dockerfile.ubuntu22.04-rt](https://github.com/occlum/occlum/blob/0.30.1-dev/tools/docker/Dockerfile.ubuntu22.04-rt#L30).
Please note, the 0.30.1 focal and jammy versions are only for test. Our plan is to do formal release since 0.31.0 in coming weeks.

**Comment by mythi** [comment]
@qzheng527 ok thanks for the update. so it sounds packages with `-focal` were added to the repo and our version pinning fails. 

jammy was not available at the time 0.30.1 was released because I've been following via #1361  (which I guess can be closed now?)

**Comment by qzheng527** [comment]
@mythi Actually jammy 0.30.1 is also available ( though not formal release). You could try it.
![image](https://github.com/user-attachments/assets/2a877dc7-2472-4c21-a546-d9df84b38d21)

**Comment by mythi** [comment]
> Actually jammy 0.30.1 is also available ( though not formal release). You could try it.

Jammy seems to have an issue and fails with SGX_MODE=SIM.

**Comment by mythi** [comment]
```
Error: Os { code: 14, kind: Uncategorized, message: "Bad address" }
[ERROR] occlum-pal: The init process exit with code: 1 (line 63, file src/pal_api.c)
[ERROR] occlum-pal: Failed to run the init process: EINVAL (line 151, file src/pal_api.c)
```

**Comment by qzheng527** [comment]
> > Actually jammy 0.30.1 is also available ( though not formal release). You could try it.
> 
> Jammy seems to have an issue and fails with SGX_MODE=SIM.

It passed the CI test in SIM mode.
https://github.com/occlum/occlum/blob/0.31.0-rc/.github/workflows/package_repo_setup_and_test.yml#L272

**Comment by mythi** [comment]
OK, for reference:

this works OK: https://github.com/confidential-containers/enclave-cc/pull/420/files
this fails: https://github.com/confidential-containers/enclave-cc/pull/198/files

**Comment by mythi** [comment]
Closing but keeping #1361 open.
