### ISSUE TITLE
[BUG] Can't make it work with rust code

### ISSUE THREAD

**Issue by GuillaumeRobin9** [occlum/occlum#1594]
# Describe the bug
(Sorry if this is not the right place to ask this question.)

I encountered an error when trying to run Occlum with a Rust project.

# To reproduce
1. cd /tmp && cargo new hello_rust
2. cd hello_rust
3. occlum-cargo build --release
4. cd .. && occlum new occlum-instance
5. cp hello_rust/target/x86_64-unknown-linux-musl/release/hello_rust /tmp/occlum-instance/
6. cd /tmp/occlum-instance && occlum build
7. occlum run /bin/hello_rust

# Expected behavior
Occlum works perfectly with C based on the Hello_World test from this GitHub page: https://github.com/occlum/occlum/blob/master/docs/install_occlum_packages.md. However, I think it is supposed to work with Rust too, since there is functionality to compile Rust such as occlum-cargo. Still, I can't make it work.

# Logs
If applicable, add logs to help explain your problem.

# Environment

- HW: SGX1
- OS: Ubuntu20.04
- Occlum version: 0.30.0

# Additional context
The error I get after running the project is the following : 
```
root@241a1604fa5d:/tmp/occlum-instance# occlum run /tmp/occlum-instance/image/bin/hello_rust 
failed to boot up LibOS: EACCES (#13, Permission denied): program path is NOT a valid entry point [line = 354, file = src/entry.rs]
[ERROR] occlum-pal: occlum_ecall_new_process returns EACCES (line 210, file src/pal_api.c)
```

# Possible solution/Implementation
Not obligatory, but suggest a fix/reason for the bug.

**Comment by volcano0dr** [comment]
cp hello_rust/target/x86_64-unknown-linux-musl/release/hello_rust /tmp/occlum-instance/image/bin/

**Comment by GuillaumeRobin9** [comment]
> cp hello_rust/target/x86_64-unknown-linux-musl/release/hello_rust /tmp/occlum-instance/image/bin/ occlum run /bin/hello_rust
Yes the path for the occlum run is already to the hello_rust binaries

**Comment by GuillaumeRobin9** [comment]
Well, I don't really understand. 
I can't find the binaries in /bin, but I can still execute it with occlum run. Autocompletion doesn't find it, and if I list all files in /bin, there is no hello_rust. 
Well, it's still working.
