### ISSUE TITLE
Enable LFX Insights On The Occlum Project 

### ISSUE THREAD

**Issue by bensternthal** [occlum/occlum#1606]
This issue is to track the request to enable LFX Insights for the Occlum project. LFX Insights has already been activated for several other CCC projects and we enable this by default for new projects

**What Is LFX Insights**
Insights provide projects with more visibility into their community dynamics, particularly around contributors, organizations, issues, and pull request metrics. It does this through an app (similar to the DCO bot) installed at the organization level. This is then enabled for one or more repos under the organization. Insights uses [crowd.dev](http://crowd.dev/) under the hood to gather read-only data about specified public repositories in a GitHub organization.

**What Information Is Collected (only public information from Github)**

- Stars/Un-stars
- Forks
- Issues
- Pull requests
- Discussions
- Comments on issues/pull requests/discussions
- Closing of issues/pull requests/discussions

**What I Need From The Project**

If folks have any questions or objections, please note this in the issue. If there are none we will enable insights in a week. 

**How Do We Turn This On**

I need to be made an admin (this can be temporary) on the org, this will allow me to install the read only Linux Foundation app. Once I install the app my privileges can be revoked.

Note I am currently on staff at the LF and one of the Program Managers on CCC. Feel free to verify my identity with folks on CCC.

**More Info**
You can find [Insights documentation here](https://docs.linuxfoundation.org/lfx/insights/v3-beta-version-current).

**Comment by jessehui** [comment]
Hi Ben, thank you for letting us know. I have no problem with that. Could you also write a email to us just for double verification? Please include your github account name in the email. Thank you

**Comment by riaankleinhans** [comment]
@jessehui I have taken over from Ben on CCC as the Linux Foundation Program manager and can assist with this process.
I will send a conformation email on your intel email address. If you prefer another address, please DM me on CCC Slack.

**Comment by riaankleinhans** [comment]
LF Community manage app have been installed. This can be closed. Thank you.
