### ISSUE TITLE
[RFC] Some questions about mysql on occlum

### ISSUE THREAD

**Issue by Kronlal** [occlum/occlum#1618]
- Feature Name: mysql on occlum
- Start Date: 2024-09-15

# Summary
[summary]: #summary

I started an occlum container and ran a springboot back-end program inside the tee, wanting to access mysql that is also deployed in occlum(not necessarily the same occlum as the springboot program), and also wanted to access normal mysql outside the tee.

# Motivation
[motivation]: #motivation

Almost all java web back-end programs need to access mysql, so it is a natural idea for springboot to access mysql in occlum, and there may be a need to access normal mysql outside of occlum.

# Guide-level explanation
[guide-level-explanation]: #guide-level-explanation

- 

# Reference-level explanation
[reference-level-explanation]: #reference-level-explanation

- 

# Drawbacks
[drawbacks]: #drawbacks

- 

# Rationale and alternatives
[rationale-and-alternatives]: #rationale-and-alternatives

- 

# Prior art
[prior-art]: #prior-art

- 

# Unresolved questions
[unresolved-questions]: #unresolved-questions

How does Springboot in occlum access mysql deployed in occlum? I see demos is accessed via a script. And how to access normal mysql deployed outside of occlum? Should springboot and mysql exist in two separate tee or two processes in one tee, which is recommended? If you can give some general advice, I would be grateful! Thank you!

# Future possibilities
[future-possibilities]: #future-possibilities

-

**Comment by Kronlal** [comment]
I have solved the problem, thank you!

**Comment by Ariel08081214** [comment]
@Kronlal Hai，I have the same question about this topic，how do you deal with this case？Can you give me a favor？Thank u
