### ISSUE TITLE
Memory leakage in exception handling

### ISSUE THREAD

**Issue by tatetian** [occlum/occlum#162]
# Expected behavior

The following simple C program, which repeats doing one operation that has no resource allocation and no side effect, should be able to run forever (if there is no memory leakage problem inside the LibOS). The program tests two different operations: one is `getpid` syscall, the other is `rdtsc` instruction. The latter one will cause SGX hardware exceptions, which are internally handled by the LibOS as a special class of syscalls. So both of them are treated by the LibOS as syscalls.

```c
#include <sys/types.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>

static __inline__ unsigned long long rdtsc(void) {
    unsigned hi, lo;
    __asm__ __volatile__ ("rdtsc" : "=a"(lo), "=d"(hi));
    return ( (unsigned long long)lo)|( ((unsigned long long)hi)<<32 );
}

volatile unsigned long long dummy;

// This is the suspect operation that might cause a memory leakage in Occlum
static void suspect_op() {
#if 1
    // This will cause memory leakage
    dummy = rdtsc();
#else
    // This is ok
    dummy = (unsigned long long) getpid();
#endif
}

int main() {
    printf("repeat the suspect operation for %llu times to detect memory leakage\n", max_count);
    unsigned long long max_count = 1000*1000*1000;
    unsigned long long count = 0;
    while ((count++) < max_count) {
        if (count % 10000 == 0) {
            printf("count = %llu\n", count);
        }
        suspect_op();
    }
    printf("pass\n");
    return 0;
}
```

# Actual results

Unfortunately, when running on Occlum, the program will eventually crash (due to out of memory) if the operation is `rdtsc`. Set a reasonably small value for `.resource_limits.kernel_space_heap_size` (e.g., `3MB`), the program will crash in several seconds. Increase the `kernel_space_heap_size` and you will see the program runs a bit longer.

According to my calculation, each exception handling triggered by `rdtsc` will leak 30B memory.

**Comment by guzongmin** [comment]
The fix is ready at https://github.com/occlum/linux-sgx/pull/6

**Comment by guzongmin** [comment]
fixed by SGX SDK
