### ISSUE TITLE
[BUG] run python not work in bash script

### ISSUE THREAD

**Issue by BUPT-wxq** [occlum/occlum#1626]
# Describe the bug
when occlum run /bin/bash /home/dataiku/dss_data/bin/dss start，many python command does not work in bash script
# To reproduce
# Expected behavior
all python command work properly in bash script .
# Logs
If applicable, add logs to help explain your problem.
+ /home/dataiku/dss_data/bin/python /home/dataiku/dataiku-dss-13.1.2/scripts/dkuinstall/install_config.py -get nodetype
/home/dataiku/dss_data/bin/.script.lock.S997rm: posix_spawn error code = 2
: No such file or directory
# Environment

- HW: [e.g. SGX1, SGX2] 
- OS: [e.g. Ubuntu20.04]
- Occlum version: image occlum/occlum:0.31.0-rc-ubuntu22.04 (54125e263dc3)

# Additional context

# Possible solution/Implementation
Not obligatory, but suggest a fix/reason for the bug.

**Comment by qzheng527** [comment]
@BUPT-wxq Please provide app log and Occlum log (OCCLUM_LOG_LEVEL=debug occlum run xxx).
