### ISSUE TITLE
[RFC]How does Occlum run on a CPU that supports TEE but is not intel SGX?

### ISSUE THREAD

**Issue by walkovernamtso** [occlum/occlum#1628]
cpu: HYGON 
os: ububtu 20.04

**Comment by Bonjourz** [comment]
Hi @walkovernamtso ，

Do you want to run Occlum inside TEE environment?

If the answer is Yes, you may need to install HyperEnclave on your platform by following the instructions here: https://github.com/asterinas/hyperenclave. Then you can run Occlum inside the TEE provided by HyperEnclave.

If the answer is No, you can try Occlum's simulation mode. Related instructions can be gotten by searching 
"simulation" in this page: https://occlum.readthedocs.io/en/latest/quickstart.html.
