### ISSUE TITLE
[BUG] nginx dose not work, 

### ISSUE THREAD

**Issue by BUPT-wxq** [occlum/occlum#1633]
# Describe the bug
occlum can not support nginx, Is there a way to replace nginx to route forward？

# To reproduce
1. 
2. 
3. 
4. 

# Expected behavior

# Logs
If applicable, add logs to help explain your problem.

# Environment

- HW: [e.g. SGX1, SGX2] 
- OS: [e.g. Ubuntu20.04, CentOS8.2]
- Occlum version: [e.g. 0.28.0]

# Additional context

# Possible solution/Implementation
Not obligatory, but suggest a fix/reason for the bug.

**Comment by jessehui** [comment]
NGINX is known to have `fork` in it which Occlum doesn't support.
