### ISSUE TITLE
how to demo memory data is protected?

### ISSUE THREAD

**Issue by onesafe** [occlum/occlum#185]
i practice occlum demo hello_world.c success and also meet java demo hang https://github.com/occlum/occlum/issues/129

but i have a question, how to prove the memory data is protected? i mean, how to demo it?

thanks for responding.

**Comment by guzongmin** [comment]
The simulation mode has some limitations, which impact the Java demo. Do you have a SGX HW to test the java?

**Comment by onesafe** [comment]
> The simulation mode has some limitations, which impact the Java demo. Do you have a SGX HW to test the java?

i use simulation mode, i don't have SGX HW.

**Comment by guzongmin** [comment]
The simulation mode is not able to protect the application. Simulation mode is only used for testing.

**Comment by onesafe** [comment]
OK, understand.
If, if i have SGX HW, can you share your experience how to demo the memory data is protected?
thanks

**Comment by guzongmin** [comment]
> OK, understand.
> If, if i have SGX HW, can you share your experience how to demo the memory data is protected?
> thanks

If you have a HW, at first you need to sign it as **release** mode. When you loading the enclave, you would know the virtual address of EPC pages. When you get the virtual address of EPC page, you could try to read it with any way. I promiss you could not read the memory of **release** mode enclave.   

Below is a sample of the EPC infomation in /proc/[pid]/maps

7fffd5832000-7fffd59fa000 r-xp 00000000 00:00 0
7fffd59fa000-7fffd5bf9000 ---p 00000000 00:00 0
7fffd5bf9000-7fffd5c09000 r--p 00000000 00:00 0
7fffd5c09000-7fffd7c1e000 rw-p 00000000 00:00 0
7fffd7c1e000-7fffd7c2e000 ---p 00000000 00:00 0
7fffd7c2e000-7fffd7d2e000 rw-p 00000000 00:00 0
7fffd7d2e000-7fffd7d3e000 ---p 00000000 00:00 0
7fffd7d3e000-7fffd7d41000 rw-p 00000000 00:00 0
7fffd7d41000-7fffd7d51000 ---p 00000000 00:00 0
7fffd7d51000-7fffd7d53000 rw-p 00000000 00:00 0
7fffd7d53000-7fffd7d63000 ---p 00000000 00:00 0

**Comment by onesafe** [comment]
Thank You
