### ISSUE TITLE
Put resolv.conf file into occlum instance

### ISSUE THREAD

**Issue by henrysun007** [occlum/occlum#202]
The [resolv.conf](https://man7.org/linux/man-pages/man5/resolv.conf.5.html) is often used by applications in occlum, but the errors resulting from the missing of the file are different across applications. Occlum users may not know whether the file is needed from the errors after `occlum run`.  They may not know whether to copy the file into occlum instance before `occlum build` , either.

**Comment by guzongmin** [comment]
https://github.com/occlum/occlum/commit/d35d98d551bea98174f88fa7b639be79af1caaa9
feature supported
