### ISSUE TITLE
Is there a way to statically link libraries in order to run a binary?

### ISSUE THREAD

**Issue by panaotizz** [occlum/occlum#216]
I want to run 4 different binaries but they depend on 3 crypto libraries. From what i understand the libraries are not accessible from inside the enclave therefore they need to be statically linked from before. 

Is this correct? if so, is there a way to do it ?

Thank you all in advance

**Comment by guzongmin** [comment]
You do not need to static link the application. You can follow the demo https://github.com/occlum/occlum/tree/master/demos/hello_c to put your application into Occlum trusted file system. If you link crypto libs, you need to put them into the file system too.

**Comment by guzongmin** [comment]
No more discussions, close it.
