### ISSUE TITLE
[BUG] Cannot build correct release enclave

### ISSUE THREAD

**Issue by liqinggd** [occlum/occlum#249]
# Describe the bug
I have changed the `metadata.debuggable` in Occlum.json to `false`,  and sign a release signature, but the enclave cannot run in the release mode.

# To reproduce
1. change the  `metadata.debuggable` in Occlum.json to `false`
2. Buid and sign the enclave with a valid signature.
3. Run the enclave

# Expected behavior
The enclave runs correctly in release mode.

# Logs
No

# Environment

- HW: SGX1,
- OS: Ubuntu18.04
- Occlum version: 0.18.0

# Additional context

# Possible solution/Implementation
I think this is because the code in 'tools/occlum' bash script is wrong
```
if [ "`get_enclave_debuggable_flag`" == "False" ]; then
        export OCCLUM_RELEASE_ENCLAVE=1
fi
```
The description in README is **lower case**, but the code is **upper case**, I suggest to allow both.

**Comment by liqinggd** [comment]
Moreover,  to find the real problem quickly,  we should print the error code if `sgx_create_enclave` failed.

**Comment by jessehui** [comment]
Thank you for pointing this out. I think this bug is introduced when we remove all python out of the `tools/occlum` script. I will fix this soon.

**Comment by jessehui** [comment]
This should be fixed by https://github.com/occlum/occlum/pull/252.
