### ISSUE TITLE
[BUG]Can't run java on occlum

### ISSUE THREAD

**Issue by lz18064638846** [occlum/occlum#259]
# Can't run java on occlum
I want to run jvm on enclave so I turn to occlum but only find out it cannot work.
I run java demo in the latest docker(occlum/occlum:0.18.0-ubuntu18.04)
I build the class file of helloworld and run the script run_java_on_occlum.sh hello
After a long time, hint a bug:
/opt/occlum/build/bin/occlum: line 216:   779 Illegal instruction     (core dumped) RUST_BACKTRACE=1 "$instance_dir/build/bin/occlum-run" "$@"
Please help me fix this bug, thanks.

**Comment by guzongmin** [comment]
@lz18064638846 We released 0.18.1 today. It fixed some bugs in 0.18.0. And the CI shows the JAVA hello world works in Occlum 0.18.1. Can you please try it?

**Comment by jessehui** [comment]
@lz18064638846 Illegal instructions could be related to RDFSBASE instructions. Please make sure you are using a kernel with this supported or you can install the kernel module here:https://github.com/occlum/enable_rdfsbase.  You can check if these instructions are supported with the tools in this patch https://github.com/occlum/occlum/pull/165/files .

**Comment by lz18064638846** [comment]
> @lz18064638846 We released 0.18.1 today. It fixed some bugs in 0.18.0. And the CI shows the JAVA hello world works in Occlum 0.18.1. Can you please try it?

Thanks alot, 0.18.1 work properly.
