### ISSUE TITLE
Is there a mailing list or chat for Occlum?

### ISSUE THREAD

**Issue by flxflx** [occlum/occlum#261]
Hi,
we recently tried Occlum and are quite fond of it - great work! Is there a way to get in touch, e.g., a mailing list or a chat room? 

Cheers,

Felix (Edgeless Systems)

**Comment by guzongmin** [comment]
Occlum has a slack page, but it is not really used by anyone. You can send email to me (zongmin.gzm@antgroup.com).

**Comment by flxflx** [comment]
Thanks!
