### ISSUE TITLE
Trace the status of file system syscalls

### ISSUE THREAD

**Issue by wangrunji0408** [occlum/occlum#28]
| Status | Meaning |
|-------|---------|
| ✅ | Tested |
| ⚠️ | Need Test |
| 🐞 | Has Bug |
| ❌ | To Do |

| Id | Syscall | Status | Note |
|---|--------|-------|------|
| 0 | **SYS_READ**   | ✅    |                     |
| 1 | **SYS_WRITE**  | ✅    |                     |
| 2| **SYS_OPEN**   | ✅    |             |
| 3| **SYS_CLOSE**  | ✅    |                     |
|4| **SYS_STAT**   | ✅    |            |
|5| **SYS_FSTAT**  | ✅    |            |
|6| **SYS_LSTAT**  | ⚠️    |            |
|7| **SYS_POLL**   | ❌   |   |
|8| **SYS_LSEEK**  | ✅    |                     |
|16| **SYS_IOCTL**  | ❌    |                     |
|17| **SYS_PREAD64**  | ✅    |                     |
|18| **SYS_PWRITE64**  | ✅    |                     |
|19| **SYS_READV**  | ✅    |                     |
|20| **SYS_WRITEV** | ✅    |                     |
|21| **SYS_ACCESS** | ❌    |                     |
|22| **SYS_PIPE**  | ✅    |  |
|32| **SYS_DUP**   | ✅    |                     |
|33| **SYS_DUP2**   | ✅    |                     |
|72| **SYS_FCNTL**  | ❌   |                     |
|73| **SYS_FLOCK**  | ❌   |                     |
|74| **SYS_FSYNC**  | ⚠️    |                     |
|75| **SYS_FDATASYNC**  | ⚠️    |                     |
|76| **SYS_TRUNC**  | ✅    |                     |
|77| **SYS_FTRUNC** | ✅    |                     |
|78| **SYS_GETDENTS** | ❌    |                     |
|79| **SYS_GETCWD** | ✅    |                     |
|80| **SYS_CHDIR**  | ✅    |                     |
|81| **SYS_FCHDIR**  | ❌    |                     |
|82| **SYS_RENAME** | ✅    |                     |
|83| **SYS_MKDIR**  | ✅    |                     |
|84| **SYS_RMDIR**  | ✅    |                     |
|85| **SYS_CREAT**  | ❌    |                     |
|86| **SYS_LINK**   | ✅    |                     |
|87| **SYS_UNLINK** | ✅    |                     |
|88| **SYS_SYMLINK** | ❌    |                     |
|89| **SYS_READLINK** | ❌    |                     |
|90| **SYS_CHMOD** | ❌    |                     |
|91| **SYS_FCHMOD** | ❌    |                     |
|92| **SYS_CHOWN** | ❌    |                     |
|93| **SYS_FCHOWN** | ❌    |                     |
|94| **SYS_LCHOWN** | ❌    |                     |
|133| **SYS_MKNOD**  | ❌    |                     |
|136| **SYS_USTAT**  | ❌    |                     |
|137| **SYS_STATFS**  | ❌    |                     |
|138| **SYS_FSTATFS**  | ❌    |                     |
|139| **SYS_SYSFS**  | ❌    |                     |
|162| **SYS_SYNC**   | ⚠️    |                     |
|217| **SYS_GETDENT64**   | ✅    |                     |
|292| **SYS_DUP3**   | ✅    |                     |
|293| **SYS_PIPE2**  | ✅    |  |

**Comment by tatetian** [comment]
This is cool. We should have a table like this for all system calls.
