### ISSUE TITLE
[BUG] SGX protected file I/O error when open file

### ISSUE THREAD

**Issue by jxiao1** [occlum/occlum#296]
# Describe the bug
It has happened when I just try to open a file (in libloading FFI library), and it randomly happened, not every time.  Something like Occlum has not taken care of the  EAGAIN error from the open function in SGK SDK.

# To reproduce
I don't know how to reproduce this bug, but it happens in my current environment.  A doubt thing is the log4rs will keep check the log configuration file for any changes each 30s.

# Expected behavior
Should Alway open a file successfully when it exists.

# Logs
[2020-12-29T00:13:30.316Z][DEBUG][T1][#2246][···Write] write: fd: 6
[2020-12-29T00:13:30.316Z][DEBUG][T1][#2247][····Open] openat: fs_path: FsPath { Absolute("/opt/plugins/libplugin_cplusplus_example_1.0.0_0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF.so") }, flags: 0o2000000, mode: 0o0
[2020-12-29T00:13:30.316Z][DEBUG][T1][#2247][····Open] lookup_inode_follow: cwd: "/", path: "/opt/plugins/libplugin_cplusplus_example_1.0.0_0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF.so"
[2020-12-29T00:13:30.316Z][ERROR][T1][#2247][····Open] SGX protected file I/O error: EWOULDBLOCK (#41, Unknown error): Resource deadlock avoided (os error: 11)
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /root/occlum/deps/sefs/rcore-fs-unionfs/src/lib.rs:845:18
stack backtrace:
   0: <sgx_tstd::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
             at library/core/src/fmt/mod.rs:1080
   2: sgx_tstd::io::Write::write_fmt
   3: sgx_tstd::panicking::default_panic_handler
   4: sgx_tstd::panicking::rust_panic_with_hook
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
             at library/core/src/panicking.rs:85
   7: core::panicking::panic
             at library/core/src/panicking.rs:50
   8: <rcore_fs_unionfs::UnionINode as rcore_fs::vfs::INode>::find
   9: rcore_fs_mountfs::MNode::find
  10: <rcore_fs_mountfs::MNode as rcore_fs::vfs::INode>::find
  11: rcore_fs::vfs::INode::lookup_follow
  12: occlum_libos_core_rs::fs::fs_view::FsView::lookup_inode
  13: occlum_libos_core_rs::fs::fs_view::FsView::open_file
  14: occlum_libos_core_rs::fs::file_ops::open::do_openat
  15: occlum_libos_core_rs::fs::syscalls::do_openat
  16: occlum_libos_core_rs::syscall::dispatch_syscall
  17: occlum_libos_core_rs::syscall::do_syscall
  18: occlum_syscall
  19: <unknown> 

And another similar case in the same place:
[2020-12-29T06:34:01.289Z][DEBUG][T1][#2896][····Open] openat: fs_path: FsPath { Absolute("/etc/certs/enclave_client_cert.pem") }, flags: 0o2000000, mode: 0o0
[2020-12-29T06:34:01.289Z][DEBUG][T1][#2896][····Open] lookup_inode_follow: cwd: "/", path: "/etc/certs/enclave_client_cert.pem"
[2020-12-29T06:34:01.289Z][ERROR][T1][#2896][····Open] SGX protected file I/O error: EWOULDBLOCK (#41, Unknown error): Resource deadlock avoided (os error: 11)
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /root/occlum/deps/sefs/rcore-fs-unionfs/src/lib.rs:845:18
stack backtrace:
   0: <sgx_tstd::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
             at library/core/src/fmt/mod.rs:1080
   2: sgx_tstd::io::Write::write_fmt
   3: sgx_tstd::panicking::default_panic_handler
   4: sgx_tstd::panicking::rust_panic_with_hook
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
             at library/core/src/panicking.rs:85
   7: core::panicking::panic
             at library/core/src/panicking.rs:50
   8: <rcore_fs_unionfs::UnionINode as rcore_fs::vfs::INode>::find
   9: rcore_fs_mountfs::MNode::find
  10: <rcore_fs_mountfs::MNode as rcore_fs::vfs::INode>::find
  11: rcore_fs::vfs::INode::lookup_follow
  12: occlum_libos_core_rs::fs::fs_view::FsView::lookup_inode
  13: occlum_libos_core_rs::fs::fs_view::FsView::open_file
  14: occlum_libos_core_rs::fs::file_ops::open::do_openat
  15: occlum_libos_core_rs::fs::syscalls::do_openat
  16: occlum_libos_core_rs::syscall::dispatch_syscall
  17: occlum_libos_core_rs::syscall::do_syscall
  18: occlum_syscall
  19: <unknown>

# Environment

- HW: SGX1
- OS: Ubuntu docker on Alios
- Occlum version: 0.19.0

# Possible solution/Implementation
May try some times when fail to open a file and the error code is EAGAIN

**Comment by jxiao1** [comment]
Some more inputs:  I have two occlum processes in the host and the same files will be opened in these two processes.

**Comment by jxiao1** [comment]
OK,  I found it's my fault,  I removed the first occlum_instance directory and recreate a new one(with the same files) when I start the second process,  I have not seen the problem above if I use another independent occlum_instance directory.

**Comment by guzongmin** [comment]
So the issue is: Occlum needs to return a more clear error message when the user runs "occlum run" twice with a single instance.
