### ISSUE TITLE
[BUG] hostfs readdir test failure in glibc test

### ISSUE THREAD

**Issue by jessehui** [occlum/occlum#342]
# Describe the bug
Nightly-scheduled test shows that the `hostfs` test case failed stably for only glibc test (musl test works fine) on both ubuntu and centos. This only appears since `Thu, 11 Feb 2021`(https://github.com/occlum/occlum/actions/runs/557315663). Before this day, with the same code, everything is fine.

However, this can't be reproduced on the local machine. More investigation is needed.

# Logs
2021-02-15T09:17:38.1813411Z   func test_write_read - [OK]
2021-02-15T09:17:38.1814025Z   func test_rename - [OK]
2021-02-15T09:17:38.1814666Z 		ERROR:faild to read file entry in func __test_readdir at line 107 of file main.c
2021-02-15T09:17:38.1815447Z   func test_readdir - [ERR]

# Environment

- HW: [e.g. SGX1, SGX2] Simulation mode on Github machines
- OS: [e.g. Ubuntu18.04, CentOS8.1] Both ubuntu and centos image
- Occlum version: [e.g. 0.17.0] 58bddcb89dc1e047ce27707083740afd0dac38cc

# Additional context

# Possible solution/Implementation
Not obligatory, but suggest a fix/reason for the bug.

**Comment by jessehui** [comment]
Looks like the glibc version readdir didn't output all the contents of a directory. Also, the test case needs to be refined.

**Comment by liqinggd** [comment]
Current implementation for `getdents()` is not correct, for `getdents()`, the linux_dirent structure pads the `d_type` after `d_name`.
I will fix this.
