### ISSUE TITLE
Failed to make submodule in WSL2

### ISSUE THREAD

**Issue by qqbrother** [occlum/occlum#356]
I have met the same problem when I tried to "make submodule". And I have followed the suggestion from [#issues128](https://github.com/occlum/occlum/issues/128) that use the v0.13.0 branch to build the project. However, I have met another problem as follows. It seems that the default cargo version in Occlum is stable. Could anyone build occlum successfully with the v0.13.0 branch?

```
warning: unused `#[macro_use]` import
 --> /home/gudale/gudale-dev/occlum/deps/sefs/rcore-fs-ramfs/src/lib.rs:4:1
  |
4 | #[macro_use]
  | ^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

   Compiling memchr v0.1.11
   Compiling rand_os v0.1.3
   Compiling atty v0.2.14
   Compiling time v0.1.44
   Compiling dirs v1.0.5
warning: 1 warning emitted

   Compiling sgx_urts v1.1.0
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/gudale/.cargo/registry/src/github.com-1ecc6299db9ec823/sgx_urts-1.1.0/src/lib.rs:19:1
   |
19 | #![feature(ptr_offset_from)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   Compiling quote v1.0.9
error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `sgx_urts`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
Makefile:142: recipe for target 'bin/sefs-fuse' failed
make[1]: *** [bin/sefs-fuse] Error 101
Makefile:27: recipe for target 'submodule' failed
make: *** [submodule] Error 2
```

**Comment by guzongmin** [comment]
@qqbrother Can you please try the latest release? Occlum has changed a lot since 0.13.0.

**Comment by qqbrother** [comment]
> @qqbrother Can you please try the latest release? Occlum has changed a lot since 0.13.0.

Thans for your timely reply. I have tried the  latest release. There is another error as follows.

```
gudale@DESKTOP-MLH2HMS:~/gudale-dev/occlum$ make submodule
Add Git hooks that check Rust code format issues before commits and pushes
git submodule init
git submodule update  --progress
cd deps/serde-json-sgx && git apply ../serde-json-sgx.patch >/dev/null 2>&1 || git apply ../serde-json-sgx.patch -R --check
cd deps/ringbuf && git apply ../ringbuf.patch >/dev/null 2>&1 || git apply ../ringbuf.patch -R --check
GEN <=  /home/gudale/gudale-dev/occlum/build/internal/tools/protect-integrity/App/Enclave_u.c
CC <= /home/gudale/gudale-dev/occlum/build/internal/tools/protect-integrity/App/Enclave_u.o
CXX <= /home/gudale/gudale-dev/occlum/build/internal/tools/protect-integrity/App/App.o
/usr/local/bin/ld: cannot find -lsgx_urts_sim_with_se_event
collect2: error: ld returned 1 exit status
Makefile:192: recipe for target '/home/gudale/gudale-dev/occlum/build/bin/occlum-protect-integrity' failed
make[2]: *** [/home/gudale/gudale-dev/occlum/build/bin/occlum-protect-integrity] Error 1
Makefile:7: recipe for target 'all' failed
make[1]: *** [all] Error 2
Makefile:33: recipe for target 'submodule' failed
make: *** [submodule] Error 2
```
The error is same as [issues128](https://github.com/occlum/occlum/issues/128).

**Comment by guzongmin** [comment]
@qqbrother Are you using the Occlum docker image? You need to use the latest Occlum docker image too.

**Comment by qqbrother** [comment]
> @qqbrother Are you using the Occlum docker image? You need to use the latest Occlum docker image too.

I can use occlum instructions in the Occlum docker image. But I wish to use occlum outside the docker image. Should I re-build occlum in the occlum docker image?

**Comment by guzongmin** [comment]
@qqbrother If you want to build Occlum from scratch, please reference 
 the docker file: https://github.com/occlum/occlum/blob/master/tools/docker/Dockerfile.ubuntu18.04 .

**Comment by lifeng68** [comment]
> > @qqbrother Can you please try the latest release? Occlum has changed a lot since 0.13.0.
> 
> Thans for your timely reply. I have tried the latest release. There is another error as follows.
> 
> ```
> gudale@DESKTOP-MLH2HMS:~/gudale-dev/occlum$ make submodule
> Add Git hooks that check Rust code format issues before commits and pushes
> git submodule init
> git submodule update  --progress
> cd deps/serde-json-sgx && git apply ../serde-json-sgx.patch >/dev/null 2>&1 || git apply ../serde-json-sgx.patch -R --check
> cd deps/ringbuf && git apply ../ringbuf.patch >/dev/null 2>&1 || git apply ../ringbuf.patch -R --check
> GEN <=  /home/gudale/gudale-dev/occlum/build/internal/tools/protect-integrity/App/Enclave_u.c
> CC <= /home/gudale/gudale-dev/occlum/build/internal/tools/protect-integrity/App/Enclave_u.o
> CXX <= /home/gudale/gudale-dev/occlum/build/internal/tools/protect-integrity/App/App.o
> /usr/local/bin/ld: cannot find -lsgx_urts_sim_with_se_event
> collect2: error: ld returned 1 exit status
> Makefile:192: recipe for target '/home/gudale/gudale-dev/occlum/build/bin/occlum-protect-integrity' failed
> make[2]: *** [/home/gudale/gudale-dev/occlum/build/bin/occlum-protect-integrity] Error 1
> Makefile:7: recipe for target 'all' failed
> make[1]: *** [all] Error 2
> Makefile:33: recipe for target 'submodule' failed
> make: *** [submodule] Error 2
> ```
> 
> The error is same as [issues128](https://github.com/occlum/occlum/issues/128).

@guzongmin I got the same error with the latest main branch. cannot find -lsgx_urts_sim_with_se_event

**Comment by guzongmin** [comment]
> > > @qqbrother Can you please try the latest release? Occlum has changed a lot since 0.13.0.
> > 
> > 
> > Thans for your timely reply. I have tried the latest release. There is another error as follows.
> > ```
> > gudale@DESKTOP-MLH2HMS:~/gudale-dev/occlum$ make submodule
> > Add Git hooks that check Rust code format issues before commits and pushes
> > git submodule init
> > git submodule update  --progress
> > cd deps/serde-json-sgx && git apply ../serde-json-sgx.patch >/dev/null 2>&1 || git apply ../serde-json-sgx.patch -R --check
> > cd deps/ringbuf && git apply ../ringbuf.patch >/dev/null 2>&1 || git apply ../ringbuf.patch -R --check
> > GEN <=  /home/gudale/gudale-dev/occlum/build/internal/tools/protect-integrity/App/Enclave_u.c
> > CC <= /home/gudale/gudale-dev/occlum/build/internal/tools/protect-integrity/App/Enclave_u.o
> > CXX <= /home/gudale/gudale-dev/occlum/build/internal/tools/protect-integrity/App/App.o
> > /usr/local/bin/ld: cannot find -lsgx_urts_sim_with_se_event
> > collect2: error: ld returned 1 exit status
> > Makefile:192: recipe for target '/home/gudale/gudale-dev/occlum/build/bin/occlum-protect-integrity' failed
> > make[2]: *** [/home/gudale/gudale-dev/occlum/build/bin/occlum-protect-integrity] Error 1
> > Makefile:7: recipe for target 'all' failed
> > make[1]: *** [all] Error 2
> > Makefile:33: recipe for target 'submodule' failed
> > make: *** [submodule] Error 2
> > ```
> > 
> > 
> > The error is same as [issues128](https://github.com/occlum/occlum/issues/128).
> 
> @guzongmin I got the same error with the latest main branch. cannot find -lsgx_urts_sim_with_se_event

Seems you are not using Occlum aware SGX SDK. Can you please follow  https://github.com/occlum/occlum/blob/master/tools/docker/Dockerfile.ubuntu18.04 to setup the environment?

**Comment by lifeng68** [comment]
> > > > @qqbrother Can you please try the latest release? Occlum has changed a lot since 0.13.0.
> > > 
> > > 
> > > Thans for your timely reply. I have tried the latest release. There is another error as follows.
> > > ```
> > > gudale@DESKTOP-MLH2HMS:~/gudale-dev/occlum$ make submodule
> > > Add Git hooks that check Rust code format issues before commits and pushes
> > > git submodule init
> > > git submodule update  --progress
> > > cd deps/serde-json-sgx && git apply ../serde-json-sgx.patch >/dev/null 2>&1 || git apply ../serde-json-sgx.patch -R --check
> > > cd deps/ringbuf && git apply ../ringbuf.patch >/dev/null 2>&1 || git apply ../ringbuf.patch -R --check
> > > GEN <=  /home/gudale/gudale-dev/occlum/build/internal/tools/protect-integrity/App/Enclave_u.c
> > > CC <= /home/gudale/gudale-dev/occlum/build/internal/tools/protect-integrity/App/Enclave_u.o
> > > CXX <= /home/gudale/gudale-dev/occlum/build/internal/tools/protect-integrity/App/App.o
> > > /usr/local/bin/ld: cannot find -lsgx_urts_sim_with_se_event
> > > collect2: error: ld returned 1 exit status
> > > Makefile:192: recipe for target '/home/gudale/gudale-dev/occlum/build/bin/occlum-protect-integrity' failed
> > > make[2]: *** [/home/gudale/gudale-dev/occlum/build/bin/occlum-protect-integrity] Error 1
> > > Makefile:7: recipe for target 'all' failed
> > > make[1]: *** [all] Error 2
> > > Makefile:33: recipe for target 'submodule' failed
> > > make: *** [submodule] Error 2
> > > ```
> > > 
> > > 
> > > The error is same as [issues128](https://github.com/occlum/occlum/issues/128).
> > 
> > 
> > @guzongmin I got the same error with the latest main branch. cannot find -lsgx_urts_sim_with_se_event
> 
> Seems you are not using Occlum aware SGX SDK. Can you please follow https://github.com/occlum/occlum/blob/master/tools/docker/Dockerfile.ubuntu18.04 to setup the environment?

@guzongmin I am using the ubuntu 20.04 distro. And i found the steps in https://github.com/occlum/occlum/blob/master/tools/docker/Dockerfile.ubuntu18.04,  add the repo repository for 18.04.
`    echo 'deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu bionic main' | tee /etc/apt/sources.list.d/intel-sgx.list &&\`

Should I update the repo repository for my ubuntu 20.04? 
https://download.01.org/intel-sgx/latest/linux-latest/docs/Intel_SGX_Installation_Guide_Linux_2.13_Open_Source.pdf 

Do you tested occlum on ubuntu 20.04?

**Comment by guzongmin** [comment]
> > > > > @qqbrother Can you please try the latest release? Occlum has changed a lot since 0.13.0.
> > > > 
> > > > 
> > > > Thans for your timely reply. I have tried the latest release. There is another error as follows.
> > > > ```
> > > > gudale@DESKTOP-MLH2HMS:~/gudale-dev/occlum$ make submodule
> > > > Add Git hooks that check Rust code format issues before commits and pushes
> > > > git submodule init
> > > > git submodule update  --progress
> > > > cd deps/serde-json-sgx && git apply ../serde-json-sgx.patch >/dev/null 2>&1 || git apply ../serde-json-sgx.patch -R --check
> > > > cd deps/ringbuf && git apply ../ringbuf.patch >/dev/null 2>&1 || git apply ../ringbuf.patch -R --check
> > > > GEN <=  /home/gudale/gudale-dev/occlum/build/internal/tools/protect-integrity/App/Enclave_u.c
> > > > CC <= /home/gudale/gudale-dev/occlum/build/internal/tools/protect-integrity/App/Enclave_u.o
> > > > CXX <= /home/gudale/gudale-dev/occlum/build/internal/tools/protect-integrity/App/App.o
> > > > /usr/local/bin/ld: cannot find -lsgx_urts_sim_with_se_event
> > > > collect2: error: ld returned 1 exit status
> > > > Makefile:192: recipe for target '/home/gudale/gudale-dev/occlum/build/bin/occlum-protect-integrity' failed
> > > > make[2]: *** [/home/gudale/gudale-dev/occlum/build/bin/occlum-protect-integrity] Error 1
> > > > Makefile:7: recipe for target 'all' failed
> > > > make[1]: *** [all] Error 2
> > > > Makefile:33: recipe for target 'submodule' failed
> > > > make: *** [submodule] Error 2
> > > > ```
> > > > 
> > > > 
> > > > The error is same as [issues128](https://github.com/occlum/occlum/issues/128).
> > > 
> > > 
> > > @guzongmin I got the same error with the latest main branch. cannot find -lsgx_urts_sim_with_se_event
> > 
> > 
> > Seems you are not using Occlum aware SGX SDK. Can you please follow https://github.com/occlum/occlum/blob/master/tools/docker/Dockerfile.ubuntu18.04 to setup the environment?
> 
> @guzongmin I am using the ubuntu 20.04 distro. And i found the steps in https://github.com/occlum/occlum/blob/master/tools/docker/Dockerfile.ubuntu18.04, add the repo repository for 18.04.
> ` echo 'deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu bionic main' | tee /etc/apt/sources.list.d/intel-sgx.list &&\`
> 
> Should I update the repo repository for my ubuntu 20.04?
> https://download.01.org/intel-sgx/latest/linux-latest/docs/Intel_SGX_Installation_Guide_Linux_2.13_Open_Source.pdf
> 
> Do you tested occlum on ubuntu 20.04?

Ubuntu 20.04 is not tested yet.

**Comment by qqbrother** [comment]
> @qqbrother If you want to build Occlum from scratch, please reference
> the docker file: https://github.com/occlum/occlum/blob/master/tools/docker/Dockerfile.ubuntu18.04 .

I‘ve solved the above problem by referencing’ the latest [Dockerfile.ubuntu 18.04](https://github.com/occlum/occlum/blob/master/tools/docker/Dockerfile.ubuntu18.04). However, there is another error as follows when I execute the final instruction "make install". I found that the dependency versions of sgx_sdk are different between the latest [Dockerfile](https://github.com/occlum/occlum/blob/master/tools/docker/Dockerfile.ubuntu18.04) (master branch) and the [ Dockerfile of occlum-v0.20.0](https://github.com/occlum/occlum/blob/0.20.0/tools/docker/Dockerfile.ubuntu18.04). The dependency version of sgx_sdk of latest is sgx_2.13_for_occlum, while the older is sgx_2.11_for_occlum.

```
  = note: /usr/local/bin/ld: /usr/lib/x86_64-linux-gnu/libsgx_pce_logic.so: undefined reference to `sgx_get_metadata'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `occlum_exec`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: linking with `cc` failed: exit code: 1
```
Did anyone meet this problem?

**Comment by guzongmin** [comment]
> > @qqbrother If you want to build Occlum from scratch, please reference
> > the docker file: https://github.com/occlum/occlum/blob/master/tools/docker/Dockerfile.ubuntu18.04 .
> 
> I‘ve solved the above problem by referencing’ the latest [Dockerfile.ubuntu 18.04](https://github.com/occlum/occlum/blob/master/tools/docker/Dockerfile.ubuntu18.04). However, there is another error as follows when I execute the final instruction "make install". I found that the dependency versions of sgx_sdk are different between the [latest Dockerfile](https://github.com/occlum/occlum/blob/master/tools/docker/Dockerfile.ubuntu18.04) (master branch) and the [ Dockerfile of occlum-v0.20.0](https://github.com/occlum/occlum/blob/0.20.0/tools/docker/Dockerfile.ubuntu18.04). The dependency version of sgx_sdk of latest is sgx_2.13_for_occlum, while the older is sgx_2.11_for_occlum.
> 
> ```
>   = note: /usr/local/bin/ld: /usr/lib/x86_64-linux-gnu/libsgx_pce_logic.so: undefined reference to `sgx_get_metadata'
>           collect2: error: ld returned 1 exit status
>           
> 
> error: aborting due to previous error
> 
> error: could not compile `occlum_exec`.
> 
> To learn more, run the command again with --verbose.
> warning: build failed, waiting for other jobs to finish...
> error: linking with `cc` failed: exit code: 1
> ```
> 
> Did anyone meet this problem?

Occlum 0.21.0 release upgrade the SGX SDK to 2.13. Please use the exactly SGX SDK 2.13 for Occlum 0.21.0, because we do not test other combinations.

**Comment by qqbrother** [comment]
Thanks! I have built the occlum successfully after I used Ubuntu 20.04 server instead of WSL2. The reason is that WSL2 cannot support some service of SGX (i.e., aesmd, WSL can not use "/sbin/initctl" or systemctl instructions to start "aesmd" service).

**Comment by qqbrother** [comment]
Thanks! I have built the occlum successfully after I used Ubuntu 20.04 server instead of WSL2. The reason is that WSL2 cannot support some service of SGX (i.e., aesmd, WSL can not use "/sbin/initctl" or systemctl instructions to start "aesmd" service).
