### ISSUE TITLE
[BUG]: d_type always is 0 when the file is a regular file or a directory

### ISSUE THREAD

**Issue by haosanzi** [occlum/occlum#371]
In /opt/test, we have several dynamic library files. 

```
dir = opendir("/opt/test")
ptr = readdir(dir)
```
When the above code is executed in occlum, we find that whether the file is a regular file or a directory, `ptr->d_type` always is 0.

We use the following shell to run our application:
```
# 1. Init Occlum Workspace
rm -rf occlum_workspace
mkdir occlum_workspace
cd occlum_workspace
occlum init

# 2. Copy files into Occlum Workspace and Build
cp ../server image/bin

mkdir -p image/opt
cp -rf /opt/test  image/opt

occlum build

# 3. Run the https_server
occlum run /bin/server
```

# Expected behavior
ptr->d_type is different according to different file type.

# Logs
If applicable, add logs to help explain your problem.
Wed Dec 31 23:59:22 UTC 1969: [ERROR] ptr->d_name is ., ptr->d_type is 0
Wed Dec 31 23:59:22 UTC 1969: [ERROR] ptr->d_name is .., ptr->d_type is 0
Wed Dec 31 23:59:22 UTC 1969: [ERROR] ptr->d_name is libtest.so, ptr->d_type is 0

# Environment
- HW: [SGX1] 
- OS: [Ubuntu18.04]
- Occlum version: [e.g. 0.21.0]
- gcc

**Comment by guzongmin** [comment]
Reference https://www.gnu.org/software/libc/manual/html_node/Directory-Entries.html Occlum should return DT_DIR or DT_REG in the above case. But the current implementation returns DT_UNKNOWN. Is it any impact to your usage?

**Comment by liqinggd** [comment]
Hi, this is a known limitation of `getdents` syscall, it returns a fake d_ino and d_type, the reason is that the current SEFS does not support it.

**Comment by haosanzi** [comment]
@guzongmin We can use other methods to work around this bug.  However please fix it as soon as possible
