### ISSUE TITLE
Run Python script with Occlum

### ISSUE THREAD

**Issue by Lili0820** [occlum/occlum#373]
I want to run Python with Occlum, and I pull the docker of Occlum. 

When I run with `occlum run /usr/bin/python test.py`, there is a error message "failed to boot up LibOS: EACCES (#13, Permission denied): program path is NOT a valid entry point [line = 303, file = src/entry.rs]  [ERROR] occlum-pal: occlum_ecall_new_process returns EACCES (line 152, file src/pal_api.c) ". 

And I want to know what's wrong with it.

**Comment by guzongmin** [comment]
@Lili0820 This is the demo of python https://github.com/occlum/occlum/tree/master/demos/python
I think the only reason is you do not add "/usr/bin/" into entry_points of the Occlum.json file.

**Comment by Lili0820** [comment]
Thanks. But I still get the error as follows:
![2021-03-25 10-20-16屏幕截图](https://user-images.githubusercontent.com/17015738/112409098-d927d380-8d53-11eb-9749-879dc2d8b9c2.png)

And `test.py` is a simple example for printing "hello world".

**Comment by guzongmin** [comment]
@Lili0820 Can you please use the python image in the Occlum demo? Or you simply add your script into the existing python demo. I think the issue of your case is: The /bin/python3.6 is not Position Independent Executables (PIE).

**Comment by Lili0820** [comment]
Because I'd like to integrate our existing project written in python3.6 into Occlum so that I want to test the python3.6 with Occlum. Do you mean that Occlum can only run with the python image given in the demo?

**Comment by guzongmin** [comment]
I mean you should rebuild the python3.6 with PIE compile&link options. Another solution is: Get the python3.6 from alpine image.
I think the easy way is to use python3.7 in the Occlum python demo.

**Comment by Lili0820** [comment]
OK. I have solved it. Thank a lot!

**Comment by Klein920116** [comment]
> OK. I have solved it. Thank a lot!

Could you please paste your demo code here? I have encountered the same problem and bother me two days.
