### ISSUE TITLE
Sealing data support

### ISSUE THREAD

**Issue by Lili0820** [occlum/occlum#378]
Does Occlum have the support of sealing data like the sgx_seal_data_ex() SDK function? 
And I want to sealing some data like a key pair when creating the enclave and use the sealing data in the enclave later. Can it be implemented with Occlum?

**Comment by guzongmin** [comment]
@Lili0820 When you save any data as a file inside Occlum, Occlum will seal it before saving it on the OS file system. So you already get the capability.

**Comment by Lili0820** [comment]
OK. I see. Thanks a lot.

**Comment by qq296776435** [comment]
> @Lili0820 When you save any data as a file inside Occlum, Occlum will seal it before saving it on the OS file system. So you already get the capability.

Could u plz show the corresponding position of the code?
