### ISSUE TITLE
Support Bash Script in Occlum

### ISSUE THREAD

**Issue by jessehui** [occlum/occlum#380]
- [x] Support most of the Bash script functionality on native Linux without `fork` syscall

- [x] Support `posix_spawn_file_actions_addopen/close/dup` for child process file handling

- [x] Support basic Bash script in Occlum

- [x] Support `execve` syscall to support Bash builtin function `exec`

- [x] Support `posix_spawnattr_setflags` and `posix_spawnattr_setsigmask` to handle sigmask in child process for some advanced usage

**Comment by guzongmin** [comment]
Task finished
