### ISSUE TITLE
failed to boot up LibOS: EINVAL

### ISSUE THREAD

**Issue by srieyulianti** [occlum/occlum#397]
# Describe the bug
failed to boot up LibOS: EINVAL (#22, Invalid argument): program path must be absolute [line = 278, file = src/entry.rs]
[ERROR] occlum-pal: occlum_ecall_new_process returns EINVAL (line 103, file src/pal_api.c)

# To reproduce
Build the container,
     1. docker run -it --device /dev/sgx occlum/occlum:0.20.0-ubuntu18.04
     2. Inside the container, running one of the demos work fine
     3. The application image is successfully created
     4. Occlum build is successfully running
The error comes when running "occlum run bin/App" which does not show the expected result. When running "OCCLUM_LEVEL_LOG=trace occlum run bin/App", the above errors show. 

# Expected behavior
While running "occlum run bin/App", the expected result below should be shown:
[+] Server test
[+] Waiting for connection...
The simulation has been successfully performed when using SGX-SDK enclave.

# Environment
- OS: Ubuntu18.04
- Occlum version: 0.20.0
CPU Info:
Intel(R) Xeon(R) E-2288G CPU @ 3.70GHz

BIOS Info:
BIOS Information
        Vendor: Microsoft Corporation
        Version: Hyper-V UEFI Release v4.1
        Release Date: 10/27/2020
        ROM Size: 64 kB
        Characteristics:
                BIOS characteristics not supported
                ACPI is supported
                Targeted content distribution is supported
                UEFI is supported
                System is a virtual machine
        BIOS Revision: 4.1

Linux Firmware version:
linux-firmware/bionic-updates 1.173.20 all

OS Version:
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"

Hi Occlum team,

Do you have any idea what does the error refer to?

Thanks

**Comment by guzongmin** [comment]
You should run "occlum run /bin/App", if you copy the App into image/bin/ folder
The reason is: Occlum need to know where is the App, "bin/App" is relative path. It could be anywhere.

**Comment by srieyulianti** [comment]
Hi @guzongmin ,

The problem now has been solved when I add /.

Thanks for the solution
