### ISSUE TITLE
[BUG] getUsername of com.sun.security.auth.module.UnixSystem returns the null

### ISSUE THREAD

**Issue by yuanwu2017** [occlum/occlum#402]
# To reproduce
java Hello.java
./run_java_on_occlum_glibc.sh
[test_java_system.zip](https://github.com/occlum/occlum/files/6316212/test_java_system.zip)

**Comment by guzongmin** [comment]
This application is using an unsupported syscall: Getgroups
There is a quick workaround:
[getgroups.txt](https://github.com/occlum/occlum/files/6323219/getgroups.txt)

The official fix will be available soon.
