### ISSUE TITLE
[BUG] getaddrinfo returns "Device or resource busy" when running under glibc

### ISSUE THREAD

**Issue by Nirusu** [occlum/occlum#415]
# Describe the bug
When running an application not specifically recompiled for Occlum (using musl), getaddrinfo does not seem to work correctly. 

# To reproduce
1. Create some C-Code using getaddrinfo and compile it with gcc as you normally would.
I used the following code for my test: https://gist.github.com/Nirusu/fcff7736f33ed31956dc99cb9290debd
2.  Compile with gcc running the Occlum 0.22.0 Docker container: `gcc -o dnstest-gcc dnstest.c`
3. Create a new Occlum image: `occlum new dns-test`
4. Create `resolv.conf` for external resolving: `echo -e "nameserver 8.8.8.8\nnameserver 8.8.4.4" > ./dns-test/image/etc/resolv.conf`
5. Copy compiled file over to Occlum image: `cp dnstest-gcc ./dns-test/image/bin/dnstest-gcc`
6. Build Occlum image: `occlum build`
7. Run the application: `occlum run /bin/dnstest-gcc`
8. You receive the following error message: `getaddrinfo: Device or resource busy`

# Expected behavior
dnstest-gcc should output the resolved DNS adresses of `google.com`, as it does when running under the host system or how it actually does when compiled with `occlum-gcc`:

```
# occlum run /bin/dnstest-occlum-gcc
hostname: lhr25s31-in-f4.1e100.net
hostname: lhr25s31-in-f4.1e100.net
hostname: lhr25s31-in-x04.1e100.net
hostname: lhr25s31-in-x04.1e100.net
```

# Logs
Can be found here:
https://gist.github.com/Nirusu/6eae085426f78fedb607a391a569e0f1

# Environment

- HW: SGX1 (Azure Confidential Computing VM)
- OS: Ubuntu 18.04
- Occlum version: 0.22.0 (Docker Ubuntu 18.04 image)

# Additional context
It would also be nice to see an automatic solution for https://github.com/occlum/occlum/issues/202 in the future, as having to manually create `/etc/resolv.conf` for external DNS resolution is confusing if you do not know you have to do this.

**Comment by guzongmin** [comment]
@Nirusu I have reproduced this issue. Thanks for your excellent report.
The root cause is: The Sendmmsg system call is not implemented in Occlum yet.

We will add Sendmmsg soon. Before that, you can use the musl version. I have tested the musl version, and it works well.

About issue #202, I will draft an RFC to clarify what is the solution I expect.
