### ISSUE TITLE
fail when try to run python celery through occlum on sgx

### ISSUE THREAD

**Issue by scorpio1858** [occlum/occlum#423]
# Describe the bug
I try to run celery through occlum but got a 'function not implemented error'

# To reproduce
1. get python file ready
2. occlum build and run
3. failure occur

# Expected behavior
If it starts, following logs would occur:

 -------------- celery@IT-C02YL2UKJHD2.local v5.0.5 (singularity)
--- ***** ----- 
-- ******* ---- macOS-10.14.6-x86_64-i386-64bit 2021-04-30 11:59:26
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         tasks:0x1091b5c10
- ** ---------- .> transport:   redis://127.0.0.1:6379//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . tasks.add

[2021-04-30 11:59:27,269: INFO/MainProcess] Connected to redis://127.0.0.1:6379//
[2021-04-30 11:59:27,278: INFO/MainProcess] mingle: searching for neighbors
[2021-04-30 11:59:28,298: INFO/MainProcess] mingle: all alone
[2021-04-30 11:59:28,313: INFO/MainProcess] celery@IT-C02YL2UKJHD2.local ready.

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)

Process finished with exit code 0

# Logs
If applicable, add logs to help explain your problem.

occlum trace
![image](https://user-images.githubusercontent.com/23226534/116653527-fa668a00-a9b9-11eb-91da-38dc525c3ad0.png)

# Environment

- HW: SGX1
- OS: CentOS7.2
- Occlum version: 0.19.1

**Comment by jessehui** [comment]
@scorpio1858 Could you provide more specific steps to reproduce like which python script you are using?
We can implement fstat for pipe soon but the other two syscalls naturally does not support pipe file types and might not be the root cause of this failure. It'd be better for you to provide more details. Thank you.
