### ISSUE TITLE
Running a command line from a C script that run on Occlum enclave

### ISSUE THREAD

**Issue by srieyulianti** [occlum/occlum#427]
Hi Occlum team,

I have my C script running on an Occlum enclave. From that script, I would like to run a command line as for example:

`...
system("mkdir -p obj")
...`

When I run this command outside of the enclave. I could see a new directory obj was created. However, when I run the same command inside the enclave, I did not see any directory created. Does Occlum disallow the mechanism to run a command line from the script running inside the enclave? Or is there a way to do this scenario with Occlum?

Thanks and Regards,
Sri

**Comment by guzongmin** [comment]
@srieyulianti Occlum support busybox inside enclave. You could reference https://github.com/occlum/occlum/tree/master/demos/fish

**Comment by jessehui** [comment]
Basic shell command utilities are provided by busybox. However, there is no support for running command line from C script with `system` function call. I think we can work on that.
