### ISSUE TITLE
Support Java multiprocessing 

### ISSUE THREAD

**Issue by jessehui** [occlum/occlum#428]
This issue is used to track the issues related to enabling Java multiprocessing. More support might be needed when running different Java UTs.

- [x] support execve
- [x] support ioctl option FIONREAD for pipe
- [x] support /proc/[pid]/root fs
- [x] uds should handle the situation that first listen and then rename the socket file
- [x] support getsockopt for unix domain socket

**Comment by guzongmin** [comment]
Supported in 0.23.0
