### ISSUE TITLE
[RFC] Support execve syscall

### ISSUE THREAD

**Issue by jessehui** [occlum/occlum#429]
- Feature Name: support execve syscall
- Start Date: 2021-5-12

# Summary
[summary]: #summary
Support execve syscall in Occlum.

# Motivation
[motivation]: #motivation
`Execve` is a very important system call that is widely used by system-level applications. It usually works with fork together when creating new processes. Occlum use spawn rather than fork+exec to create a new process. But in some scenarios, execve syscall could be used alone. 

During the enablement of Java multiprocessing, we can hardcode the method of creating a new process to spawn based on:
![截屏2021-05-12 下午2 50 09](https://user-images.githubusercontent.com/13930406/117931113-5e317100-b331-11eb-8ef8-0bad23f4c148.png)

However, although it is set to use posix_spawn, it actually spawns a `spawnhelper` defined in `src/java.base/unix/native/jspawnhelper/jspawnhelper.c` and calls `execve` later to execute the real child process. Thus, `execve` becomes a "must" to enable Java multiprocessing.

What's more, shell command `exec` could also depend on this.

# Guide-level explanation
[guide-level-explanation]: #guide-level-explanation

In general, it follows the beviour of execve described in the [man page](https://man7.org/linux/man-pages/man2/execve.2.html). Besides execve a elf binary, it should also support execve a script.

# Reference-level explanation
[reference-level-explanation]: #reference-level-explanation

In native Linux, execve syscall should replace all the VM of a process and execute the new process. However, for single address space OS, we can't do that. A reasonable method is to create a new process in the existing way. And then just execute the new process in the syscall and never return. In more details:
1. `process 1` (main process) calls execve
2. OS handles this syscall and creates a new process, let's say `process 1'`, similar to spawn but in a replace way:
      - inherit the `process 1`'s parent process as its parent process
      - use the same tid and pid as `process 1` while replacing process reference and thread reference in the process table
      - close all the `close-on-exec` file and others are kept
      - the dispositions of handled signals are reset to the default; the dispositions of ignored signals are left unchanged
      - any alternate signal stack is not preserved
      - any open directory streams are closed
      - any outstanding asynchronous I/O operations are canceled
      - all `process 1`'s threads are destroyed during an execve().  Mutexes, condition variables, and other pthreads objects are not preserved.
3. after creating `process 1'`, using OCALL to run it in a host thread
4. exit the original `process 1` including terminating the thread and release the resources of process and thread based on its reference

# Rationale and alternatives
[rationale-and-alternatives]: #rationale-and-alternatives

Other options:
1. Directly destroy the VM of `process 1` and create new `process 1'` using the same VM range. And for sysret, directly point to `main` of the new process.

Seems workable, but a lot of work need to be done for more bottom-level code and must invent the new path to support this syscall.

2. After creating `process 1'`, the `process 1` doesn't exit. Instead, it waits until the `process 1'` finishes and then exit together. 

This clearly can meet the requirements that execve should never return. However, wait will still consume resources including CPU and memory which should be released and could be used by other processes.

In summary, the proposed method uses existing and similar path to simulate the behaviour of execve to reduce the effort of development and in the same, release resources as soon as possible.

# Unresolved questions
[unresolved-questions]: #unresolved-questions

- What parts of the design do you expect to resolve through the RFC process before this gets merged?
We would like us to be on the same page about whether we should create a new process and whether to wait or exit for `process 1`.

- What parts of the design do you expect to resolve through the implementation of this feature before stabilization?
The detail exit process for `process 1` which should make the application unaware of the original process' exit.

- Unresoved questions:
    - multithreaded applications when one thread calls execve, how to deal with other threads
    - during the process replacement procedure, what resources should be locked to avoid inconsistency

# Future possibilities
[future-possibilities]: #future-possibilities

If execve is supported, another important syscall `vfork` could also be added to the plan list as execve often works with fork and vfork. Since fork has some performance issue, vfork are used more nowadays. And many applications provide a vfork implementation to substitute fork. And vfork is not a `mission impossible` for single address space OS.

**Comment by guzongmin** [comment]
Is it possible that after the process 1' created and before process 1 is not destroyed, another process want to send a signal to process 1 with pid?  What is the behavior in the current design?

**Comment by jessehui** [comment]
The separation point is the time that the new `process 1'` is assigned the pid of the original `process 1`. Before the separation point, the signal will be queued to signal queue of `process 1`. After the separation point, the signal will be queued to signal queue of `process 1'`.

**Comment by guzongmin** [comment]
May need more detail about if the process 1 is the multi-thread application, what would happen?

**Comment by jessehui** [comment]
Update:
1. Use the main process's VM space and don't allocate new VM space
2. In execve, destroy all threads of the calling process and then do other stuff

**Comment by superajun-wsj** [comment]
Java supports both spawn and fork api to create a new process. We can decide it by startup parameter:
spawn: -Djdk.lang.Process.launchMechanism=posix_spawn
fork: -Djdk.lang.Process.launchMechanism=fork
and fork is Java's default way.

**Comment by jessehui** [comment]
Thanks @superajun-wsj . Tests have shown that once we support execve, java multiprocess can run without modification with `-Djdk.lang.Process.launchMechanism=posix_spawn` in Occlum. Thank you for your help!

**Comment by jessehui** [comment]
> Update:
> 
> 1. Use the main process's VM space and don't allocate new VM space
> 2. In execve, destroy all threads of the calling process and then do other stuff

Update-2:
If considering `vfork + exec` usage, since vfork doesn't create new address space (use parent process's address space), if execve also uses the same address space, the parent process will no longer exist. Thus, It is not aligned with the real situation. 

Based on Linux kernel implementation, execve also creates a new VM. 
Call trace:
```
__do_execve_file -> bprm_mm_init -> exec_binprm
```

In summary, execve should allocate new VM space.
