### ISSUE TITLE
make submodule does not work on ubuntu 20.04

### ISSUE THREAD

**Issue by lytofd** [occlum/occlum#432]
l have verified  /opt/intel/sgxsdk/SampleCode/SampleEnclave/app, but when execute make submodule  error happended as follows:
```
CXX <= /home/occlum/build/internal/tools/protect-integrity/App/App.o
/usr/bin/ld: cannot find -lsgx_urts_sim_with_se_event
```
kernel： 5.8.0-53-generic .

How to resolve it , Thanks.

**Comment by guzongmin** [comment]
@lytofd ubuntu 20.04 is not tested yet. My suggestion is: Using the ubuntu 18.04 docker image. You are able to get more information from the readme file https://github.com/occlum/occlum#how-to-use.

Another way is to create your own ubuntu 20.04 build environment by reference 18.04 docker file https://github.com/occlum/occlum/blob/master/tools/docker/Dockerfile.ubuntu18.04. If you are able to create a 20.04 docker file for Occlum, it is a great contribution. I would add your 20.04 docker file into the daily CI/CD script.

**Comment by lytofd** [comment]
> @lytofd ubuntu 20.04 is not tested yet. My suggestion is: Using the ubuntu 18.04 docker image. You are able to get more information from the readme file https://github.com/occlum/occlum#how-to-use.
> 
> Another way is to create your own ubuntu 20.04 build environment by reference 18.04 docker file https://github.com/occlum/occlum/blob/master/tools/docker/Dockerfile.ubuntu18.04. If you are able to create a 20.04 docker file for Occlum, it is a great contribution. I would add your 20.04 docker file into the daily CI/CD script.

Thanks,l'll try it.

**Comment by guzongmin** [comment]
Close this issue, since Ubuntu 20.04 would not be supported now.
