### ISSUE TITLE
docker-compose DNS names don't resolve when running java inside an occlum instance.

### ISSUE THREAD

**Issue by larsr** [occlum/occlum#433]
SUMMARY: When I run a java program in occlum inside a docker instance, the java program doesn't resolve DNS-names created by docker-compose.

---

I'm using `docker-compose` to create two docker instances named `server` and `client`.

Inside the docker containers, `host server` often resolves to 172.21.0.2 and `host client` to 172.21.0.3.  But sometimes they get other ip-addresses.  

To resolve the dns name, the docker instances use a local dns server at 127.0.0.11, set up by `docker`. It is listed in their `/etc/resolv.conf`.

However, when I run a java program inside occlum, the DNS resolution is not able to resolve `server` or `client`.  It's like it is not using the DNS-server configured in the host's `/etc/resolv.conf`.  This makes it impossible for my `client` program to contact the `server`.

Q: How can I make the occlum instance resolve DNS correctly, i.e. using the DNS settings from its environment?

Q: How does it pick a name server today?

Thanks!

**Comment by larsr** [comment]
I'm using the docker image `occlum/occlum:0.22.0-ubuntu18.04`

**Comment by guzongmin** [comment]
@larsr Thank you to report this issue. This issue is discussed in #422.
Before we make it happen, you could copy the host /etc/resolv.conf file to [instanc dir]/image/etc/resolv.conf

**Comment by guzongmin** [comment]
Occlum creates the /etc/resolv.conf for you now
https://github.com/occlum/occlum/commit/d35d98d551bea98174f88fa7b639be79af1caaa9

Enjoy it
