### ISSUE TITLE
Coredump and syscall error

### ISSUE THREAD

**Issue by pegahnikbakht** [occlum/occlum#436]
Hi,

When I run my program I get core dump and I tried to trace the program I found this error in the logs: "[SetRobustList] Error = ENOSYS (#38, Function not implemented): Unimplemented or unknown syscall [line = 897, file = src/syscall/mod.rs]". Seems like this set_robust_list is not implemented in occlum? Do you have any idea how to solve this problem? By the way my program works well in simulation mode but with the actual SGX it does not work. 

Regards,
Pegah

**Comment by guzongmin** [comment]
@pegahnikbakht SetRobustList is not implemented yet, but most of the time it is not a critical issue. As the result, you are able to run the app under simulation mode. 

Can you please provide the full trace file of the crash issue?

**Comment by pegahnikbakht** [comment]
[trace.txt](https://github.com/occlum/occlum/files/6508961/trace.txt)
This is the trace file of my program.

**Comment by guzongmin** [comment]
@pegahnikbakht The log did not have important information about the crash. So I have 4 suggestions below:
1. try to enlarge the "kernel_space_stack_size" in Occlum.json
2. try to use the latest Occlum version and try again 
3. try "occlum gdb" command instead of "occlum run", then you will get more information about the crash.
4. If you are able to share the test code, I can help to take a look.

**Comment by pegahnikbakht** [comment]
Here is the code I tried to run with occlum and sgx: 
[https://github.com/keith-cullen/FreeCoAP](url)  I would like to run this test: /test/test_proxy_http_coap with sgx
The program has some glibc libraries, I compiled it with normal gcc and copied glibc libraries to occlum_instance.

**Comment by guzongmin** [comment]
@pegahnikbakht 
Because lacking of this software background, I do not know how to use this software. 
Can you please share me a script which could be used to run the app under simulation mode?

**Comment by pegahnikbakht** [comment]
[download_build.txt](https://github.com/occlum/occlum/files/6530798/download_build.txt)
This file is for download and building the required libraries.

[run.txt](https://github.com/occlum/occlum/files/6530804/run.txt)
This one is for running the program.

**Comment by guzongmin** [comment]
@pegahnikbakht Occlum needs special glibc libraries. I updated your run.txt, and now, it works.
```
#!/bin/bash

occlum_glibc=/opt/occlum/glibc/lib/
git clone https://github.com/keith-cullen/FreeCoAP.git
cd FreeCoAP/test/test_proxy_http_coap
make

rm -rf occlum_instance
occlum new occlum_instance
cd occlum_instance

#cp /usr/local/lib/x86_64-linux-gnu/libgnutls* image/$occlum_glibc
#cp /usr/local/lib/x86_64-linux-gnu/libnettle* image/$occlum_glibc
#cp /usr/local/lib/x86_64-linux-gnu/libhogweed* image/$occlum_glibc
#cp /usr/local/lib/x86_64-linux-gnu/libgmp* image/$occlum_glibc
#cp /lib/x86_64-linux-gnu/* image/$occlum_glibc
#cp /usr/lib/x86_64-linux-gnu/* image/$occlum_glibc
#cp /usr/bin/gnutls* image/bin
cp /usr/lib/x86_64-linux-gnu/libgnutls.so.30 image/$occlum_glibc
cp /lib/x86_64-linux-gnu/libz.so.1 image/$occlum_glibc
cp /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 image/$occlum_glibc
cp /usr/lib/x86_64-linux-gnu/libidn2.so.0 image/$occlum_glibc
cp /usr/lib/x86_64-linux-gnu/libunistring.so.2 image/$occlum_glibc
cp /usr/lib/x86_64-linux-gnu/libtasn1.so.6 image/$occlum_glibc
cp /usr/lib/x86_64-linux-gnu/libnettle.so.6 image/$occlum_glibc
cp /usr/lib/x86_64-linux-gnu/libhogweed.so.4 image/$occlum_glibc
cp /usr/lib/x86_64-linux-gnu/libgmp.so.10 image/$occlum_glibc
cp /usr/lib/x86_64-linux-gnu/libffi.so.6 image/$occlum_glibc
cp /opt/occlum/glibc/lib/libdl.so.2 image/$occlum_glibc

cat <<EOF > proxy.conf
port = "12437"
max_log_level = "info"

[http_server]
trust_file = "/certs/root_client_cert.pem"
cert_file = "/certs/server_cert.pem"
key_file = "/certs/server_privkey.pem"

[coap_client]
trust_file = "/certs/root_server_cert.pem"
cert_file = "/certs/client_cert.pem"
key_file = "/certs/client_privkey.pem"
EOF

mkdir -p image/certs
cp ../proxy.conf image/
cp ../../../certs/* image/certs/
cp ../test_proxy_http_coap image/bin
occlum build --sgx-mode SIM
#occlum build
occlum run /bin/test_proxy_http_coap
```

**Comment by guzongmin** [comment]
Close it for no more active topics.
