### ISSUE TITLE
[BUG] how I use a mounted direct?

### ISSUE THREAD

**Issue by cathhuo** [occlum/occlum#440]
# Describe the bug

# To reproduce
1. 
2. 
3. 
4. 

# Expected behavior

# Logs
If applicable, add logs to help explain your problem.

# Environment

- HW: [e.g. SGX1, SGX2] 
- OS: [e.g. Ubuntu18.04, CentOS8.2]
- Occlum version: [e.g. 0.17.0]

# Additional context

# Possible solution/Implementation
Not obligatory, but suggest a fix/reason for the bug.

**Comment by guzongmin** [comment]
@cathhuo Can you please give more information about your question? Do you mean you want to mount something in Occlum FS?

**Comment by cathhuo** [comment]
> @cathhuo Can you please give more information about your question? Do you mean you want to mount something in Occlum FS?
the problem is , when I execute 'Occlum build', the data write by sqlite will be clear. how can I avoid this when I use Occlum to manage my application ? I tried ‘Occlum mount’, but It seems will not solve my problem
