### ISSUE TITLE
ias_access_key  when I run  < Remote Attestation Demo >

### ISSUE THREAD

**Issue by cathhuo** [occlum/occlum#445]
I did not find ias_access_key in 
https://api.portal.trustedservices.intel.com/developer
'''
SPID
Primary Key 
Secondary key
''''
which one is ias_access_key

**Comment by guzongmin** [comment]
Please read Intel RA document about ias_access_key. https://api.portal.trustedservices.intel.com/EPID-attestation
You need to get one for you own.

You can try the Intel SGX SDK RA demo https://github.com/intel/linux-sgx/tree/master/SampleCode/RemoteAttestation to confirm the environment is correct before using Occlum RA.

**Comment by cathhuo** [comment]
I followed your url, did not found ias_access_key.

**Comment by cathhuo** [comment]
<img width="1152" alt="aa" src="https://user-images.githubusercontent.com/52396712/119612963-1cbfbc00-be2f-11eb-9578-0f59d8f1b3bc.png">

**Comment by guzongmin** [comment]
@cathhuo You could try the "Primary key".
Actually, I have a NUC with SGX2 DCAP enabled. So I do not use EPID anymore.

**Comment by cathhuo** [comment]
I use the spid and primary key, but show some wrong  as bellow:

Remote attestation testing ...
[ERROR][/root/demos/remote_attestation/lib/src/ra_quote.cpp:106] Empty SPID or Invalid SPID hexstring length

 ---------------------
does the remote attestation demo run ?

**Comment by jxiao1** [comment]
@cathhuo, did you copied the config file "demos/remote_attestation/conf/ra_config.json" in the right place,   "./ra_config.json", or "/etc/ra_config.json"?   Of course, you should make sure that the SPID in ra_config.json is existed and right, the error code shown that your SPID is not found or is not 32bytes hexstr of the sgx_spid_t(16bytes binary)

**Comment by cathhuo** [comment]
Remote attestation testing ...
[ERROR][/root/demos/remote_attestation/lib/src/ra_ias.cpp:293] Fail to get quote report from IAS
[ERROR][/root/demos/remote_attestation/lib/src/ra_quote.cpp:188] [Function] GetEnclaveIasReport
Fail to get quote or fetch report, error code is 5040000!

**Comment by jxiao1** [comment]
@cathhuo, for the wrong SPID issue,  Intel has confirmed that there is something wrong in the IAS side,  they have fixed this problem. Please follow intel's suggestion to get the right SPID and try again.  "users that have the issue with wrong SPID need to resubscribe to Attestation Service - cancel subscription on their profile page (Cancel button on the right of subscription) and subscribe once again as before."

**Comment by cathhuo** [comment]
thx，I got the result .
