### ISSUE TITLE
Question about occlum's ra demo

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [occlum/occlum#457]
Hi, These days I have a look at Intel official ra sample (https://github.com/intel/sgx-ra-sample), and compare it with occlum's ra demo code, and I find that the difference between them is large. The Intel official ra sample has a process that does the logical of challenger and also has a process that does the process of application, but the occlum's ra demo only have a single process. I think the occlum's ra demo combine logical of application and challenger to a single process, so the compex interact of application and challanger in Intel official ra sample can skip because of no need to run the step of  Sigma protocol  between of them. And do you agree with me?

**Comment by guzongmin** [comment]
@Keepmoving-ZXY The Intel RA demo is what a regular RA process. Occlum should provide a better demo to follow the same process. It is on the plan.

**Comment by Keepmoving-ZXY** [comment]
@guzongmin So what you means is that we should build our own ra code during ra in occlum?

**Comment by guzongmin** [comment]
Occlum provide RA interface (sgx devide). User needs to write RA application with the interface. The RA application logic should be the same as Intel's demo.

**Comment by Keepmoving-ZXY** [comment]
@guzongmin And I want to ensure that the RA interface is /dev/sgx in occlum, does this ok?

**Comment by guzongmin** [comment]
> @guzongmin And I want to ensure that the RA interface is /dev/sgx in occlum, does this ok?

Yes, It is.

**Comment by Keepmoving-ZXY** [comment]
@guzongmin ok, thank you.
