### ISSUE TITLE
[BUG] futex wait hang and can't be interrupted

### ISSUE THREAD

**Issue by jessehui** [occlum/occlum#463]
# Describe the bug
futex-wait sometimes hangs and waits infinitely and can't be interrupted.

# To reproduce
When running Java UT in Occlum,  one of the threads can't exit and hang in futex-wait. It can't be interrupted and never get timeout.

# Expected behavior
All the threads exit normally.

# Environment

- HW: [e.g. SGX1, SGX2] SGX1
- OS: [e.g. Ubuntu18.04, CentOS8.2] Ubuntu18.04
- Occlum version: [e.g. 0.17.0] 0.22.0

# Additional context
The thread calling futex wait doesn't call the futex syscall in the end. Instead, in `se_event_timeout_wait`, because of `se_event` 's old_value not zero, it directly returns. Thus, it won't timeout or get interrupted (because it never calls the futex syscall on the host).

The key is the `se_event` value which should be `0` when `get_event`, add `-1` before futex syscall (host) and set to `0` after the syscall. But in the thread which never returns, the `se_event` corresponds to a very big negative value. I added some log and it shows that the `se_event` was `-1` when `get_event`. And since then, it was added `-1` each time when `wait_event_timeout` is called and never gets back to 0 and thus causes the hang.

What causes the `se_event` to `-1` when `get_event`? It turns out the `do_wait4` implementation calls`se_event_wait` (sgx-sdk) which looks like this:
```c
int se_event_wait(se_handle_t se_event)
{
    if (se_event == NULL)
        return SE_MUTEX_INVALID;

    if (__sync_fetch_and_add((int*)se_event, -1) == 0)
        syscall(__NR_futex, se_event, FUTEX_WAIT, -1, NULL, NULL, 0);

    return SE_MUTEX_SUCCESS;
}
```
And once this futex syscall is interrupted, the `se_event` has no chance to become 0 again.

Designed by sgx-sdk, signals which could interrupt this syscall are registered with `SA_RESTART` flag and would not cause `se_event` still `-1` when return.  However, the SIG64 remove this flag and once this syscall is interrupted by SIG64, this bug is triggered.

# Possible solution/Implementation
Fix will be pushed later.

**Comment by mythi** [comment]
I'm noticing something similar in my case. I'm running 0.29.5. Should the fix be included?

```
[2023-05-24T06:50:10.591Z][TRACE][T26][#12317][···Futex] Syscall { num = Futex, futex_addr = 0x7eaec001fee
8, futex_op = 137, futex_val = -1, timeout = 0, futex_new_addr = 0x0, bitset = 4294967295 }
[2023-05-24T06:50:10.591Z][DEBUG][T26][#12317][···Futex] futex_wait_bitset addr: 0x7eaec001fee8, val: -1,
timeout: None, bitset: 0xffffffff 
```

this is on a "server". The client gets an error:
```
channel: read failed Custom { kind: Other, error: reqwest::Error { kind: Body, source: hyper::Error(
Body, Error { kind: Reset(StreamId(3), PROTOCOL_ERROR, Remote) }) } }
```

**Comment by jessehui** [comment]
@mythi This bug should be long gone. I believe we have some test cases for this.

**Comment by mythi** [comment]
@jessehui yeah I noticed but the behavior I'm seeing looks very much the same. The logs just hang for `futex_wait_bitset addr` and then the client errors... I will continue debugging

**Comment by mythi** [comment]
@jessehui The error triggers consistently but I don't know how to get rid of it. My app uses 8 threads. Forcing it to 4 threads makes the problem go away but I'd need it working without the thread count override setting.

What additional info can I provide?

**Comment by jessehui** [comment]
@mythi Sorry to hear that. Please open a new issue with detailed steps to reproduce. If you can try to simplify your case, it would be much easier for us to find the reason. Thank you.
