### ISSUE TITLE
[BUG] Unknown SGX error (line 22, file src/ocalls/spawn.c)

### ISSUE THREAD

**Issue by a3213105** [occlum/occlum#469]
when i ran OpenVINO demo on ICX，there is an  error below， how can i fix this？

occlum run /bin/benchmark_app -m /model/age-gender-recognition-retail-0013.xml 
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading Inference Engine
[ INFO ] InferenceEngine:
        API version ............ 2.1
        Build .................. custom_heads/2019_R3_1c794d971cdd3c94de5ea4a6c9588eac63f4cc57
        Description ....... API
[ INFO ] Device info:
        CPU
        MKLDNNPlugin version ......... 2.1
        Build ........... custom_heads/2019_R3_1c794d971cdd3c94de5ea4a6c9588eac63f4cc57

[Step 3/11] Reading the Intermediate Representation network
[ INFO ] Loading network files
[ INFO ] Read network took 44.05 ms
[Step 4/11] Resizing network to match image sizes and given batch
[ INFO ] Network batch size: 1, precision: FP32
[Step 5/11] Configuring input of the model
[Step 6/11] Setting device configuration
[Step 7/11] Loading the model to the device
[ERROR] occlum-pal: Failed to enter the enclave to execute a LibOS thread (host tid = 116892) with error code 0x1003: Unknown SGX error (line 22, file src/ocalls/spawn.c)

**Comment by jessehui** [comment]
@a3213105 Please enlarge the `max_num_of_threads` in the Occlum.json.
Error code `0x1003` means that `The enclave is out of TCS`
