### ISSUE TITLE
[BUG] getaddrinfo still returns "Device or resource busy" when running under glibc

### ISSUE THREAD

**Issue by Nirusu** [occlum/occlum#477]
# Describe the bug
When running an application not specifically recompiled for Occlum (using musl), getaddrinfo does not seem to work correctly. 

This was already reported once in #415 and was closed with #426. While adding the sendmmsg syscall seems to be a step into the right direction, getaddrinfo() still does not seem to work correctly (but now failing at some other point).

# To reproduce
1. Create some C-Code using getaddrinfo and compile it with gcc as you normally would.
I used the following code for my test: https://gist.github.com/Nirusu/fcff7736f33ed31956dc99cb9290debd
2.  Compile with gcc running the Occlum 0.22.0 Docker container: `gcc -o dnstest-gcc dnstest.c`
3. Create a new Occlum image: `occlum new dns-test`
4. Create `resolv.conf` for external resolving: `echo -e "nameserver 8.8.8.8\nnameserver 8.8.4.4" > ./dns-test/image/etc/resolv.conf`
5. Copy compiled file over to Occlum image: `cp dnstest-gcc ./dns-test/image/bin/dnstest-gcc`
6. Build Occlum image: `cd dns-test && occlum build`
7. Run the application: `occlum run /bin/dnstest-gcc`
8. You receive the following error message: `getaddrinfo: Device or resource busy`
# Expected behavior
dnstest-gcc should output the resolved DNS adresses of `google.com`, as it does when running under the host system or how it actually does when compiled with `occlum-gcc`:

```
# occlum run /bin/dnstest-occlum-gcc
hostname: lhr25s31-in-f4.1e100.net
hostname: lhr25s31-in-f4.1e100.net
hostname: lhr25s31-in-x04.1e100.net
hostname: lhr25s31-in-x04.1e100.net
```

# Logs
Can be found here (fresh ones with Occlum 0.23.0):
https://gist.github.com/Nirusu/2b88cbbde34c007994b2e1e37fb2802b

# Environment

- HW: SGX1 (Azure Confidential Computing VM)
- OS: Ubuntu 18.04
- Occlum version: 0.23.0 (Docker Ubuntu 18.04 image)

**Comment by ClawSeven** [comment]
Hi, I have reproduced your bug and fixed it. Since this C-code program is based on glibc, several glibc-related shared objects need to be copied into your occlum instance. 
`cp /lib/x86_64-linux-gnu/{libnss_dns.so.2,libnss_files.so.2,libresolv.so.2} ./dns-test/image/opt/occlum/glibc/lib` or
`cp /opt/occlum/glibc/lib/{libnss_dns.so.2,libnss_files.so.2,libresolv.so.2} ./dns-test/image/opt/occlum/glibc/lib`
Then rebuild occlum and run it !

**Comment by ClawSeven** [comment]
If you encounter similar problem, you can check error logs.
`
[2021-06-14T16:22:13.061Z][DEBUG][T2][#71][··Openat] openat: fs_path: FsPath { Absolute("/opt/occlum/glibc/lib/libnss_files.so.2") }, flags: 0o2000000, mode: 0o0[2021-06-14T16:22:13.061Z][DEBUG][T2][#71][··Openat] lookup_inode: cwd: "/", path: "/opt/occlum/glibc/lib/libnss_files.so.2"
`
As the error log shown, libnss_files.so.2 can't be found. We strongly recommend you to copy those shared objects from "/opt/occlum/glibc/lib" in docker.

**Comment by Nirusu** [comment]
Oh, I did not notice that these calls happened _inside_ the Occlum image due to the path. I thought that was redirected to the outside or something.

Now that gets things mostly working so far, thank you!

One last thing that does not quite work yet is resolving "localhost", however. I have a /etc/hosts file in my image with:
```
127.0.0.1   localhost
```

Which I think is automatically created by `occlum create`? Yet it does not resolve correctly. Any ideas why?

**Comment by guzongmin** [comment]
@Nirusu I am not sure what is the issue. But this is the least one solution for you:  update the image/etc/hosts as you expected, or just remove it if you do not need it.

**Comment by Nirusu** [comment]
The original issue was that I thought DNS lookups with glibc are still broken, but that seems to not be the case (just copy over libnss & libresolv) to the image.

The issue I am now encoutering though is that while external lookups using an external resolver work fine, I cannot resolve localhost -> 127.0.0.1 correctly despite having the entry in `image/etc/hosts`, as it just returns "Name or service not known" (or from Go's context where I want to get DNS working: "No such host").

This might not be a bug, just not sure how I can get this fixed to get localhost -> 127.0.0.1 resolved correctly as I thought the whole purpose of `/etc/hosts` inside the image is to get this working. With musl (`occlum-gcc`, `occlum-go` etc.), this works.

**Comment by Nirusu** [comment]
Okay, so I finally figured out how to setup DNS correctly with both `localhost` and external DNS entries resolving:

Basically:

- As @ClawSeven suggested, copy `libnss_dns.so.2`, `libnss_files.so.2`, `libresolv.so.2` into your Occlum instance
- Create `/etc/resolv.conf` pointing to DNS servers used for resolving. I used Google's Public DNS servers:
```
nameserver 8.8.8.8
nameserver 8.8.4.4
```
- And the step that got `localhost` resolution working for me: Tell `libnss` to start with `/etc/hosts` (which is automatically created with `occlum new`) before contacting a DNS server by creating `/etc/nsswitch.conf` with the following lines:
```
hosts:	files dns
```

All in all, everything automated (running under the Occlum Docker image, adjust the path to your Occlum instance):
```bash
echo -e "nameserver 8.8.8.8\nnameserver 8.8.4.4" > ./occlum-instance/image/etc/resolv.conf
echo -e "hosts:	files dns" > ./occlum-instance/image/etc/nsswitch.conf
cp /opt/occlum/glibc/lib/libnss_dns.so.2 /opt/occlum/glibc/lib/libnss_files.so.2 /opt/occlum/glibc/lib/libresolv.so.2 occlum-instance/image/opt/occlum/glibc/lib/
```

Voilà, DNS works with a glibc built application :)

**Comment by doutv** [comment]
With Occlum v0.30.0:

change occlum-instance -> occlum_instance
```
echo -e "nameserver 8.8.8.8\nnameserver 8.8.4.4" > $script_dir/occlum_instance/image/etc/resolv.conf
echo -e "hosts:	files dns" > $script_dir/occlum_instance/image/etc/nsswitch.conf
cp /lib/x86_64-linux-gnu/{libnss_dns.so.2,libnss_files.so.2,libresolv.so.2} $script_dir/occlum_instance/image/opt/occlum/glibc/lib
```
