### ISSUE TITLE
Does occlum need local attestation?

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [occlum/occlum#478]
occlum let all processes run in the same sgx enclave, so I think processes that occlum run in a single workstation don't need any local attestation, because they run in the same sgx enclave, does this ok?

**Comment by guzongmin** [comment]
@Keepmoving-ZXY Local attestation used when two enclaves want to share some secret. So if you have only one enclave, then you are right, you do not need local attestation. But if you do have two enclaves, for example two Occlum instances, then you still need local attestation (If you do not want to use heavy remote attestation).

**Comment by Keepmoving-ZXY** [comment]
@guzongmin Thank you for your answer, and I want to know is there a way to integrate sgx local attestation routine (such as `sgx_dh_init_session`, `sgx_dh_responder_gen_msg1`, and so on) with python code?  Our project's main language is python code that running in the occlum.

**Comment by guzongmin** [comment]
@Keepmoving-ZXY It is a good suggestion. We are planning to provide more Local/Remote attestation support. Please be patient.

**Comment by Keepmoving-ZXY** [comment]
@guzongmin Sorry, our project leader claim that the local attestation should be okay until the end of this month, so I have to find a temporary solution.
 And I have a idea that the Occlum provide a device file named `/dev/sgx`, and local attestation can be done via `ioctl` with it. So what about write some C++ code to wrapper `ioctl` call, and compile the C++ code in the LibOS, then run these code?

**Comment by guzongmin** [comment]
> @guzongmin Sorry, our project leader claim that the local attestation should be okay until the end of this month, so I have to find a temporary solution.
> And I have a idea that the Occlum provide a device file named `/dev/sgx`, and local attestation can be done via `ioctl` with it. So what about write some C++ code to wrapper `ioctl` call, and compile the C++ code in the LibOS, then run these code?

It should work.

**Comment by Keepmoving-ZXY** [comment]
@guzongmin  ok, I will have a try.

**Comment by Keepmoving-ZXY** [comment]
Based on the code in `hello_cc` in the `demo`  directory, I write some simple code shown below, then run with `occlum run /bin/hello_world`:
```
#include <iostream>
#include <sgx_report.h>
#include <sgx.h>
#include <sgx_defs.h>
#include <sys/ioctl.h>
#include <string.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>

typedef struct {
	const sgx_target_info_t *target_info;
	const sgx_report_data_t *report_data;
	sgx_report_t            *report;
} sgxioc_create_report_arg_t;

#define SGXIOC_VERIFY_REPORT _IOWR('s', 5, sgx_report_t)
#define SGXIOC_CREATE_REPORT _IOWR('s', 4, sgxioc_create_report_arg_t)

int main() {
	int sgx_fd = 0;
	
	sgx_report_t report;
	sgxioc_create_report_arg_t arg;
	arg.target_info = nullptr;
	arg.report_data = nullptr;

	memset(&report, 0, sizeof(report));
	arg.report = &report; 
	
	sgx_fd = open("/dev/sgx", O_RDONLY);
	if (sgx_fd < 0) {
		std::cerr << "open /dev/sgx failed." << std::endl;
		return -1;
	}	

	int ret = ioctl(sgx_fd, SGXIOC_CREATE_REPORT, &arg);
	if (ret < 0) {
		close(sgx_fd);
		std::cerr << "ioctl error during create report." << std::endl;
		return -1;
	}

	close(sgx_fd);
	sgx_fd = -1;

	sgx_fd = open("/dev/sgx", O_RDONLY);
	if (sgx_fd < 0) {
		std::cerr << "open /dev/sgx failed." << std::endl;
		return -1;
	}	

	ret = ioctl(sgx_fd, SGXIOC_VERIFY_REPORT, &report);
	if (ret < 0) {
		close(sgx_fd);
		std::cerr << "failed to vertify report, error is " <<strerror(errno) << std::endl; 
		return -1;
	}
	
	close(sgx_fd);
	return 0;
}
```
The code is very simple, and during the generate report action run successfully, and the verify report failed with error `Invalid Argument`.
So I have two question:
1. does two ioctl of `/dev/sgx` with different request do local attestation ?
2. if question 1 is yes, does local attestation can't run in the same enclave?

**Comment by guzongmin** [comment]
Maybe the target_info is not correct. I have no time to try it out these days.

**Comment by Keepmoving-ZXY** [comment]
> Maybe the target_info is not correct. I have no time to try it out these days.

ok, I will have a try, thank you.

**Comment by Keepmoving-ZXY** [comment]
It seems that these code run well:
```
#include <iostream>
#include <sgx_report.h>
#include <sgx.h>
#include <sgx_defs.h>
#include <sys/ioctl.h>
#include <string.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>

typedef struct {
	const sgx_target_info_t *target_info;
	const sgx_report_data_t *report_data;
	sgx_report_t            *report;
} sgxioc_create_report_arg_t;

#define SGXIOC_SELF_TARGET   _IOR('s', 3, sgx_target_info_t)
#define SGXIOC_VERIFY_REPORT _IOW('s', 5, sgx_report_t)
#define SGXIOC_CREATE_REPORT _IOWR('s', 4, sgxioc_create_report_arg_t)

int main() {
	int sgx_fd = 0;

	sgx_report_t report;
	sgx_target_info_t target;
	sgxioc_create_report_arg_t arg;
	arg.target_info = nullptr;
	arg.report_data = nullptr;
	
	memset(&target, 0, sizeof(target));
	sgx_fd = open("/dev/sgx", O_RDONLY);
	if (sgx_fd < 0) {
		std::cerr << "open /dev/sgx failed." << std::endl;
		return -1;
	}	
	
	int ret = ioctl(sgx_fd, SGXIOC_SELF_TARGET, &target);
	if (ret < 0) {
		std::cerr << "generate target info failed." << std::endl;
		close(sgx_fd);
		return -1;
	}

	close(sgx_fd);

	memset(&report, 0, sizeof(report));
	arg.report = &report; 
	arg.target_info= &target;

	sgx_fd = open("/dev/sgx", O_RDONLY);
	if (sgx_fd < 0) {
		std::cerr << "open /dev/sgx failed." << std::endl;
		return -1;
	}	

	ret = ioctl(sgx_fd, SGXIOC_CREATE_REPORT, &arg);
	if (ret < 0) {
		close(sgx_fd);
		std::cerr << "ioctl error during create report." << std::endl;
		return -1;
	}

	close(sgx_fd);
	sgx_fd = -1;

	sgx_fd = open("/dev/sgx", O_RDONLY);
	if (sgx_fd < 0) {
		std::cerr << "open /dev/sgx failed." << std::endl;
		return -1;
	}	

	ret = ioctl(sgx_fd, SGXIOC_VERIFY_REPORT, &report);
	if (ret < 0) {
		close(sgx_fd);
		std::cerr << "failed to vertify report, error is " <<strerror(errno) << std::endl; 
		return -1;
	}

	close(sgx_fd);
	return 0;
}
```
These code is compiled via `occlum-gcc` and generate `hello_world`, then:
```
cp ../hello_world image/bin
occlum build
occlum run /bin/hello_world
```

This is screen output during `occlum-run /bin/hello_world`:
```
Enclave sign-tool: /opt/occlum/sgxsdk-tools/bin/x64/sgx_sign
Enclave sign-key: /opt/occlum/etc/template/Enclave.pem
SGX mode: HW
Building new image...
[+] Home dir is /root
[+] Open token file success! 
[+] Token file valid!
[+] Init Enclave Successful 54069343289346!
Generate the SEFS image successfully
EXPORT => OCCLUM_CONF_FILE_MAC = b1-1c-6a-75-b9-d1-61-8a-c6-65-94-56-ad-a5-a0-66
Building the initfs...
[+] Home dir is /root
[+] Open token file success! 
[+] Token file valid!
[+] Init Enclave Successful 54133767798786!
Generate the SEFS image successfully
Building libOS...
Signing the enclave...
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>1048576</StackMaxSize>
    <StackMinSize>1048576</StackMinSize>
    <HeapMaxSize>33554432</HeapMaxSize>
    <HeapMinSize>33554432</HeapMinSize>
    <TCSNum>32</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
    <ReservedMemMaxSize>314572800</ReservedMemMaxSize>
    <ReservedMemMinSize>314572800</ReservedMemMinSize>
    <ReservedMemInitSize>314572800</ReservedMemInitSize>
    <ReservedMemExecutable>1</ReservedMemExecutable>
</EnclaveConfiguration>
tcs_num 32, tcs_max_num 32, tcs_min_pool 1
The required memory is 384724992B.
The required memory is 0x16ee7000, 375708 KB.
Succeed.
Built the Occlum image and enclave successfully
```
No any output, this means that create&vertify report passed.

**Comment by guzongmin** [comment]
Your code seems correct. 
If you have no idea what is local attestation, you code reference https://sgx101.gitbook.io/sgx101/sgx-bootstrap/attestation/inter-process-local-attestation

**Comment by Keepmoving-ZXY** [comment]
ok, thank you for these day's help.
