### ISSUE TITLE
Questions about ocall

### ISSUE THREAD

**Issue by lz18064638846** [occlum/occlum#497]
When I read the source code of occlum, I notice that gettimeofday and rdtsc are wrapped with ocall, but as far as I knew, these two functions can work in user mode, so why did they need to be ocall? Is this about rust feature or sgx limitation? I will be really appreciate it if someone can help me figure out this.

**Comment by guzongmin** [comment]
@lz18064638846 gettimeofday is not supported inside Enclave, so we need an ocall. rdtsc is only supported on SGX2 platform, so it also needs an ocall on SGX1 HW.

**Comment by lz18064638846** [comment]
> @lz18064638846 gettimeofday is not supported inside Enclave, so we need an ocall. rdtsc is only supported on SGX2 platform, so it also needs an ocall on SGX1 HW.

This limitation is on hardware or software like driver?

**Comment by guzongmin** [comment]
@lz18064638846 HW limitation

**Comment by guzongmin** [comment]
Close this issue for no more active topics.
