### ISSUE TITLE
undefined reference to __snprintf_chk'  when compile thrift

### ISSUE THREAD

**Issue by SummerTrains** [occlum/occlum#501]
用occlum编译thrift的时候，遇到问题：

# To reproduce
1.occlum-gcc版本：
x86_64-linux-musl-gcc (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
2. 编译指令
export CC=occlum-gcc; export CXX=occlum-g++; export LD_LIBRARY_PATH=$SAME_PATH; ./configure  CPPFLAGS="-g -O2 -fPIC -I$SAME_PATH -L$SAME_PATH" LDFLAGS="-L$SAME_PATH -Wl,-rpath-link, $SAME_PATH" --without-rs --without-python --without-zlib --with-openssl=$SAME_PATH --with-boost=$SAME_PATH
make -j

# Logs
/app/TIP/honeycombDep/3rdparty/src/Boost/build/include/boost/smart_ptr/shared_ptr.hpp:529:34: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
     shared_ptr & operator=( std::auto_ptr<Y> && r )
                                  ^~~~~~~~
In file included from /opt/occlum/toolchains/gcc/x86_64-linux-musl/include/c++/8.3.0/memory:80,
                 from /app/TIP/honeycombDep/3rdparty/src/Boost/build/include/boost/config/no_tr1/memory.hpp:21,
                 from /app/TIP/honeycombDep/3rdparty/src/Boost/build/include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /app/TIP/honeycombDep/3rdparty/src/Boost/build/include/boost/shared_ptr.hpp:17,
                 from ../../../lib/cpp/src/thrift/transport/TTransport.h:24,
                 from ../../../lib/cpp/src/thrift/protocol/TProtocol.h:28,
                 from ../../../lib/cpp/src/thrift/TProcessor.h:24,
                 from processor/ServerThread.h:22,
                 from processor/ServerThread.cpp:22:
/opt/occlum/toolchains/gcc/x86_64-linux-musl/include/c++/8.3.0/bits/unique_ptr.h:53:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /app/TIP/honeycombDep/3rdparty/src/Boost/build/include/boost/shared_ptr.hpp:17,
                 from ../../../lib/cpp/src/thrift/transport/TTransport.h:24,
                 from ../../../lib/cpp/src/thrift/protocol/TProtocol.h:28,
                 from ../../../lib/cpp/src/thrift/TProcessor.h:24,
                 from processor/ServerThread.h:22,
                 from processor/ServerThread.cpp:22:
/app/TIP/honeycombDep/3rdparty/src/Boost/build/include/boost/smart_ptr/shared_ptr.hpp: In member function 'boost::shared_ptr<T>& boost::shared_ptr<T>::operator=(std::auto_ptr<_Up>&&)':
/app/TIP/honeycombDep/3rdparty/src/Boost/build/include/boost/smart_ptr/shared_ptr.hpp:531:38: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
         this_type( static_cast< std::auto_ptr<Y> && >( r ) ).swap( *this );
                                      ^~~~~~~~
In file included from /opt/occlum/toolchains/gcc/x86_64-linux-musl/include/c++/8.3.0/memory:80,
                 from /app/TIP/honeycombDep/3rdparty/src/Boost/build/include/boost/config/no_tr1/memory.hpp:21,
                 from /app/TIP/honeycombDep/3rdparty/src/Boost/build/include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /app/TIP/honeycombDep/3rdparty/src/Boost/build/include/boost/shared_ptr.hpp:17,
                 from ../../../lib/cpp/src/thrift/transport/TTransport.h:24,
                 from ../../../lib/cpp/src/thrift/protocol/TProtocol.h:28,
                 from ../../../lib/cpp/src/thrift/TProcessor.h:24,
                 from processor/ServerThread.h:22,
                 from processor/ServerThread.cpp:22:
/opt/occlum/toolchains/gcc/x86_64-linux-musl/include/c++/8.3.0/bits/unique_ptr.h:53:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/bin/bash ../../../libtool  --tag=CXX   --mode=link occlum-g++ -Wall -Wextra -pedantic -g -O2 -L/app/TIP/honeycombDep/3rdparty/src/Boost/build/lib -L/app/TIP/honeycombDep/3rdparty/src/build/lib -Wl,-rpath-link,/app/TIP/honeycombDep/3rdparty/src/build/lib -o processor_test processor/ProcessorTest.o processor/EventLog.o processor/ServerThread.o libprocessortest.
libtool: warning: library '/opt/occlum/toolchains/gcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/lib/libstdc++.la' was moved.
libtool: warning: library '/opt/occlum/toolchains/gcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/lib/libstdc++.la' was moved.
libtool: link: occlum-g++ -Wall -Wextra -pedantic -g -O2 -Wl,-rpath-link -Wl,/app/TIP/honeycombDep/3rdparty/src/build/lib -o .libs/processor_test processor/ProcessorTest.o processor/EventLog.o processor/ServerThread.o  -L/app/TIP/honeycombDep/3rdparty/src/Boost/build/lib -L/app/TIP/honeycombDep/3rdparty/src/build/lib ./.libs/libprocessortest.a /opt/occlum/tool
/opt/occlum/toolchains/gcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/bin/ld: /app/TIP/honeycombDep/3rdparty/src/Boost/build/lib/libboost_unit_test_framework.a(debug.o): in function `boost::debug::(anonymous namespace)::process_info::process_info(int)':
debug.cpp:(.text+0x73): undefined reference to `__snprintf_chk'
/opt/occlum/toolchains/gcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/bin/ld: debug.cpp:(.text+0x13b): undefined reference to `__snprintf_chk'
/opt/occlum/toolchains/gcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/bin/ld: /app/TIP/honeycombDep/3rdparty/src/Boost/build/lib/libboost_unit_test_framework.a(debug.o): in function `boost::debug::(anonymous namespace)::prepare_gdb_cmnd_file(boost::debug::dbg_startup_info const&)':
debug.cpp:(.text+0x1fd): undefined reference to `__snprintf_chk'
/opt/occlum/toolchains/gcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/bin/ld: /app/TIP/honeycombDep/3rdparty/src/Boost/build/lib/libboost_unit_test_framework.a(debug.o): in function `boost::debug::(anonymous namespace)::safe_execlp(char const*, ...)':
debug.cpp:(.text+0x57a): undefined reference to `__printf_chk'
/opt/occlum/toolchains/gcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/bin/ld: debug.cpp:(.text+0x5d6): undefined reference to `__printf_chk'
/opt/occlum/toolchains/gcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/bin/ld: /app/TIP/honeycombDep/3rdparty/src/Boost/build/lib/libboost_unit_test_framework.a(debug.o): in function `boost::debug::(anonymous namespace)::start_dbx_in_console(boost::debug::dbg_startup_info const&)':
debug.cpp:(.text+0x75b): undefined reference to `__snprintf_chk'
/opt/occlum/toolchains/gcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/bin/ld: debug.cpp:(.text+0x7a6): undefined reference to `__snprintf_chk'
/opt/occlum/toolchains/gcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/bin/ld: /app/TIP/honeycombDep/3rdparty/src/Boost/build/lib/libboost_unit_test_framework.a(debug.o): in function `boost::debug::(anonymous namespace)::prepare_window_title(boost::debug::dbg_startup_info const&)':
debug.cpp:(.text+0x85a): undefined reference to `__snprintf_chk'
/opt/occlum/toolchains/gcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/bin/ld: /app/TIP/honeycombDep/3rdparty/src/Boost/build/lib/libboost_unit_test_framework.a(debug.o): in function `boost::debug::(anonymous namespace)::start_dbx_in_ddd(boost::debug::dbg_startup_info const&)':
debug.cpp:(.text+0xb8b): undefined reference to `__snprintf_chk'
/opt/occlum/toolchains/gcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/bin/ld: debug.cpp:(.text+0xbcf): undefined reference to `__snprintf_chk'
/opt/occlum/toolchains/gcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/bin/ld: /app/TIP/honeycombDep/3rdparty/src/Boost/build/lib/libboost_unit_test_framework.a(debug.o):debug.cpp:(.text+0xc90): more undefined references to `__snprintf_chk' follow
/opt/occlum/toolchains/gcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/bin/ld: /app/TIP/honeycombDep/3rdparty/src/Boost/build/lib/libboost_unit_test_framework.a(execution_monitor.o): in function `execution_monitor_jumping_signal_handler':
execution_monitor.cpp:(.text+0x3a): undefined reference to `__longjmp_chk'
/opt/occlum/toolchains/gcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/bin/ld: /app/TIP/honeycombDep/3rdparty/src/Boost/build/lib/libboost_unit_test_framework.a(execution_monitor.o): in function `execution_monitor_attaching_signal_handler':
execution_monitor.cpp:(.text+0x201): undefined reference to `__longjmp_chk'
/opt/occlum/toolchains/gcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/bin/ld: /app/TIP/honeycombDep/3rdparty/src/Boost/build/lib/libboost_unit_test_framework.a(execution_monitor.o): in function `boost::detail::report_error(boost::execution_exception::error_code, boost::exception const*, char const*, __va_list_tag (*) [1])':
execution_monitor.cpp:(.text+0xce8): undefined reference to `__vsnprintf_chk'
collect2: error: ld returned 1 exit status
Makefile:1168: recipe for target 'processor_test' failed
make[3]: *** [processor_test] Error 1
make[3]: Leaving directory '/app/TIP/honeycombDep/3rdparty/src/Thrift/lib/cpp/test'
Makefile:954: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/app/TIP/honeycombDep/3rdparty/src/Thrift/lib/cpp/test'
Makefile:646: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/app/TIP/honeycombDep/3rdparty/src/Thrift'
Makefile:560: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by guzongmin** [comment]
Not an issue
