### ISSUE TITLE
 undefined reference to `main', when compile opencv2.4.13

### ISSUE THREAD

**Issue by SummerTrains** [occlum/occlum#502]
用occlum 编译 opencv2.4.13
/opt/occlum/toolchains/gcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/bin/ld: /opt/occlum/toolchains/gcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/lib/Scrt1.o: in function `_start_c':
Scrt1.c:(.text._start_c+0x1b): undefined reference to `main'

# To reproduce
1. download opencv.2.4.13.zip   unzip
2. 编译指令：third_party_path=`pwd`
cd OpenCV
rm -rf build && mkdir -p build/tmp && cd build
CMAKE_PARAM=${CMAKE_PARAM}" -DCMAKE_CXX_COMPILER:FILEPATH=/opt/occlum/toolchains/gcc/bin/occlum-g++ -DCMAKE_C_COMPILER:FILEPATH=/opt/occlum/toolchains/gcc/bin/occlum-gcc -DPYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") -DPYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; import os; print(os.path.join(sysconfig.get_config_var('LIBDIR'), sysconfig.get_config_var('LDLIBRARY')))")"
cmake .. ${CMAKE_PARAM} -DBUILD_opencv_java=OFF -DBUILD_JAVA_SUPPORT=OFF -DBUILD_PYTHON_SUPPORT=OFF -DBUILD_opencv_python=OFF -DBUILD_EXAMPLES=OFF -DWITH_FFMPEG=ON -DBUILD_ZLIB=ON -DBUILD_TIFF=ON -DBUILD_JASPER=ON -DBUILD_JPEG=OFF -DBUILD_PNG=ON -DBUILD_OPENEXR=ON -DCMAKE_BUILD_TYPE=RELEASE -DWITH_QT=OFF -DWITH_CUDA=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=./tmp -DWITH_JPEG=ON -DJPEG_LIBRARY=${third_party_path}/jpeg/build/usr/local/lib/libjpeg.a -DJPEG_INCLUDE_DIR=${third_party_path}/jpeg/build/usr/local/include/
make -j1

# Logs
[ 16%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/b44ExpLogTable.cpp.o
[ 16%] Linking CXX static library ../lib/libIlmImf.a
[ 16%] Built target IlmImf
[ 16%] Generating opencv_test_core_pch_dephelp.cxx
Scanning dependencies of target opencv_test_core_pch_dephelp
[ 16%] Building CXX object modules/core/CMakeFiles/opencv_test_core_pch_dephelp.dir/opencv_test_core_pch_dephelp.cxx.o
[ 16%] Linking CXX static library ../../lib/libopencv_test_core_pch_dephelp.a
[ 16%] Built target opencv_test_core_pch_dephelp
[ 16%] Generating opencv_core_pch_dephelp.cxx
Scanning dependencies of target opencv_core_pch_dephelp
[ 16%] Building CXX object modules/core/CMakeFiles/opencv_core_pch_dephelp.dir/opencv_core_pch_dephelp.cxx.o
[ 16%] Linking CXX static library ../../lib/libopencv_core_pch_dephelp.a
[ 16%] Built target opencv_core_pch_dephelp
[ 16%] Generating opencv_ts_pch_dephelp.cxx
Scanning dependencies of target opencv_ts_pch_dephelp
[ 16%] Building CXX object modules/ts/CMakeFiles/opencv_ts_pch_dephelp.dir/opencv_ts_pch_dephelp.cxx.o
[ 16%] Linking CXX static library ../../lib/libopencv_ts_pch_dephelp.a
[ 16%] Built target opencv_ts_pch_dephelp
Scanning dependencies of target pch_Generate_opencv_ts
[ 16%] Generating precomp.hpp
[ 16%] Generating precomp.hpp.gch/opencv_ts_RELEASE.gch
/opt/occlum/toolchains/gcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/bin/ld: /opt/occlum/toolchains/gcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/lib/Scrt1.o: in function `_start_c':
Scrt1.c:(.text._start_c+0x1b): undefined reference to `main'
collect2: error: ld returned 1 exit status
modules/ts/CMakeFiles/pch_Generate_opencv_ts.dir/build.make:62: recipe for target 'modules/ts/precomp.hpp.gch/opencv_ts_RELEASE.gch' failed
make[2]: *** [modules/ts/precomp.hpp.gch/opencv_ts_RELEASE.gch] Error 1
CMakeFiles/Makefile2:7146: recipe for target 'modules/ts/CMakeFiles/pch_Generate_opencv_ts.dir/all' failed
make[1]: *** [modules/ts/CMakeFiles/pch_Generate_opencv_ts.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
[  2%] Built target zlib
[  6%] Built target libtiff
[  9%] Built target libjasper
[ 10%] Built target libpng
[ 16%] Built target IlmImf
[ 16%] Built target opencv_test_core_pch_dephelp
[ 16%] Built target opencv_core_pch_dephelp
[ 16%] Built target opencv_ts_pch_dephelp
[ 16%] Generating precomp.hpp.gch/opencv_ts_RELEASE.gch
/opt/occlum/toolchains/gcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/bin/ld: /opt/occlum/toolchains/gcc/bin/../lib/gcc/x86_64-linux-musl/8.3.0/../../../../x86_64-linux-musl/lib/Scrt1.o: in function `_start_c':
Scrt1.c:(.text._start_c+0x1b): undefined reference to `main'
collect2: error: ld returned 1 exit status
modules/ts/CMakeFiles/pch_Generate_opencv_ts.dir/build.make:62: recipe for target 'modules/ts/precomp.hpp.gch/opencv_ts_RELEASE.gch' failed
make[2]: *** [modules/ts/precomp.hpp.gch/opencv_ts_RELEASE.gch] Error 1
CMakeFiles/Makefile2:7146: recipe for target 'modules/ts/CMakeFiles/pch_Generate_opencv_ts.dir/all' failed
make[1]: *** [modules/ts/CMakeFiles/pch_Generate_opencv_ts.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

# Environment

- Occlum version: root@17b9c03e0d39:/app/TIP/honeycombDep/3rdparty# occlum-g++ --version
x86_64-linux-musl-g++ (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.

**Comment by SummerTrains** [comment]
What's more, if I use gcc/g++, not occlum-gcc/g++ , it's OK

**Comment by guzongmin** [comment]
> What's more, if I use gcc/g++, not occlum-gcc/g++ , it's OK

If you are able to build opencv with gcc/g++, could please try the compiled binary in Occlum? Occlum also supports those pre-compiled binaries if it is PIC/PIE binary.

**Comment by liqinggd** [comment]
@SummerTrains We have built the OpenCV 4.1.0 in the OpenVINO demo, please see  [here](https://github.com/occlum/occlum/blob/master/demos/openvino/download_and_build_openvino.sh#L13) if it can help you.
