### ISSUE TITLE
occlum run /bin/hello_world failed due to FSGSBASE enablement check failed 

### ISSUE THREAD

**Issue by mirazsunny** [occlum/occlum#509]
I am running the hello_world.c from demos. I enabled **rdfsbase** kernel module. When I am running the program in HW mode it gives me the following error:

`occlum run /bin/hello_world`
`[ERROR] occlum-pal: 	SIGILL Caught ! (line 37, file src/pal_check_fsgsbase.c)`
`[ERROR] occlum-pal: FSGSBASE enablement check failed. (line 84, file src/pal_api.c)`

Could you please tell what I am doing wrong?

**Comment by guzongmin** [comment]
It seems the kernel issue. We notice that the latest Ubuntu 18.04 kernel disabled the FSGSBASE MSR update feature. So if you want to try Occlum, please use the latest Linux 15.12 kernel or an older one. I am using "Linux 5.4.0-42-generic x86_64".

**Comment by mirazsunny** [comment]
It's working now. I update my kernel to 5.10. Thanks.

**Comment by prz23** [comment]
> It seems the kernel issue. We notice that the latest Ubuntu 18.04 kernel disabled the FSGSBASE MSR update feature. So if you want to try Occlum, please use the latest Linux 15.12 kernel or an older one. I am using "Linux 5.4.0-42-generic x86_64".

Why docker image pulled from occlum's dockerhub[1] use an old version of kernel “Linux 4.15.0”[2]，Do I need to upgrade it manually?

[1]https://hub.docker.com/layers/occlum/occlum/0.29.1-ubuntu20.04/images/sha256-de5388e0609d15a4d7797083d69b11d8dcc364c4bc3b9f897922b5e74363cff6?context=explore
[2]Linux version 4.15.0-194-generic

**Comment by guzongmin** [comment]
@prz23 There are some references to help you.
https://superuser.com/questions/889472/docker-containers-have-their-own-kernel-or-not
https://www.zhihu.com/question/55143510

**Comment by prz23** [comment]
Got it.Thanks.
