### ISSUE TITLE
Can user_space_size be specified at runtime?

### ISSUE THREAD

**Issue by zchunhai** [occlum/occlum#537]
I want to specify the resource limits of the container at runtime，but the parameter "resource_limits.user_space_size" in the file Occlum.json is used in build time.

Can the parameter be specified at runtime?

**Comment by guzongmin** [comment]
@zchunhai It is not supported  now. But you are able to adjust the process resource by command: ulimit
For detail information, please reference https://github.com/occlum/occlum/tree/master/demos/fish

**Comment by zchunhai** [comment]
> @zchunhai It is not supported now. But you are able to adjust the process resource by command: ulimit
> For detail information, please reference https://github.com/occlum/occlum/tree/master/demos/fish

Thanks, I'll try.
