### ISSUE TITLE
Problems when executing shell script under fish-shell

### ISSUE THREAD

**Issue by asdfsx** [occlum/occlum#561]
1. build-in command`cd` cannot use 

   I write a shell script as below
 
   ```
   #!/usr/bin/fish
   cd /opt/app/
   /bin/python3 main.py 
   
   echo "start center-algorithm"
   ```
   
   and when I execute the script, I got the following error
   ```
   [2021-07-27T10:20:30.551Z][DEBUG][T2][#102][····Stat] fstatat: fs_path: FsPath { Absolute("/opt/app/center-computation") }, flags: (empty)
   [2021-07-27T10:20:30.551Z][DEBUG][T2][#102][····Stat] lookup_inode: cwd: "/", path: "/opt/app/center-computation"
   [2021-07-27T10:20:30.551Z][DEBUG][T2][#103][····Open] openat: fs_path: FsPath { Absolute("/opt/app/center-computation") }, flags: 0o2000000, mode: 0o0
   [2021-07-27T10:20:30.551Z][DEBUG][T2][#103][····Open] lookup_inode: cwd: "/", path: "/opt/app/center-computation"
   [2021-07-27T10:20:30.551Z][DEBUG][T2][#103][····Open] convert_to_abs_path: cwd: "/", path: "/opt/app/center-computation"
   [2021-07-27T10:20:30.551Z][DEBUG][T2][#104][···Fcntl] fcntl: fd: 6, cmd: SetFd(1)
   [2021-07-27T10:20:30.551Z][ERROR][T2][#105][··Fchdir] Error = ENOSYS (#38, Function not implemented): Unimplemented or unknown syscall [line = 910, file = src/syscall/mod.rs]
   [2021-07-27T10:20:30.551Z][DEBUG][T2][#106][····Stat] fstatat: fs_path: FsPath { Absolute("/opt/app/center-computation") }, flags: (empty)
   [2021-07-27T10:20:30.551Z][DEBUG][T2][#106][····Stat] lookup_inode: cwd: "/", path: "/opt/app/center-computation"
   [2021-07-27T10:20:30.551Z][DEBUG][T2][#107][·····Brk] brk: addr: 0x7f9816b47000
   [2021-07-27T10:20:30.551Z][DEBUG][T2][#108][···Close] close: fd: 6
   [2021-07-27T10:20:30.551Z][DEBUG][T2][#109][···Write] write: fd: 2
   cd: Permission denied: '/opt/app/center-computation'
   /bin/startup.sh (line 10): 
   cd /opt/app/center-computation
   ^
   [2021-07-27T10:20:30.551Z][DEBUG][T2][#112][··Access] faccessat: fs_path: FsPath { Absolute("/bin/python3") }, mode: X_OK, flags: (empty)
   ```
 
   It seems `Fchdir` is not implemented, so build-in command `cd` failed when executing. Am I right ? And is there any plan to support more syscalls ? 

2. Occlum stucked when execute a program in backend
    
   scripts like below

   ```
   #!/usr/bin/fish
   
   set -gx PYTHONHOME /opt/python-occlum

   set -gx PYTHONPATH /opt/app1
   /bin/python3 /opt/app1/main.py &
  
   set -gx PYTHONPATH /opt/app2
   /bin/python3 /opt/app2/main.py 
   ```

   Occlum stuck without any errors.

   Does Occlum support scripts like this?

**Comment by guzongmin** [comment]
@asdfsx about the first issue, we would add Fchdir soon.
About the second one, please separate the script into two: Script1.sh and Script2.sh
Then you can run below commands:

occlum start
occlum exec /bin/Script1.sh &
occlum exec /bin/Script2.sh
occlum stop

**Comment by jessehui** [comment]
@asdfsx #562 should fix the first issue. For the second one, since there is no process group or session implementation in Occlum for now, the background process is not supported yet inside Occlum. We are working on that.

**Comment by asdfsx** [comment]
@jessehui Even `occlum exec /bin/Script1.sh &` can not create a background process?
Another question is the process config in `Occlum.json` define the memory allocation for each process, and the process_vm will allocate memory for each process according to this configuration. Is that mean if I start a python program use fish-shell scripts, the process fish-shell scripts will spend same memory like the python program. Am I right?

**Comment by jessehui** [comment]
> @jessehui Even `occlum exec /bin/Script1.sh &` can not create a background process?

I am wondering why you need a background process here?  `occlum exec ... &` and `occlum run ... &` should both work.

> Another question is the process config in `Occlum.json` define the memory allocation for each process, and the process_vm will allocate memory for each process according to this configuration. Is that mean if I start a python program use fish-shell scripts, the process fish-shell scripts will spend same memory like the python program. Am I right?

You are right. All processes created in Occlum will be assigned the same amount of memory. It is true that sometimes it is a waste like in this case. However, you can use `ulimit` and change the VM configuration for the next process. You can take a look [here](https://github.com/occlum/occlum/tree/master/demos/fish#per-process-resource-configuration-with-help-of-fish)

**Comment by asdfsx** [comment]
@jessehui I want to start 2 app in one Occlum container, so they can sharing same sefs.

I have modified my script, split it into 2, like below

```
#!/usr/bin/fish

ulimit -Ss 20480 # stack size 20M
ulimit -Sd 81920 # heap size 80M
ulimit -Sv 2048000 # virtual memory size 2000M (including heap, stack, mmap size)

ulimit -a

set -gx OCCLUM yes
set -gx PYTHONHOME /opt/python-occlum
set -gx PYTHONPATH /opt/app1
/bin/python3 /opt/app1/wrapper.py 
```

```
#!/usr/bin/fish

ulimit -Ss 20480 # stack size 20M
ulimit -Sd 81920 # heap size 80M
ulimit -Sv 8192000 # virtual memory size 8000M (including heap, stack, mmap size)

ulimit -a

set -gx OCCLUM yes
set -gx PYTHONHOME /opt/python-occlum
set -gx PYTHONPATH /opt/app2
/bin/python3 /opt/app2/wrapper.py
```

then I start them 

```
occlum start
occlum exec /bin/app1.sh
occlum exec /bin/app1.sh
```

then I got following error

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /root/occlum/deps/sefs/rcore-fs-unionfs/src/lib.rs:484:18
stack backtrace:
   0: <sgx_tstd::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
             at library/core/src/fmt/mod.rs:1076
   2: sgx_tstd::io::Write::write_fmt
   3: sgx_tstd::panicking::default_panic_handler
   4: sgx_tstd::panicking::rust_panic_with_hook
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
             at library/core/src/panicking.rs:85
   7: core::panicking::panic
             at library/core/src/panicking.rs:50
   8: rcore_fs_unionfs::UnionINode::new_inode
   9: <rcore_fs_unionfs::UnionINode as rcore_fs::vfs::INode>::iterate_entries
  10: <occlum_libos_core_rs::fs::inode_file::INodeFile as occlum_libos_core_rs::fs::file::File>::iterate_entries
  11: occlum_libos_core_rs::fs::file_ops::getdents::do_getdents
  12: occlum_libos_core_rs::fs::syscalls::do_getdents
  13: occlum_libos_core_rs::syscall::dispatch_syscall
  14: occlum_libos_core_rs::syscall::do_syscall
  15: occlum_syscall
  16: <unknown>
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
[ERROR] occlum-pal: Failed to enter the enclave to execute a LibOS thread (host tid = 448) with error code 0x1006: Unknown SGX error (line 22, file src/ocalls/spawn.c)
```

can someone tell what happened ?

**Comment by guzongmin** [comment]
@asdfsx Can you please share me the app1 code?

**Comment by asdfsx** [comment]
@guzongmin you mean the shell script code or python code?

**Comment by guzongmin** [comment]
> @guzongmin you mean the shell script code or python code?
> BTW, can I share some data between 2 app using sefs if they belong to different occlum containers?

Occlum is just like a container, each instance has its own file system. So if you want to share something between two Occlum instance, you need to use gRPC or something similar.

**Comment by asdfsx** [comment]
@guzongmin So the only way to share sth between 2 occlum container is network communication. 

What about 2 app in same occlum container? can they share the same sefs?

The error I just met is sharing same sefs between 2 apps inside one occlum container. 

But it doesn't happen anymore.

**Comment by guzongmin** [comment]
> @guzongmin So the only way to share sth between 2 occlum container is network communication.
> 
> What about 2 app in same occlum container? can they share the same sefs?
> 
> The error I just met is sharing same sefs between 2 apps inside one occlum container.
> 
> But it doesn't happen anymore.

Two apps inside one Occlum instance means that the two applications are using the same SEFS. Of course, the two applications are able to share any file.

**Comment by asdfsx** [comment]
After read some code in [github.com/occlum/sefs](https://github.com/occlum/sefs)

I guess the problem is the 2nd app try's to read/write the inode the 1st app modified but haven't synced yet.

Fox example, the `log` directory. Right now two apps sharing the same directory to write logfile.

If it's true, may be I should create 2 independent log directory for both app.

**Comment by asdfsx** [comment]
@guzongmin maybe I find a bug related to `ulimit`

my fish-script
```
#!/usr/bin/fish

ulimit -Ss 30720 # stack size 30M
ulimit -Sd 256000 # heap size 256M
ulimit -Sv 8192000 # virtual memory size 8000M (including heap, stack, mmap size)

ulimit -a

set -gx OCCLUM yes
set -gx PYTHONHOME /opt/python-occlum
set -gx PYTHONPATH /opt/app
/bin/python3 /opt/app/occlum_main.py -c /opt/app/etc/config.yaml 
```

I set the heap size to `256000`

but the output of the `ulimit -a` is 
```
Maximum size of core files created                                                     (kB, -c) unlimited
Maximum size of a process’s data segment                                       (kB, -d) 32768
Maximum size of files created by the shell                                          (kB, -f) unlimited
Maximum size that may be locked into memory                                 (kB, -l) unlimited
Maximum resident set size                                                                  (kB, -m) unlimited
Maximum number of open file descriptors                                                (-n) unlimited
Maximum stack size                                                                               (kB, -s) 30720
Maximum amount of cpu time in seconds                                  (seconds, -t) unlimited
Maximum number of processes available to a single user                       (-u) unlimited
Maximum amount of virtual memory available to the shell                (kB, -v) 8192000
```

I think the 2nd line should not be 32768.

And it seems the ulimit doesn't support `unlimited` parameter, am I right?

**Comment by jessehui** [comment]
> @guzongmin maybe I find a bug related to `ulimit`
> 
> my fish-script
> 
> ```
> #!/usr/bin/fish
> 
> ulimit -Ss 30720 # stack size 30M
> ulimit -Sd 256000 # heap size 256M
> ulimit -Sv 8192000 # virtual memory size 8000M (including heap, stack, mmap size)
> 
> ulimit -a
> 
> set -gx OCCLUM yes
> set -gx PYTHONHOME /opt/python-occlum
> set -gx PYTHONPATH /opt/app
> /bin/python3 /opt/app/occlum_main.py -c /opt/app/etc/config.yaml 
> ```
> 
> I set the heap size to `256000`, but the output of the `ulimit -a` is
> 
> ```
> ...
> Maximum size of core files created                           (kB, -c) unlimited
> Maximum size of a process’s data segment                     (kB, -d) 32768
> Maximum size of files created by the shell                   (kB, -f) unlimited
> Maximum size that may be locked into memory                  (kB, -l) unlimited
> Maximum resident set size                                    (kB, -m) unlimited
> Maximum number of open file descriptors                          (-n) unlimited
> Maximum stack size                                           (kB, -s) 30720
> Maximum amount of cpu time in seconds                   (seconds, -t) unlimited
> Maximum number of processes available to a single user           (-u) unlimited
> Maximum amount of virtual memory available to the shell      (kB, -v) 8192000
> ...
> ```
> 
> I think the 2nd line should not be 32768, cause I set it to 256000. And I don't know whether the config is success.

Could you try `ulimit -Sv` first and then set stack and data? If it still doesn't give the correct value,  you can check the return value to make sure `ulimit` success or add `OCCLUM_LOG_LEVEL=trace` when running the script.

> BTW it seems the ulimit doesn't support `unlimited` parameter right now, am I right?
Correct. Setting `unlimited` is not supported.

**Comment by asdfsx** [comment]
@jessehui After change the scripts to
```
ulimit -Sv 6184000 
ulimit -Sd 256000
ulimit -Ss 30720
ulimit -a
```
The return value is correct.

So why should I use `ulimit -Sv` first? why is the order so important?

**Comment by guzongmin** [comment]
> @jessehui After change the scripts to
> 
> ```
> ulimit -Sv 6184000 
> ulimit -Sd 256000
> ulimit -Ss 30720
> ulimit -a
> ```
> 
> The return value is correct.
> 
> So why should I use `ulimit -Sv` first? why is the order so important?

When you are running "ulimit -Sd 256000", the heap size is larger than the total memory limit, so it failed.

**Comment by asdfsx** [comment]
@guzongmin So, if I don't set `ulimit -Sv 6184000`, how big is the default memory limit?
