### ISSUE TITLE
Running standalone gzip.c in Occlum

### ISSUE THREAD

**Issue by mirazsunny** [occlum/occlum#567]
Hi,

I am running standalone compiled gzip in Occlum. Output showing the argument path is not finding any file. Here are the steps:

`mkdir occlum_instance && cd occlum_instance`
`occlum init`
`cp ../gzip image/bin`
`occlum build`
`occlum run /bin/gzip ../gzip_copy.c`

Output is:
`gzip: ../gzip_copy.c: No such file or directory`

However, in the Linux runtime, it's working. Could you please tell me what I am doing wrong?

**Comment by guzongmin** [comment]
@mirazsunny You need to copy the gzip_copy.c into image folder too.
cp gzip_copy.c image/

**Comment by mirazsunny** [comment]
Thanks for replying.

I copied the file still showing the same result. `cp ../gzip_copy.c image/`

Then I run: `occlum run /bin/gzip image/gzip_copy.c`

Output is: `gzip: /image/gzip_copy.c: No such file or directory`

**Comment by guzongmin** [comment]
occlum run /bin/gzip  ../gzip_copy.c
You should use the path inside occlum.

**Comment by mirazsunny** [comment]
Thanks for replying. It's working now.
