### ISSUE TITLE
JAVA file getUsableSpace returns strange values (SEFS)

### ISSUE THREAD

**Issue by qzheng527** [occlum/occlum#586]
In developing sofaboot (spring boot), the health check always failed due to the "diskSpace" check.
It returns total disk size as 256k which is much smaller than the threshold 10M.
Tracing the calling process, the issue happened in the flow as below.

**java getUsableSpace->syscall Statfs->...->sefs info.**

From the definition, **the default block size is set to 128, while blocks is set to 128*8=1024**.
(occlum/deps/sefs/rcore-fs-sefs/src/structs.rs)

I don't know why there is such setting which looks to me is not correct.
I tried modifying the block size to 4096, then getUsableSpace may return 100M+ which can satisfy the requirements of the health check. But I don't think it is a good enough solution.

The JAVA code I used to trace the bug.
```
import java.io.File;

public class Main {
   public static void main(String[] args) {
      
      File f = null;
      long v;
      boolean bool = false;
      
      try{
         // create new file
         f = new File(".");
         
         // number of bytes available
         v = f.getUsableSpace();
         
         // true if the file path exists
         bool = f.exists();
         
         // if file exists
         if(bool)
         {
            // prints
            System.out.println("number of bytes available: "+v);
         }
      }catch(Exception e){
         // if any error occurs
         e.printStackTrace();
      }
   }
}
```

BTW, the same java code in Linux host may return the /dev/sda disk size.

**Comment by liqinggd** [comment]
The `block_size` is big enough to store one INode's information in the metadata file, so the block_size is 128bit.

The `blocks` is the number of blocks used in SEFS, is will be increased if allocate new block group.

Maybe the meaning of this information is not consistent with Linux, then we can change it

**Comment by qzheng527** [comment]
“The blocks is the number of blocks used in SEFS, is will be increased if allocate new block group.”
But it can't exaplain why the blocks is so small (2048) in my another very heavy sofaboot occlum app.
Only the jar file is over 100M why the total size return is only 128*2048=256K?
```
occlum_instance# ls -lh image/usr/lib/spring/
total 136M
-rw-r--r-- 1 root root 136M Aug 11 05:09 windowsappsign-bootstrap-1.0.0-SNAPSHOT-executable.jar
```

**Comment by liqinggd** [comment]
”allocate new block group“ means the filesystem has many files, so one block group is not enough to hold the metadata of the files.

**Comment by liqinggd** [comment]
Linux FS uses block_size as the size of the data block, but SEFS's block is the metadata of INode, to fix it, we should change it.

**Comment by qzheng527** [comment]
Anyway, the app calling getUsableSpace expects the correct total size, free space size, used space size.
Even changing the block_size to 4096, I don't see correct values. 
The calculating used space size couldn't reflect the actual status. 

BTW, the "busybox df" in fishshell couldn't work in Occlum as well.
Looks like it trys to read the mount info but failed.
