### ISSUE TITLE
[BUG] "Fail to get quote report from IAS" when  I run  remote attestation

### ISSUE THREAD

**Issue by lcmfq** [occlum/occlum#624]
# Describe the bug
When I  run the remote attestation in SIM_Mode I get "[ERROR][/root/occlum/demos/remote_attestation/lib/src/ra_ias.cpp:293] Fail to get quote report from IAS
[ERROR][/root/occlum/demos/remote_attestation/lib/src/ra_quote.cpp:187] [Function] GetEnclaveIasReport
Fail to get quote or fetch report, error code is 5040000!"

# Logs
*   Trying 40.87.90.88:443...
* Connected to api.trustedservices.intel.com (40.87.90.88) port 443 (#0)
* ALPN, offering http/1.1
* error setting certificate verify locations, continuing anyway:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; postalCode=95054-1537; ST=California; L=Santa Clara; street=FM1-110; street=2200 Mission College Blvd; O=Intel
*  start date: Oct 23 00:00:00 2020 GMT
*  expire date: Oct 23 23:59:59 2021 GMT
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Organization Validation Secure Server CA
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> POST /sgx/dev/attestation/v4/report HTTP/1.1
Host: api.trustedservices.intel.com
User-Agent: sgx-sp/1.0
Accept: application/json
Content-Type: application/json
Ocp-Apim-Subscription-Key: 91afd031914e44169fd7846e9859c918
Content-Length: 1511

* upload completely sent off: 1511 out of 1511 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Content-Length: 0
< Request-ID: 87570e4108b3445386299afcb71e5552
< Date: Mon, 06 Sep 2021 05:49:35 GMT
<
* Closing connection 0
[ERROR][/root/occlum/demos/remote_attestation/lib/src/ra_ias.cpp:293] Fail to get quote report from IAS
[ERROR][/root/occlum/demos/remote_attestation/lib/src/ra_quote.cpp:187] [Function] GetEnclaveIasReport

# Environment

- SIM_MODE
- OS: Linux 18.04 on Hyper-V
- Occlum version: master

**Comment by guzongmin** [comment]
@lcmfq I checked the daily test result, the RA case passed. 
I think maybe the issue is: simulation mode is used to develop RA related application. SGX RA is a HW feature, under simulation mode you would build the application, but it is NOT able to work as you expected. You need an SGX HW to test it.

**Comment by lcmfq** [comment]
Thank you！ I try with HW
