### ISSUE TITLE
Out of memory error when I run golang project

### ISSUE THREAD

**Issue by kunmel** [occlum/occlum#634]
I meet this error when I run golang project with occlum,  but it is not included in `Resource Configuration Guide`，please tell me the reason for this problem and  which parameter should I enlarge in Occlum.json.   :
```
runtime: out of memory: cannot allocate 268435456-byte block (66158592 in use)
fatal error: out of memory
```
Here is part of my Occlum.json:
```
  "resource_limits": {
    "kernel_space_heap_size": "630MB",
    "kernel_space_stack_size": "10MB",
    "user_space_size": "5120MB",
    "max_num_of_threads": 32
  },
  "process": {
    "default_stack_size": "40MB",
    "default_heap_size": "320MB",
    "default_mmap_size": "960MB"
  },

```

**Comment by guzongmin** [comment]
@kunmel The doc https://github.com/occlum/occlum/blob/master/docs/resource_config_guide.md shows some cases to help you config the memory.
In your case, it could be "resource_limits.kernel_space_heap_size".

**Comment by kunmel** [comment]
@guzongmin Sorry, I think this error may be caused by go-ethereum , not due to occlum. I found that the go-ethereum needs 64bit machine and os, do you think this is the problem?

**Comment by guzongmin** [comment]
@kunmel Occlum does support 64bit environment. It is the default behavior.

**Comment by kunmel** [comment]
@guzongmin OK，I will continue to look for the reason. Thank you for your help!
