### ISSUE TITLE
How to deliver variables between SGX and untrusted environments

### ISSUE THREAD

**Issue by ziqi-zhang** [occlum/occlum#648]
Hi,

I want to implement a python program that needs to transmit variables between SGX and untrusted environments. I read some documents and examples but they didn't cover how to transmit variables in and outside the SGX. I was wondering is there any documents about how to implement such features?

Thanks,

**Comment by guzongmin** [comment]
@ziqi-zhang What is the variables? In general, you could host a grpc server inside Occlum. Below is a sample 
https://github.com/occlum/occlum/tree/master/demos/grpc

**Comment by ziqi-zhang** [comment]
@guzongmin Thanks very much for your quick reply. I want to implement a pytorch model and the features and weights need to be transmitted. Is grpc compatible with pytorch models?

**Comment by guzongmin** [comment]
I think grpc is able to handle all the cases. But it is a bit heavy for a simple demo. So it depends on what you are doing now.

**Comment by ziqi-zhang** [comment]
Thanks!
