### ISSUE TITLE
How to get real kernel thread tid under occlum?

### ISSUE THREAD

**Issue by lz18064638846** [occlum/occlum#695]
When I try to use gettid syscall in my code to get the kernel thread id of my thread, it turns out that occlum trap this syscall and return self alloc tid, however this is not I wanted.
I wonder how to match my user thread with kernel thread(especially in driver), I would appreciate it if you could help me do so.

**Comment by lz18064638846** [comment]
> @lz18064638846 This requirement breaks Occlum programming mode. May I know why you need it? Maybe we can find an alternative solution.

I want to do some profile work under occlum, like swapping times for each thread, I can print thread id in driver, but I can't find a way to match it with my user thread, thus I can't know which thread is the bottleneck of my benchmark.

**Comment by lz18064638846** [comment]
@guzongmin I have to use occlum because I am running some Java benchmarks

**Comment by guzongmin** [comment]
Close this issue. Occlum is not able to support this requirement as a general feature.
