### ISSUE TITLE
[BUG]Failed to run pytorch demo

### ISSUE THREAD

**Issue by jcsora** [occlum/occlum#721]
# Describe the bug
Failed to run pytorch demo in docker ocntainer.

# To reproduce
1. In occlum docker container:
 `cd /root/demos/pytorch && install_python_with_conda.sh && ./run_pytorch_on_occlum.sh`
It returns: 
`/opt/occlum/build/bin/occlum_build.mk:128: *** multiple target patterns.  Stop.`
After checking, I found that the occlum_build.mk file contained the ":" in the IMAGE_DIRS and IMAGE_FILES.
2. Because `python-occlum/lib/` contained a directory named `pkgConfig:` after using
`conda create --prefix python-occlum -y  python=3.7 pytorch numpy torchvision -c pytorch`
It is the ":" symbol that causes the error. Full path is:
`/root/demos/pytorch/python-occlum/lib/pkgconfig:/tmp/build/80754af9/ncurses_1635849359651/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/share/pkgconfig`.
3. Copy all files in `pkgConfig:` to the `pkgconfig` directory and delete the `pkgconfig:` directory:
```
cp /root/demos/pytorch/python-occlum/lib/pkgconfig:/tmp/build/80754af9/ncurses_1635849359651/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/share/pkgconfig/* /root/demos/pytorch/python-occlum/lib/pkgconfig
rm -rf /root/demos/pytorch/python-occlum/lib/pkgconfig:
```
4.Retry using `cd /root/demos/pytorch && ./run_pytorch_on_occlum.sh`. And then it's blocked at the `occlum run /bin/python3 demo.py` step.

# Expected behavior
Successfully run demo.

# Logs
```
root@3212beaba2be:~/demos/pytorch# ./run_pytorch_on_occlum.sh
Enclave sign-tool: /opt/occlum/sgxsdk-tools/bin/x64/sgx_sign
Enclave sign-key: /opt/occlum/etc/template/Enclave.pem
SGX mode: HW
rm -rf /root/demos/pytorch/occlum_instance/build
Building new image...
[+] Home dir is /root
[-] Open token file /root/enclave.token error! Will create one.
[+] Saved updated launch token!
[+] Init Enclave Successful 4264902524930!
Generate the SEFS image successfully
Building the initfs...
[+] Home dir is /root
[+] Open token file success!
[+] Token file valid!
[+] Init Enclave Successful 4342211936258!
Generate the SEFS image successfully
Building libOS...
Signing the enclave...
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>1048576</StackMaxSize>
    <StackMinSize>1048576</StackMinSize>
    <HeapMaxSize>268435456</HeapMaxSize>
    <HeapMinSize>268435456</HeapMinSize>
    <TCSNum>64</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
    <ReservedMemMaxSize>6291456000</ReservedMemMaxSize>
    <ReservedMemMinSize>6291456000</ReservedMemMinSize>
    <ReservedMemInitSize>6291456000</ReservedMemInitSize>
    <ReservedMemExecutable>1</ReservedMemExecutable>
</EnclaveConfiguration>
tcs_num 64, tcs_max_num 64, tcs_min_pool 1
The required memory is 6630928384B.
The required memory is 0x18b3bf000, 6475516 KB.
Succeed.
Built the Occlum image and enclave successfully
occlum run /bin/python3 demo.py

```

# Environment

- HW: SGX2
- OS: Ubuntu 20.04.3 LTS
- Kernel version: 5.14.0-051400-generic
- Docker image: occlum/occlum:0.24.2-ubuntu18.04
- Occlum version: 0.24.2

**Comment by qzheng527** [comment]
@jcsora Please try apply the [`patch`](https://github.com/occlum/occlum/commit/28baa5b080adefcfcccec2cd82fff4918bd4a4c3).

**Comment by jcsora** [comment]
> @jcsora Please try apply the [`patch`](https://github.com/occlum/occlum/commit/28baa5b080adefcfcccec2cd82fff4918bd4a4c3).

I guess this will have the same effect as if I manually copied files from `/root/demos/pytorch/python-occlum/lib/pkgconfig:` to `/root/demos/pytorch/python-occlum/lib/pkgconfig` and deleted pkgconfig: directory. After using your patch, occlum build is successfully passed, but the execution will still block at step `occlum run /bin/python3 demo.py`.

**Comment by qzheng527** [comment]
> > @jcsora Please try apply the [`patch`](https://github.com/occlum/occlum/commit/28baa5b080adefcfcccec2cd82fff4918bd4a4c3).
> 
> I guess this will have the same effect as if I manually copied files from `/root/demos/pytorch/python-occlum/lib/pkgconfig:` to `/root/demos/pytorch/python-occlum/lib/pkgconfig` and deleted pkgconfig: directory. In fact, after using your patch, occlum build is successfully passed, but the execution will still block at step `occlum run /bin/python3 demo.py`.

There is no such block in my local test nor the github action CI test.
Would you wait for longer time? This demo may take almost 1 min in my NUC (Atom J5005).
And if still block, please run the demo with OCCLUM_LOG_LEVEL=debug.

**Comment by jcsora** [comment]
> > > @jcsora Please try apply the [`patch`](https://github.com/occlum/occlum/commit/28baa5b080adefcfcccec2cd82fff4918bd4a4c3).
> > 
> > 
> > I guess this will have the same effect as if I manually copied files from `/root/demos/pytorch/python-occlum/lib/pkgconfig:` to `/root/demos/pytorch/python-occlum/lib/pkgconfig` and deleted pkgconfig: directory. In fact, after using your patch, occlum build is successfully passed, but the execution will still block at step `occlum run /bin/python3 demo.py`.
> 
> There is no such block in my local test nor the github action CI test. Would you wait for longer time? This demo may take almost 1 min in my NUC (Atom J5005). And if still block, please run the demo with OCCLUM_LOG_LEVEL=debug.

I've tried:
```
cd /root/demos/pytorch/occlum_instance/
OCCLUM_LOG_LEVEL=trace
occlum run /bin/python3 demo.py
```

unfortunately it will block at step `occlum run /bin/python3 demo.py` for more than two days and no log is printed.

**Comment by jcsora** [comment]
> > > @jcsora Please try apply the [`patch`](https://github.com/occlum/occlum/commit/28baa5b080adefcfcccec2cd82fff4918bd4a4c3).
> > 
> > 
> > I guess this will have the same effect as if I manually copied files from `/root/demos/pytorch/python-occlum/lib/pkgconfig:` to `/root/demos/pytorch/python-occlum/lib/pkgconfig` and deleted pkgconfig: directory. In fact, after using your patch, occlum build is successfully passed, but the execution will still block at step `occlum run /bin/python3 demo.py`.
> 
> There is no such block in my local test nor the github action CI test. Would you wait for longer time? This demo may take almost 1 min in my NUC (Atom J5005). And if still block, please run the demo with OCCLUM_LOG_LEVEL=debug.

I tried adding a print.py to `/root/demos/pytorch/occlum_instance/image`, and
```
cd /root/demos/pytorch/occlum_instance/
OCCLUM_LOG_LEVEL=trace
occlum run /bin/python3 print.py
```
the same as before as if python did not call print.py.

**Comment by qzheng527** [comment]
> > > > @jcsora Please try apply the [`patch`](https://github.com/occlum/occlum/commit/28baa5b080adefcfcccec2cd82fff4918bd4a4c3).
> > > 
> > > 
> > > I guess this will have the same effect as if I manually copied files from `/root/demos/pytorch/python-occlum/lib/pkgconfig:` to `/root/demos/pytorch/python-occlum/lib/pkgconfig` and deleted pkgconfig: directory. In fact, after using your patch, occlum build is successfully passed, but the execution will still block at step `occlum run /bin/python3 demo.py`.
> > 
> > 
> > There is no such block in my local test nor the github action CI test. Would you wait for longer time? This demo may take almost 1 min in my NUC (Atom J5005). And if still block, please run the demo with OCCLUM_LOG_LEVEL=debug.
> 
> I tried adding a print.py to `/root/demos/pytorch/occlum_instance/image`, and
> 
> ```
> cd /root/demos/pytorch/occlum_instance/
> OCCLUM_LOG_LEVEL=trace
> occlum run /bin/python3 print.py
> ```
> 
> the same as before as if python did not call print.py.

Please put OCCLUM_LOG_LEVEL=<trace or debug> in the same line with `occlum run`.
For example,  `OCCLUM_LOG_LEVEL=debug occlum run /bin/python3 print.py 2>&1 | tee debug_log`

**Comment by jcsora** [comment]
> > > > > @jcsora Please try apply the [`patch`](https://github.com/occlum/occlum/commit/28baa5b080adefcfcccec2cd82fff4918bd4a4c3).
> > > > 
> > > > 
> > > > I guess this will have the same effect as if I manually copied files from `/root/demos/pytorch/python-occlum/lib/pkgconfig:` to `/root/demos/pytorch/python-occlum/lib/pkgconfig` and deleted pkgconfig: directory. In fact, after using your patch, occlum build is successfully passed, but the execution will still block at step `occlum run /bin/python3 demo.py`.
> > > 
> > > 
> > > There is no such block in my local test nor the github action CI test. Would you wait for longer time? This demo may take almost 1 min in my NUC (Atom J5005). And if still block, please run the demo with OCCLUM_LOG_LEVEL=debug.
> > 
> > 
> > I tried adding a print.py to `/root/demos/pytorch/occlum_instance/image`, and
> > ```
> > cd /root/demos/pytorch/occlum_instance/
> > OCCLUM_LOG_LEVEL=trace
> > occlum run /bin/python3 print.py
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the same as before as if python did not call print.py.
> 
> Please put OCCLUM_LOG_LEVEL= in the same line with `occlum run`. For example, `OCCLUM_LOG_LEVEL=debug occlum run /bin/python3 print.py 2>&1 | tee debug_log`

It still doesn't work, and no logs are written to the `debug_log`

**Comment by qzheng527** [comment]
> > > > > > @jcsora Please try apply the [`patch`](https://github.com/occlum/occlum/commit/28baa5b080adefcfcccec2cd82fff4918bd4a4c3).
> > > > > 
> > > > > 
> > > > > I guess this will have the same effect as if I manually copied files from `/root/demos/pytorch/python-occlum/lib/pkgconfig:` to `/root/demos/pytorch/python-occlum/lib/pkgconfig` and deleted pkgconfig: directory. In fact, after using your patch, occlum build is successfully passed, but the execution will still block at step `occlum run /bin/python3 demo.py`.
> > > > 
> > > > 
> > > > There is no such block in my local test nor the github action CI test. Would you wait for longer time? This demo may take almost 1 min in my NUC (Atom J5005). And if still block, please run the demo with OCCLUM_LOG_LEVEL=debug.
> > > 
> > > 
> > > I tried adding a print.py to `/root/demos/pytorch/occlum_instance/image`, and
> > > ```
> > > cd /root/demos/pytorch/occlum_instance/
> > > OCCLUM_LOG_LEVEL=trace
> > > occlum run /bin/python3 print.py
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > the same as before as if python did not call print.py.
> > 
> > 
> > Please put OCCLUM_LOG_LEVEL= in the same line with `occlum run`. For example, `OCCLUM_LOG_LEVEL=debug occlum run /bin/python3 print.py 2>&1 | tee debug_log`
> 
> It still doesn't work, and no logs are written to the `debug_log`

@jcsora Can run successfully run other demos? Such as demos/python.

**Comment by jcsora** [comment]
> > > > > > > @jcsora Please try apply the [`patch`](https://github.com/occlum/occlum/commit/28baa5b080adefcfcccec2cd82fff4918bd4a4c3).
> > > > > > 
> > > > > > 
> > > > > > I guess this will have the same effect as if I manually copied files from `/root/demos/pytorch/python-occlum/lib/pkgconfig:` to `/root/demos/pytorch/python-occlum/lib/pkgconfig` and deleted pkgconfig: directory. In fact, after using your patch, occlum build is successfully passed, but the execution will still block at step `occlum run /bin/python3 demo.py`.
> > > > > 
> > > > > 
> > > > > There is no such block in my local test nor the github action CI test. Would you wait for longer time? This demo may take almost 1 min in my NUC (Atom J5005). And if still block, please run the demo with OCCLUM_LOG_LEVEL=debug.
> > > > 
> > > > 
> > > > I tried adding a print.py to `/root/demos/pytorch/occlum_instance/image`, and
> > > > ```
> > > > cd /root/demos/pytorch/occlum_instance/
> > > > OCCLUM_LOG_LEVEL=trace
> > > > occlum run /bin/python3 print.py
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > the same as before as if python did not call print.py.
> > > 
> > > 
> > > Please put OCCLUM_LOG_LEVEL= in the same line with `occlum run`. For example, `OCCLUM_LOG_LEVEL=debug occlum run /bin/python3 print.py 2>&1 | tee debug_log`
> > 
> > 
> > It still doesn't work, and no logs are written to the `debug_log`
> 
> @jcsora Can run successfully run other demos? Such as demos/python.

Yes, run ~/demos/python/python_glibc successfully. When I change directory to `~/demos/pytorch/occlum_instance`, there was no result after using `occlum run /bin/python3 -V`.

**Comment by qzheng527** [comment]
@jcsora There is some mismatch between your setup and mine. I could never reproduce the issue you met.
One suggest, in the running occlum/occlum:0.24.2-ubuntu18.04, do a fresh build/install.
Hope this could make us align in the same page.

1. Get the latest Occlum source
```
# git clone https://github.com/occlum/occlum.git
```

2. Build and install
```
# cd occlum
# make submodule && OCCLUM_RELEASE_BUILD=1 make && make install

3. Build and run the pytorch demo
```
# cd demos/pytorch
# ./install_python_with_conda.sh
# OCCLUM_LOG_LEVEL=debug ./run_pytorch_on_occlum.sh
```

**Comment by jcsora** [comment]
> @jcsora There is some mismatch between your setup and mine. I could never reproduce the issue you met. One suggest, in the running occlum/occlum:0.24.2-ubuntu18.04, do a fresh build/install. Hope this could make us align in the same page.
> 
>     1. Get the latest Occlum source
> 
> 
> ```
> # git clone https://github.com/occlum/occlum.git
> ```
> 
>     1. Build and install
> 
> 
> ```
> # cd occlum
> # make submodule && OCCLUM_RELEASE_BUILD=1 make && make install
> ```
> 
>     1. Build and run the pytorch demo
> 
> 
> ```
> # cd demos/pytorch
> # ./install_python_with_conda.sh
> # OCCLUM_LOG_LEVEL=debug ./run_pytorch_on_occlum.sh
> ```

Problem remains the same after reinstalling using latest source code in docker container. But after I built with `occlum build --sgx-mode SIM`, it ran successfully.

**Comment by jcsora** [comment]
> @jcsora There is some mismatch between your setup and mine. I could never reproduce the issue you met. One suggest, in the running occlum/occlum:0.24.2-ubuntu18.04, do a fresh build/install. Hope this could make us align in the same page.
> 
>     1. Get the latest Occlum source
> 
> 
> ```
> # git clone https://github.com/occlum/occlum.git
> ```
> 
>     1. Build and install
> 
> 
> ```
> # cd occlum
> # make submodule && OCCLUM_RELEASE_BUILD=1 make && make install
> ```
> 
>     1. Build and run the pytorch demo
> 
> 
> ```
> # cd demos/pytorch
> # ./install_python_with_conda.sh
> # OCCLUM_LOG_LEVEL=debug ./run_pytorch_on_occlum.sh
> ```

```
[2021-11-09T07:00:19.531Z][DEBUG][T2][#5505][····Stat] fstatat: fs_path: FsPath { Absolute("/opt/python-occlum/lib/python3.7/site-packages/pytz/__init__.cpython-37m-x86_64-li
nux-gnu.so") }, flags: (empty)                                                                                                                                                [2021-11-09T07:00:19.531Z][DEBUG][T2][#5505][····Stat] lookup_inode: cwd: "/", path: "/opt/python-occlum/lib/python3.7/site-packages/pytz/__init__.cpython-37m-x86_64-linux-gn
u.so"                                                                                                                                                                         [2021-11-09T07:00:19.531Z][ERROR][T2][#5505][····Stat] Error = ENOENT (#2, No such file or directory): EntryNotFound
[2021-11-09T07:00:19.531Z][DEBUG][T2][#5506][····Stat] fstatat: fs_path: FsPath { Absolute("/opt/python-occlum/lib/python3.7/site-packages/pytz/__init__.abi3.so") }, flags: (empty)
[2021-11-09T07:00:19.531Z][DEBUG][T2][#5506][····Stat] lookup_inode: cwd: "/", path: "/opt/python-occlum/lib/python3.7/site-packages/pytz/__init__.abi3.so"
[2021-11-09T07:00:19.531Z][ERROR][T2][#5506][····Stat] Error = ENOENT (#2, No such file or directory): EntryNotFound                                                          [2021-11-09T07:00:19.531Z][DEBUG][T2][#5507][····Stat] fstatat: fs_path: FsPath { Absolute("/opt/python-occlum/lib/python3.7/site-packages/pytz/__init__.so") }, flags: (empty
)                                                                                                                                                                             [2021-11-09T07:00:19.531Z][DEBUG][T2][#5507][····Stat] lookup_inode: cwd: "/", path: "/opt/python-occlum/lib/python3.7/site-packages/pytz/__init__.so"
[2021-11-09T07:00:19.531Z][ERROR][T2][#5507][····Stat] Error = ENOENT (#2, No such file or directory): EntryNotFound
[2021-11-09T07:00:19.531Z][DEBUG][T2][#5508][····Stat] fstatat: fs_path: FsPath { Absolute("/opt/python-occlum/lib/python3.7/site-packages/pytz/__init__.py") }, flags: (empty
)

...

[2021-11-09T07:01:34.335Z][ERROR][T2][#24314][···Ioctl] Error = ENOTTY (#25, Not a typewriter): not tty device [line = 248, file = src/fs/inode_file.rs]

```

**Comment by qzheng527** [comment]
> > @jcsora There is some mismatch between your setup and mine. I could never reproduce the issue you met. One suggest, in the running occlum/occlum:0.24.2-ubuntu18.04, do a fresh build/install. Hope this could make us align in the same page.
> > ```
> > 1. Get the latest Occlum source
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > # git clone https://github.com/occlum/occlum.git
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 1. Build and install
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > # cd occlum
> > # make submodule && OCCLUM_RELEASE_BUILD=1 make && make install
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 1. Build and run the pytorch demo
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > # cd demos/pytorch
> > # ./install_python_with_conda.sh
> > # OCCLUM_LOG_LEVEL=debug ./run_pytorch_on_occlum.sh
> > ```
> 
> ```
> [2021-11-09T07:00:19.531Z][DEBUG][T2][#5505][····Stat] fstatat: fs_path: FsPath { Absolute("/opt/python-occlum/lib/python3.7/site-packages/pytz/__init__.cpython-37m-x86_64-li
> nux-gnu.so") }, flags: (empty) 
> [2021-11-09T07:00:19.531Z][DEBUG][T2][#5505][····Stat] lookup_inode: cwd: "/", path: "/opt/python-occlum/lib/python3.7/site-packages/pytz/__init__.cpython-37m-x86_64-linux-gn
> u.so"
> [2021-11-09T07:00:19.531Z][ERROR][T2][#5505][····Stat] Error = ENOENT (#2, No such file or directory): EntryNotFound
> [2021-11-09T07:00:19.531Z][DEBUG][T2][#5506][····Stat] fstatat: fs_path: FsPath { Absolute("/opt/python-occlum/lib/python3.7/site-packages/pytz/__init__.abi3.so") }, flags: (empty)
> [2021-11-09T07:00:19.531Z][DEBUG][T2][#5506][····Stat] lookup_inode: cwd: "/", path: "/opt/python-occlum/lib/python3.7/site-packages/pytz/__init__.abi3.so"
> [2021-11-09T07:00:19.531Z][ERROR][T2][#5506][····Stat] Error = ENOENT (#2, No such file or directory): EntryNotFound
> [2021-11-09T07:00:19.531Z][DEBUG][T2][#5507][····Stat] fstatat: fs_path: FsPath { Absolute("/opt/python-occlum/lib/python3.7/site-packages/pytz/__init__.so") }, flags: (empty
> )
> [2021-11-09T07:00:19.531Z][DEBUG][T2][#5507][····Stat] lookup_inode: cwd: "/", path: "/opt/python-occlum/lib/python3.7/site-packages/pytz/__init__.so"
> [2021-11-09T07:00:19.531Z][ERROR][T2][#5507][····Stat] Error = ENOENT (#2, No such file or directory): EntryNotFound
> [2021-11-09T07:00:19.531Z][DEBUG][T2][#5508][····Stat] fstatat: fs_path: FsPath { Absolute("/opt/python-occlum/lib/python3.7/site-packages/pytz/__init__.py") }, flags: (empty
> )
> 
> ...
> 
> [2021-11-09T07:01:34.335Z][ERROR][T2][#24314][···Ioctl] Error = ENOTTY (#25, Not a typewriter): not tty device [line = 248, file = src/fs/inode_file.rs]
> ```

@jcsora Is the above log from the blocking case?

**Comment by jcsora** [comment]
> > > @jcsora There is some mismatch between your setup and mine. I could never reproduce the issue you met. One suggest, in the running occlum/occlum:0.24.2-ubuntu18.04, do a fresh build/install. Hope this could make us align in the same page.
> > > ```
> > > 1. Get the latest Occlum source
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > # git clone https://github.com/occlum/occlum.git
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > 1. Build and install
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > # cd occlum
> > > # make submodule && OCCLUM_RELEASE_BUILD=1 make && make install
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > 1. Build and run the pytorch demo
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > # cd demos/pytorch
> > > # ./install_python_with_conda.sh
> > > # OCCLUM_LOG_LEVEL=debug ./run_pytorch_on_occlum.sh
> > > ```
> > 
> > 
> > ```
> > [2021-11-09T07:00:19.531Z][DEBUG][T2][#5505][····Stat] fstatat: fs_path: FsPath { Absolute("/opt/python-occlum/lib/python3.7/site-packages/pytz/__init__.cpython-37m-x86_64-li
> > nux-gnu.so") }, flags: (empty) 
> > [2021-11-09T07:00:19.531Z][DEBUG][T2][#5505][····Stat] lookup_inode: cwd: "/", path: "/opt/python-occlum/lib/python3.7/site-packages/pytz/__init__.cpython-37m-x86_64-linux-gn
> > u.so"
> > [2021-11-09T07:00:19.531Z][ERROR][T2][#5505][····Stat] Error = ENOENT (#2, No such file or directory): EntryNotFound
> > [2021-11-09T07:00:19.531Z][DEBUG][T2][#5506][····Stat] fstatat: fs_path: FsPath { Absolute("/opt/python-occlum/lib/python3.7/site-packages/pytz/__init__.abi3.so") }, flags: (empty)
> > [2021-11-09T07:00:19.531Z][DEBUG][T2][#5506][····Stat] lookup_inode: cwd: "/", path: "/opt/python-occlum/lib/python3.7/site-packages/pytz/__init__.abi3.so"
> > [2021-11-09T07:00:19.531Z][ERROR][T2][#5506][····Stat] Error = ENOENT (#2, No such file or directory): EntryNotFound
> > [2021-11-09T07:00:19.531Z][DEBUG][T2][#5507][····Stat] fstatat: fs_path: FsPath { Absolute("/opt/python-occlum/lib/python3.7/site-packages/pytz/__init__.so") }, flags: (empty
> > )
> > [2021-11-09T07:00:19.531Z][DEBUG][T2][#5507][····Stat] lookup_inode: cwd: "/", path: "/opt/python-occlum/lib/python3.7/site-packages/pytz/__init__.so"
> > [2021-11-09T07:00:19.531Z][ERROR][T2][#5507][····Stat] Error = ENOENT (#2, No such file or directory): EntryNotFound
> > [2021-11-09T07:00:19.531Z][DEBUG][T2][#5508][····Stat] fstatat: fs_path: FsPath { Absolute("/opt/python-occlum/lib/python3.7/site-packages/pytz/__init__.py") }, flags: (empty
> > )
> > 
> > ...
> > 
> > [2021-11-09T07:01:34.335Z][ERROR][T2][#24314][···Ioctl] Error = ENOTTY (#25, Not a typewriter): not tty device [line = 248, file = src/fs/inode_file.rs]
> > ```
> 
> @jcsora Is the above log from the blocking case?

Problem has been solved. Pytorch demo need 6000MB to run but my BIOS PRM setting was 2GB. Thank you for your help.
