### ISSUE TITLE
question aboout occlum install

### ISSUE THREAD

**Issue by weitianyuan** [occlum/occlum#727]
Add Git hooks that check Rust code format issues before commits and pushes
git submodule init
git submodule update  --progress
cd deps/serde-json-sgx && git apply ../serde-json-sgx.patch >/dev/null 2>&1 || git apply ../serde-json-sgx.patch -R --check
cd deps/ringbuf && git apply ../ringbuf.patch >/dev/null 2>&1 || git apply ../ringbuf.patch -R --check
cd deps/resolv-conf && git apply ../resolv-conf.patch >/dev/null 2>&1 || git apply ../resolv-conf.patch -R --check
GEN <=  /home/wty/work/occlum/build/internal/tools/protect-integrity/App/Enclave_u.c
CC <= /home/wty/work/occlum/build/internal/tools/protect-integrity/App/Enclave_u.o
App/App.cpp: In function ‘int initialize_enclave()’:
App/App.cpp:174:45: warning: argument to ‘sizeof’ in ‘char* strncpy(char*, const char*, size_t)’ call is the same expression as the source; did you mean to use the size of the destination? [-Wsizeof-pointer-memaccess]
  174 |         strncpy(token_path, TOKEN_FILENAME, sizeof(TOKEN_FILENAME));
      |                                             ^~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/string.h:495,
                 from /home/wty/work/occlum/build/internal/tools/protect-integrity/App/Enclave_u.h:7,
                 from App/App.cpp:1:
In function ‘char* strncpy(char*, const char*, size_t)’,
    inlined from ‘int initialize_enclave()’ at App/App.cpp:169:16:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:34: warning: ‘char* __builtin___strncpy_chk(char*, const char*, long unsigned int, long unsigned int)’ output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
App/App.cpp: In function ‘int initialize_enclave()’:
App/App.cpp:167:20: note: length computed here
  167 |             (strlen(home_dir) + strlen("/") + sizeof(TOKEN_FILENAME) + 1) <= MAX_PATH) {
      |              ~~~~~~^~~~~~~~~~
In file included from /usr/include/string.h:495,
                 from /home/wty/work/occlum/build/internal/tools/protect-integrity/App/Enclave_u.h:7,
                 from App/App.cpp:1:
In function ‘char* strncpy(char*, const char*, size_t)’,
    inlined from ‘int main(int, char**)’ at App/App.cpp:341:20:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:34: warning: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
App/App.cpp: In function ‘int main(int, char**)’:
App/App.cpp:338:44: note: length computed here
  338 |             size_t output_path_len = strlen(input_path) + strlen(output_ext) + 1;
      |                                      ~~~~~~^~~~~~~~~~~~
CXX <= /home/wty/work/occlum/build/internal/tools/protect-integrity/App/App.o
/usr/local/bin/ld: 找不到 -lsgx_urts_sim_with_se_event
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:192：/home/wty/work/occlum/build/bin/occlum-protect-integrity] 错误 1
make[1]: *** [Makefile:10：all] 错误 2
make: *** [Makefile:41：submodule] 错误 2

os:ubuntu20.04 
kernel :Linux version 5.11.0-051100-generic 
how to fix it???

**Comment by guzongmin** [comment]
Please build Occlum with Occlum docker image:
docker pull occlum/occlum:latest-ubuntu18.04

If you want to know the detail, please reference https://github.com/occlum/occlum/blob/master/tools/docker/Dockerfile.ubuntu18.04
