### ISSUE TITLE
typo in pal_log.h

### ISSUE THREAD

**Issue by haosanzi** [occlum/occlum#758]
In https://github.com/occlum/occlum/blob/master/src/pal/src/pal_log.h#L11,

```c
    fprintf(stderr, "[WARM] occlum-pal: " fmt " (line %d, file %s)\n", ##__VA_ARGS__, __LINE__, __FILE__)
```

I think it should be `WARN` rather than `WARM`.

**Comment by guzongmin** [comment]
Thanks for your report
