### ISSUE TITLE
[BUG] Error running bash script in HW mode

### ISSUE THREAD

**Issue by SoulKa** [occlum/occlum#765]
# Describe the bug
Running a simple bash script in HW mode fails. The error is shown below

# To reproduce
1. Create a new occlum instance
2. Create a bash script in file `image/bin/test` with the content `#!/bin/bash` and `echo "Hello world!"` and make it executable
3. Execute `./image/bin/test` with success
4. Execute `occlum build` with success
5. Executing `occlum run /bin/test` fails (error below)

# Expected behavior
The script should work just like in the Docker host OS by echoing "Hello World!"

# Logs
```
thread '<unnamed>' panicked at 'range end index 64 out of range for slice of length 32', /root/occlum/deps/sefs/rcore-fs/src/vfs.rs:211:30
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
             at library/core/src/panicking.rs:96
   2: core::slice::index::slice_end_index_len_fail
             at library/core/src/slice/index.rs:41
   3: rcore_fs::vfs::INode::read_elf64_lazy_as_vec
   4: occlum_libos_core_rs::process::do_spawn::exec_loader::load_file_hdr_to_vec
   5: occlum_libos_core_rs::process::do_spawn::exec_loader::load_exec_file_hdr_to_vec
   6: occlum_libos_core_rs::process::do_spawn::new_process_common
   7: occlum_libos_core_rs::process::do_spawn::do_spawn_common
   8: occlum_libos_core_rs::entry::do_new_process
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
[ERROR] occlum-pal: occlum_ecall_new_process returns EFAULT (line 165, file src/pal_api.c)
```

# Environment

- HW: SGX2
- OS: Ubuntu 18.04 by using the Occlum Docker Image 0.26.1
- Occlum version: 0.26.1

# Possible solution/Implementation
I could successfully run compiled binaries. Does it crash because it's not a real compiled program?

**Comment by jessehui** [comment]
I think you hit a bug here. An easy workaround is to run this command:
`occlum run /bin/bash /bin/test`

We will fix this soon.
