### ISSUE TITLE
docker run error

### ISSUE THREAD

**Issue by ykPrograWorld** [occlum/occlum#778]
when run :
docker run -it --privileged -v /dev/sgx_enclave:/dev/sgx/enclave -v /dev/sgx_provision:/dev/sgx/provision occlum/occlum:latest-ubuntu18.04

show this:

esm_service[14]: [get_driver_type edmm_utility.cpp:111] Failed to open Intel SGX device.

aesm_service[14]: [get_driver_type edmm_utility.cpp:111] Failed to open Intel SGX device.

aesm_service[14]: [load_qe ../qe_logic.cpp:642] Error, call sgx_create_enclave QE fail [load_qe], SGXError:2006.

aesm_service[14]: Failed to load QE3: 0x2006
aesm_service[14]: The server sock is 0x5610d4a30fa0

how to fix it? thank you!

**Comment by guzongmin** [comment]
@ykPrograWorld 
This is the command I used on Ubuntu 18.04 with Intel ICX hardware.
```
docker run --cap-add sys_ptrace -idt -v ~/Source:/local_folder --name occlum_0.26.3 --net=host --device /dev/sgx/enclave --device /dev/sgx/provision occlum/occlum:0.26.3-ubuntu18.04 bash
```
Please check your hardware to confirm it is SGX2 machine.

**Comment by ykPrograWorld** [comment]
> 

Currently docker started successfully, but when building oclum on linux (not in the docker container), when the execution of make submodule error, I would like to ask in the production environment can only be deployed with docker, can not be built on linux local machine it, thank you for your answer

**Comment by ykPrograWorld** [comment]
> @ykPrograWorld This is the command I used on Ubuntu 18.04 (Linux 5.11.0-38-generic x86_64) with Intel ICX hardware.
> 
> ```
> docker run --cap-add sys_ptrace -idt -v ~/Source:/local_folder --name occlum_0.26.3 --net=host --device /dev/sgx/enclave --device /dev/sgx/provision occlum/occlum:0.26.3-ubuntu18.04 bash
> ```
> 
> Please check your hardware to confirm it is SGX2 machine.

One more question, we want to put the fabric (blockchain) in oclum, is this feasible?

**Comment by guzongmin** [comment]
@ykPrograWorld All the things you should do are documented in the https://github.com/occlum/occlum/blob/master/tools/docker/Dockerfile.ubuntu18.04

**Comment by guzongmin** [comment]
> 

Of course, it is a good usage.

**Comment by ykPrograWorld** [comment]
> @ykPrograWorld All the things you should do are documented in the https://github.com/occlum/occlum/blob/master/tools/docker/Dockerfile.ubuntu18.04

Thank you for your answer, it was very helpful to me

**Comment by ykPrograWorld** [comment]
> Of course, it is a good usage.



> Of course, it is a good usage.

Is there a step-by-step procedure or information you can refer to, thank you for your answer

**Comment by guzongmin** [comment]
I have not tried it. You may need to port it by reference to the existing demos.

**Comment by ykPrograWorld** [comment]
> I have not tried it. You may need to port it by reference to the existing demos.

OK, thanks for your answer

**Comment by ykPrograWorld** [comment]
Does Occlum not support centos7.6 now?

**Comment by ykPrograWorld** [comment]
> > I have not tried it. You may need to port it by reference to the existing demos.
> 
> OK, thanks for your answer

Does Occlum not support centos7.6 now?

**Comment by guzongmin** [comment]
We stop testing Occlum on centos7.6, because it is not officially supported by SGX SDK now.

**Comment by ykPrograWorld** [comment]
> We stop testing Occlum on centos7.6, because it is not officially supported by SGX SDK now.

Thank you very much
