### ISSUE TITLE
Python compiling with occlum-gcc fails

### ISSUE THREAD

**Issue by chigarovae** [occlum/occlum#788]
Hi! Trying to compile Python with occlum-gcc to use it in an enclave for some testing, bit compilation fails on posixmodule:

`
/Include/internal  -I. -I./Include    -DPy_BUILD_CORE_BUILTIN  -DPy_BUILD_CORE_BUILTIN -I./Include/internal -c ./Modules/posixmodule.c -o Modules/posixmodule.o
./Modules/posixmodule.c: In function 'os_preadv_impl':
./Modules/posixmodule.c:9704:13: error: implicit declaration of function 'preadv2'; did you mean 'preadv'? [-Werror=implicit-function-declaration]
         n = preadv2(fd, iov, cnt, offset, flags);
             ^~~~~~~
             preadv
./Modules/posixmodule.c: In function 'os_pwritev_impl':
./Modules/posixmodule.c:10346:18: error: implicit declaration of function 'pwritev2'; did you mean 'pwritev'? [-Werror=implicit-function-declaration]
         result = pwritev2(fd, iov, cnt, offset, flags);
                  ^~~~~~~~
                  pwritev
In file included from ./Include/Python.h:126,
                 from ./Modules/posixmodule.c:12:
./Modules/posixmodule.c: In function 'all_ins':
./Modules/posixmodule.c:15334:33: error: 'RTLD_DEEPBIND' undeclared (first use in this function); did you mean 'RTLD_DEFAULT'?
     if (PyModule_AddIntMacro(m, RTLD_DEEPBIND)) return -1;
                                 ^~~~~~~~~~~~~
./Include/modsupport.h:154:67: note: in definition of macro 'PyModule_AddIntMacro'
 #define PyModule_AddIntMacro(m, c) PyModule_AddIntConstant(m, #c, c)
                                                                   ^
./Modules/posixmodule.c:15334:33: note: each undeclared identifier is reported only once for each function it appears in
     if (PyModule_AddIntMacro(m, RTLD_DEEPBIND)) return -1;
                                 ^~~~~~~~~~~~~
./Include/modsupport.h:154:67: note: in definition of macro 'PyModule_AddIntMacro'
 #define PyModule_AddIntMacro(m, c) PyModule_AddIntConstant(m, #c, c)
                                                                   ^
cc1: some warnings being treated as errors
Makefile:2046: recipe for target 'Modules/posixmodule.o' failed
make: *** [Modules/posixmodule.o] Error 1
`

I'm using ubuntu 18.04 docker image with occlum and SGX SDK. Tried multiple releases of python - all of them failed to compile on posixmodule with occlum-gcc, but with common gcc compiling works fine.

Thanks in advance!

**Comment by guzongmin** [comment]
@chigarovae the occlum-gcc is only a script to help user link musl as libc. If you are able to use normal gcc, you can just use it.
