### ISSUE TITLE
Support XGboost

### ISSUE THREAD

**Issue by Yourens** [occlum/occlum#80]
1. system call used by xgboost example
2. external and internal libraries used by xgboost.

**Comment by Yourens** [comment]
Internal libraries used:
librabit.a and libdmlc.a
This two libraries will be build with xgboost. If we want to use xgboost statically, link them statically.
External libraries used:
pthread math and gomp.

For gomp, cpuid support is requested.

**Comment by Yourens** [comment]
new syscall used by xgboost example:
sched_getaffinity
set_robust_list
getdents
mprotect
madvise
futex

**Comment by tatetian** [comment]
These syscalls are all ok

**Comment by tatetian** [comment]
Done
