### ISSUE TITLE
Error in Launching Occlum-Vault with different Storage Configuration

### ISSUE THREAD

**Issue by dzobbe** [occlum/occlum#824]
Hello folks, 

I am trying to deploy a Vault solution secured with Occlum using an integrated storage instead of the file storage. I changed the configuration of vault as follows:

```ui = true
disable_mlock = true

storage "raft" {
  path = "/vault/data"
  node_id = "raft_node_1"
}
cluster_addr = "[::]:8201"

listener "tcp" {
  address     = "[::]:8200"
  tls_disable = 1
}
```

And also added the path in the compose file:

```includes:
  - base.yaml
targets:
  - target: /bin
    copy:
      - files:
        - ../source_code/bin/vault
  - target: /
    mkdirs:
      - etc/ssl
      - vault/data 
 ```

However, when running I am getting this error:

`2022/02/25 10:33:15 bolt.Close(): funlock error: function not implemented
Error initializing storage of type raft: failed to create fsm: failed to open bolt file: function not implemented
2022-02-25T10:33:15.676Z [INFO]  proxy environment: http_proxy="\"\"" https_proxy="\"\"" no_proxy="\"\""`

Any suggestion? Thanks. 

Giovanni

**Comment by guzongmin** [comment]
@dzobbe Thanks for you to report this issue. Can you please open Occlum trace and share the trace out?
[https://github.com/occlum/occlum#how-to-debug](https://github.com/occlum/occlum#how-to-debug)

**Comment by dzobbe** [comment]
Of course. Here it is attached.

[trace.log](https://github.com/occlum/occlum/files/8153794/trace.log)

**Comment by guzongmin** [comment]
@dzobbe Thank you very much. I read the trace and find that your application depends on flock syscall. We will add it soon.

**Comment by dzobbe** [comment]
Ah great. Thanks for this info. Do you already have an ETA on this extension?
