### ISSUE TITLE
My SGX framework for distributed Machine Learning Training Process

### ISSUE THREAD

**Issue by LinbinYoung** [occlum/occlum#84]
I use Intel SGX and ECDH to secure distributed Machine Learning Training Process.

I hope to learn more about SGX and Occlum from you!

You can find more details about my project here: https://github.com/LinbinYoung/Distributed_TEEML_POC

**Comment by tatetian** [comment]
Thanks for your interest in Occlum and sharing your personal project.

TEE-based secure/privacy-preserving ML is a hot topic. There are a number of research papers and open-source projects that work on this direction. At Ant Financial, we also have teams that are working on distributed TEE-protected ML. I didn't dive into your code. But I believe they have build systems similar to your project (in a sense) and deployed in production environments. That being said, there are still many technical challenges and open problems.

By the way, we are hiring aggressively. If you're interested in an intern/full-time job at Ant Financial or Alibaba, send your resume to me (tate.thl@antfin.com) or we could talk via WeChat (my ID: tatetian).

**Comment by LinbinYoung** [comment]
> Thanks for your interest in Occlum and sharing your personal project.
> 
> TEE-based secure/privacy-preserving ML is a hot topic. There are a number of research papers and open-source projects that work on this direction. At Ant Financial, we also have teams that are working on distributed TEE-protected ML. I didn't dive into your code. But I believe they have build systems similar to your project (in a sense) and deployed in production environments. That being said, there are still many technical challenges and open problems.
> 
> By the way, we are hiring aggressively. If you're interested in an intern/full-time job at Ant Financial or Alibaba, send your resume to me ([tate.thl@antfin.com](mailto:tate.thl@antfin.com)) or we could talk via WeChat (my ID: tatetian).

Thanks very much, Mr Tian. I really want to dive deep and learn more about combining TEE with ML training. I have sent my resume to your mail at (tate.thl@antfin.com).

**Comment by tatetian** [comment]
Great. Then we can talk and I will close this issue.
