### ISSUE TITLE
Whether a Occlum instance directory can hold two executable binarys to run?

### ISSUE THREAD

**Issue by lwxiaowuge** [occlum/occlum#849]
hello:
**1，Does a Occlum instance directory correspond to only one binary, or does a Occlum instance directory contain multiple binarys? If yes, do they all belong to the security zone?
2，If a Occlum instance directory exist two binarys,Can the host OS program call occlum_pal_exec() to execute the two binary files outside?
3，What other ways do the outer enclave programs communicate with the Occlum program besides sharing memory?**
    Thanks!

**Comment by guzongmin** [comment]
Add your questions and answers in the wiki
https://github.com/occlum/occlum/wiki/Q&A#q-does-an-occlum-instance-directory-correspond-to-only-one-binary-or-does-an-occlum-instance-directory-contain-multiple-binaries-if-yes-do-they-all-belong-to-the-security-zone

**Comment by lwxiaowuge** [comment]
Yes，thank you for report.
But for the thired question answered,I went to know the way untrust application process in the host OS communicate with the Occlum process in a enclave.

**Comment by guzongmin** [comment]
You could use socket (IP based) to communicate between trusted and untrusted applications.
In the next generation Occlum (coming soon), user is able to use UDS.

**Comment by lwxiaowuge** [comment]
If there are two occlum_instance directories, each containing one binary,such as:occlum_instance01 is contained binary A,occlum_instance02 is contained binary B.
Could the untrust application call occlum_PAL_init and OCclum_pal_exec, Occlum_pal_destroy executes both binaries respectively？
The pseudocode is as follows:
`void funcA()
{
	const char *cmd_path = "/bin/A";
	...
	   // Init Occlum PAL
    occlum_pal_attr_t pal_attr = OCCLUM_PAL_ATTR_INITVAL;
    pal_attr.instance_dir = "occlum_instance01";
    pal_attr.log_level = "off";
    if (occlum_pal_init(&pal_attr) < 0) {
        printf("%s %d error.\n",__func__,__LINE__);      
        return EXIT_FAILURE;
    }
	...
	 if (occlum_pal_exec(&exec_args) < 0) {
        printf("%s %d error.\n",__func__,__LINE__);
        return EXIT_FAILURE;
    }
	
	// Destroy Occlum PAL
    occlum_pal_destroy();
}

void funcB()
{
	const char *cmd_path = "/bin/B";
	...
	   // Init Occlum PAL
    occlum_pal_attr_t pal_attr = OCCLUM_PAL_ATTR_INITVAL;
    pal_attr.instance_dir = "occlum_instance02";
    pal_attr.log_level = "off";
    if (occlum_pal_init(&pal_attr) < 0) {
        printf("%s %d error.\n",__func__,__LINE__);      
        return EXIT_FAILURE;
    }
	...
	 if (occlum_pal_exec(&exec_args) < 0) {
        printf("%s %d error.\n",__func__,__LINE__);
        return EXIT_FAILURE;
    }
	
	// Destroy Occlum PAL
    occlum_pal_destroy();
}

int main()
{
	funcA()
	funcB();
	return 0;
}`
I verified that funcB cannot be called after funcA is called,why?

**Comment by guzongmin** [comment]
Technically, you can do it now. 
But Occlum would stop to support such a case soon.
Can you please tell us what is the usage?

**Comment by lwxiaowuge** [comment]
Yes,This is just an example of my own thinking,well,I wanted to test if it worked。
