### ISSUE TITLE
Are the threads running in Occlum actually concurrent?

### ISSUE THREAD

**Issue by lwxiaowuge** [occlum/occlum#856]
hi:
    For all I know,Occlum is multitasking inside a single enclave of intel SGX,My question is that the CPU of my computer is multi-core,So were multiple threads running on SMP truly concurrent in Occlum?

**Comment by guzongmin** [comment]
@lwxiaowuge Please check the answer at https://github.com/occlum/occlum/wiki/Q&A#q-how-many-cpu-cores-can-be-used-inside-occlumenclave

**Comment by lwxiaowuge** [comment]
Thank you for your answer,Our group studied occlum yesterday, and we had one more question。
The ELF loader of Occlum LibOS checks that the ELF binaries to be loaded are verified and signed by the Occlum verifier,
How it verified and signed the ELF binaries？Is there a key in enclave of ELF binaries, Sign according to this key?

**Comment by guzongmin** [comment]
In the current implementation, the customer binaries only be signed with signing tool. It is not verified. So user should take the responsibly to make sure the binaries are good citizens. Occlum reuse the Intel SGX SDK signing tool to sign the enclave.   Any change of the customer binary would change the enclave MREnclave value.

**Comment by lwxiaowuge** [comment]
Thank you for your answer.
