### ISSUE TITLE
Open file issue

### ISSUE THREAD

**Issue by light1021** [occlum/occlum#86]
Hi everyone：
I’m trying to add sqlite3 as a demo of occlum. But I find out that when running with occlum sqlite3  couldn't open file. The error is 

> Error: unable to open database "mydatabase": unable to open database file.

Then I tested the file read and write interface with a very simple c++ code as shown blow:
`
#include <iostream>
#include <fstream>

#include <string>

int main() {
        std::string filename = "Test.b";
        // prepare a file to read
        double d = 3.14;
        std::ofstream(filename, std::ios::binary).write(reinterpret_cast<char*>(&d), sizeof d)
                << 123 << "abc";
        // open file for reading
        std::ifstream istrm(filename, std::ios::binary);
        if (!istrm.is_open()) {
                std::cout << "failed to open " << filename << '\n';
        } else {
                double d;
                istrm.read(reinterpret_cast<char*>(&d), sizeof d); // binary input
                int n;
                std::string s;
                if (istrm >> n >> s)                               // text input
                        std::cout << "read back from file: " << d << ' ' << n << ' ' << s << '\n';
        }
}
`
1. compile the code with occulm-g++
2. mkdir workspace
3. do occlum init in workspace
4. copy the build target to image/bin
5. do occlum build in workspace
6. run target with occlum run /bin/target
It reports the same error:

> failed to open Test.b

So what's wrong with this? And how can I solve it?

**Comment by tatetian** [comment]
Hi @light1021 

Could you try to change the path to `/root/Test.b` and try again?

The thing is that currently Occlum loads the Occlum FS image and mounts it as an integrity-only FS at `/`. As the FS is integrity-only (not encrypted), any writes to the FS would leak user secrets. So we set the integrity-only FS as read-only. 

There is a writable, encrypted FS mounted at `/root/`. This directory is where the user program are supposed to write data.

In the near future (hopefully, the next release), we will support UnionFS. By introducing this new type of FS, we will support file writes to `/` without  leaking any secrets.

**Comment by light1021** [comment]
Hi @tatetian 
I changed the path in my test code and it runs. But unfortunately, when I try this with sqlite3,  new error occurred :

> CREATE TABLE COMPANY(
   ID INT PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL,
   AGE            INT     NOT NULL,
   ADDRESS        CHAR(50),
   SALARY         REAL
);
Error: near line 1: disk I/O error

**Comment by tatetian** [comment]
We are making some progress. That's good.

Could you share with us code that can easily reproduce the problem? Something like the demos that we include in the project.

We haven't tested Occlum with sqlite, yet. Thanks for reporting the problem.

**Comment by light1021** [comment]
Hi @tatetian 

You can use this code for test 
[https://github.com/light1021/occlum/tree/master/demos](url)
Use CMakeLists.txt for compiling.

**Comment by tatetian** [comment]
So the problem is that the sqlite3 command-line shell program failed to execute the "CREATE TABLE" command?

**Comment by light1021** [comment]
Yes, When we run "CREATE TABLE" in sqlite3 shell, it will write the database file. 

> root@df67c2ac29a2:~/sqlite/build/workspqce# occlum run /bin/sqlite3 /root/test.db
-- warning: cannot find home directory; cannot read ~/.sqliterc
CREATE TABLE COMPANY(
ID INT PRIMARY KEY NOT NULL,
NAME TEXT NOT NULL,
AGE INT NOT NULL,
ADDRESS CHAR(50),
SALARY REAL
);
Error: near line 1: disk I/O error

**Comment by tatetian** [comment]
Got you. We will look into the problem.

**Comment by liqinggd** [comment]
Hi @light1021 

Please check out the demo in https://github.com/occlum/occlum/tree/master/demos/sqlite

**Comment by guzongmin** [comment]
> Hi everyone：
> I’m trying to add sqlite3 as a demo of occlum. But I find out that when running with occlum sqlite3 couldn't open file. The error is
> 
> > Error: unable to open database "mydatabase": unable to open database file.
> 
> Then I tested the file read and write interface with a very simple c++ code as shown blow:
> `
> #include
> #include
> 
> #include
> 
> int main() {
> std::string filename = "Test.b";
> // prepare a file to read
> double d = 3.14;
> std::ofstream(filename, std::ios::binary).write(reinterpret_cast<char*>(&d), sizeof d)
> << 123 << "abc";
> // open file for reading
> std::ifstream istrm(filename, std::ios::binary);
> if (!istrm.is_open()) {
> std::cout << "failed to open " << filename << '\n';
> } else {
> double d;
> istrm.read(reinterpret_cast<char*>(&d), sizeof d); // binary input
> int n;
> std::string s;
> if (istrm >> n >> s) // text input
> std::cout << "read back from file: " << d << ' ' << n << ' ' << s << '\n';
> }
> }
> `
> 
> 1. compile the code with occulm-g++
> 2. mkdir workspace
> 3. do occlum init in workspace
> 4. copy the build target to image/bin
> 5. do occlum build in workspace
> 6. run target with occlum run /bin/target
>    It reports the same error:
> 
> > failed to open Test.b
> 
> So what's wrong with this? And how can I solve it?

We have solved this issue. Tested with your simple demo. Please try Occlum 0.16.0 .
