### ISSUE TITLE
Failed to build on Ubuntu 18.04

### ISSUE THREAD

**Issue by andyzyb** [occlum/occlum#88]
"make submodule" failed with

error: failed to run custom build command for `fuse v0.3.1`
process didn't exit successfully: `/home/andy/src/occlum/deps/sefs/sefs-fuse/app/target/release/build/fuse-0aba6809738ce801/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"fuse\" \"fuse >= 2.6.0\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package fuse was not found in the pkg-config search path.\nPerhaps you should add the directory containing `fuse.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'fuse\' found\nPackage fuse was not found in the pkg-config search path.\nPerhaps you should add the directory containing `fuse.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'fuse\' found\n" } }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by andyzyb** [comment]
Looks it needs to use docker environment, or install more dependency.

**Comment by Yourens** [comment]
@tatetian told u. You said:"impossible, work perfectly on my machine.".

**Comment by danintel** [comment]
See
https://github.com/harababurel/gcsf/issues/9
https://github.com/zargony/rust-fuse/issues/69

You may need to install a package:
`apt install libfuse-dev`

**Comment by tatetian** [comment]
Thanks for reporting the issue on Ubuntu 18.04.

We will provide an official Dockerfile and Docker image for Ubuntu 18.04 in the next release.

**Comment by tatetian** [comment]
The new release of version 0.9.0 has provided Dockerfile and Docker image for Ubuntu 18.04.

**Comment by tatetian** [comment]
Since version 0.9.0, Occlum supports Ubuntu 18.04 officially and provides Dockerfiles and Docker image for Ubuntu 18.04.
