### ISSUE TITLE
 had a problem certifying remote attestation certificates in Docker

### ISSUE THREAD

**Issue by lwxiaowuge** [occlum/occlum#894]
1,We had a problem certifying remote attestation certificates in Docker,The software and hardware environments are as follows:
Hardware:使用DELL品牌机，型号vostro 3681,11代I5 10400 CPU
Software:ubuntu 20.04 + occlum docoer20.04 
          When remote attestation app was executed in docker,the intel attestation service retur CONFIGURATION_AND_SW_HARDENING_NEEDED of status code in isvEnclaveQuoteStatus of field name,which was requested Report Data by intel attestation service.
About explain of CONFIGURATION_AND_SW_HARDENING_NEEDED as follows:
CONFIGURATION_AND_SW_HARDENING_NEEDED –
the EPID signature of the ISV enclave QUOTE has been
verified correctly but additional configuration for the
platform and SW Hardening in the attesting SGX
enclaves may be needed. The platform has not been
identified as compromised and thus it is not revoked. It
is up to the Service Provider to decide whether or not
to trust the content of the QUOTE. The relying party
should also evaluate the potential risk of an attack
leveraging the relevant issues on the attestation
enclave, and whether the attesting enclave employs
adequate software hardening to mitigate the risk.

2,Which PC or Server remote attestation return OK of status code?so we need to be able to use certified machines in the project.
      Thanks!

**Comment by guzongmin** [comment]
You need to update the BIOS to adopt the latest SGX patch. Please contact the HW provider (DELL) for the new BIOS or get an environment that supports SGX.

**Comment by lwxiaowuge** [comment]
We have already updated the newest BIOS Version,Do you have any recommended PC or Server that can be verified RA remotely?

**Comment by guzongmin** [comment]
You can try SGX machines on Alibaba Cloud or Microsoft Azure.

**Comment by lwxiaowuge** [comment]
OK，Thanks!
