### ISSUE TITLE
Iago attacks and supported syscalls

### ISSUE THREAD

**Issue by dimakuv** [occlum/occlum#91]
I was reading your Occlum paper (congrats on being accepted to ASPLOS!) and browsing through the code here.

One thing that I do not fully understand is what is your position on Iago attacks? I didn't find any discussion of this in the paper, and I also didn't notice any particular sanitization of syscalls in the source code. It looks that most syscalls (except the ones for objects implemented entirely inside Occlum, like pipes and socketpairs) are more or less forwarded to the host. Could you give any estimate on how many syscalls are resolved in the host and how are they protected?

I observed some syscalls are implemented under `Pal/` as explicit OCALLs, and some are implemented under `LibOS/` as more opaque OCALLs `libc::ocall::...`. What is the reason for this separation? What happens to `libc::ocall`s?

Also, do I understand correctly that there is no mechanism in Occlum for the enclavized application to communicate with other (host or other-enclave) applications? It seems objects like pipes and socketpairs and UNIX sockets are resolved entirely in LibOS. Is my understanding correct?

**Comment by tatetian** [comment]
Hi @dimakuv 

Thanks for your interest in Occlum.

As Occlum is a LibOS for SGX, the security is of paramount importance. The reason that we didn't address Iago attacks in the paper is not that Iago attacks are unimportant, but these attacks are well known and have been addressed by existing LibOSes. In a research paper, we want to focus on novel issues that are specific to Occlum.

The Occlum project is still in the early stage. Before all known security issues, including Igao attacks, are addressed, we won't claim Occlum 1.0.0 (the current version is 0.9.0, the next one is 0.10.0, not 1.0.0). That said, we have done a lot to defend against the untrusted world. Some examples are

1. All file data and metadata of the rootfs is integrity protected transparently under the mount point `/` (see the `mount` key in `Occlum.json`);
2. All file data and metadata are encrypted transparently under the mount point `/root` (see the `mount` key in `Occlum.json`);
3. Environment variables can be trusted (see the `env` key in `Occlum.json`);
4. Only selected programs can be executed with `occlum run` from the outside (see the `entry_points` key in `Occlum.json`);
5.  There are only two ECalls and a dozen of OCalls (excluding those defined by Intel SGX SDK and Rust SGX SDK);
6. The boundary between C code (e.g., ECall/OCall) and Rust code are crystal clear with Rust's `unsafe` keyword and all C data types are explicitly converted to Rust's safe data types before using. It is during this conversion that some pointer checks and sanity checks have been done, but shall be done more thoroughly in the future.

Regarding with cross-enclave communication, the trusted apps running upon Occlum can communicate with host or enclave apps through
1. TCP sockets;
2. Host FS (the `/host` mount point, see the `mount` key in `Occlum.json`);
3. Shared memory (see the embedded mode demo under `demos/embedded_mode`).

We will provide other means for cross-enclave communication.
