### ISSUE TITLE
occlum-g++ Compilation failed

### ISSUE THREAD

**Issue by chenzhijun45** [occlum/occlum#949]
I did the following in docker(occlum/occlum:latest-ubuntu20.04):

It can be compiled with g++, but it fails to compile with cluster-g++, and the GMP library cannot be found.

If I copy the g++ compiled file test to /image/bin, Libgmp so. 10 not found.

What can I do to implement it correctly?

**Comment by liqinggd** [comment]
The occlum-g++ use musl as the libc, so the libs your application depends on should be compiled and installed into `/usr/local/occlum/x86_64-linux-musl/lib`. Then occlum-g++ can find the libs.

**Comment by chenzhijun45** [comment]
@liqinggd 
Thank you for your answer,I've done it.
But, The following exceptions occur:
x86_64-linux-musl/lib/libgmp.so not found.
x86_64-linux-musl/lib/libgmp.so: undefined to strtol@GLIBC_2.2.5.
Is it because I failed to compile, but you can see that the libgmp.so file exists in the /usr/local/occlum/x86_64-linux-musl/lib/ directory.

**Comment by liqinggd** [comment]
@chenzhijun45 Maybe you misuse the libs, it seems that the library is a Glibc version.

BTW, Occlum also supports Glibc, you can just compile the app with g++.

**Comment by chenzhijun45** [comment]
@liqinggd Thanks, Does that mean I have to use the GMP Library of musl version.

**Comment by liqinggd** [comment]
Correct, it means that you have to use the GMP Library of musl version

**Comment by chenzhijun45** [comment]
@liqinggd  Thank you for your answer! But, I am on GMP official website (https://gmplib.org/download/gmp/) unable to find the version of GMP for musl. I'm not familiar with c++. I really don't know how to solve this problem. The following is the process of compile GMP:
Start docker: sudo docker run -it --name occlum occlum/occlum:latest-ubuntu20.04 /bin/bash.
Compile GMP to /usr/local/occlum/x86_64-linux-musl/lib.
./configure --prefix=/usr/local/occlum/x86_64-linux-musl/ --enable-cxx
`make 
make chek
sudo make isntall`
I tried to compile GMP to different locations, but it still didn't work. 
for example: ./configure --prefix=/usr/local/occlum/x86_64-linux-musl/lib --enable-cxx  ./configure --prefix=/usr/local/occlum/x86_64-linux-musl/bin --enable-cxx

Can you give an example of how occlum-g++ uses GMP?

**Comment by liqinggd** [comment]
I guess you should set the compiler for GMP when building it. Maybe you can  reference https://github.com/occlum/occlum/blob/master/tools/toolchains/musl-gcc/install_zlib.sh as an example
