### ISSUE TITLE
Where should I put the resource file

### ISSUE THREAD

**Issue by chenzhijun45** [occlum/occlum#952]
If my program needs to read a.txt, Where should I put a.txt? I tried to copy it to the ${occlum_isntance}/image/ directory, but it didn't work.

**Comment by qzheng527** [comment]
@chenzhijun45 After the copy, did you do `occlum build` ?

**Comment by chenzhijun45** [comment]
> @chenzhijun45 After the copy, did you do `occlum build` ?

Thank you very much for your answer. I made a mistake.
