### ISSUE TITLE
Remote attestation and function call via Occlum

### ISSUE THREAD

**Issue by lemonviv** [occlum/occlum#96]
Hi Occlum Team,

It seems that the current remote attestation demo only provides functionality that gets quote from the local enclave and attests the quote with IAS. Do you have any plan to support the complete interactive RA process, e.g., letting a client to verify a remote enclave-based server, similar to what the [sample code](https://github.com/intel/linux-sgx/tree/master/SampleCode/RemoteAttestation) Intel sgx provided? 

Besides, is there any way for another function to call an occlum program? For example, if there is a program A that is run with occlum, and there is another function B wants to call A to obtain the output of A and do the rest of executions. Due to some limitations, A and B cannot be combined into a whole program and run directly with occlum. 

Any suggestion would be highly appreciated.

Thanks and best regards,
Yuncheng

**Comment by guzongmin** [comment]
Hi Yuncheng,
     We do plan to provide the RA support. Please wait for a while.
     About the usage you mensioned. Are you talking about the usage below?  "A is runing inside occlum, but B is not. And you want B to communicate with A."

Thanks
Zongmin

**Comment by lemonviv** [comment]
Hi Zongmin,

Thanks for the quick reply. That would be great to support RA. 

Yes, from the demos, occlum takes the executable program as input and use `occlum run` to execute it, seems not straightforward to let B communicate with A? 

Thanks and best regards,
Yuncheng

**Comment by guzongmin** [comment]
Hi Yuncheng,
       A is running inside enclave, so A is protected. B is a normal application, which is not protected. B could be any application, even controlled by a hacker. So it is by design, B is not able to  communicate with A by shared memory or other similar things.
      I think you can run A as a web server, then B can send requests to A.
      But I think your requirement is reasonable. We will seriously think about it.

Thanks
Zongmin

**Comment by tatetian** [comment]
@lemonviv 

Check out the demo of [the embedded mode](https://github.com/occlum/occlum/tree/master/demos/embedded_mode). It demonstrates how B can control the lifecycle of A and communicate with A through shared (untrusted) memory.

**Comment by lemonviv** [comment]
@guzongmin, thank you. Yes, a web server might be a solution.

@tatetian, thank you. Yeah, linking Occlum as a shared library is the solution what I expect, it could let B control the lifecycle of A. My concern is that the communication is unidirectional since B can only pass arguments to A but cannot directly receive the output of A (not sure if understand correctly here, please correct me if I am wrong), thus the interaction is not like the SGX Ecall supports (maybe because of different design goals as Zongmin said).

**Comment by tatetian** [comment]
@lemonviv Yes, we have also observed the need for a ECall/OCall-like mechanism for the embedded mode. This feature is on our roadmap, but we haven't settled with its design, yet. If you have any idea, we would like to hear from you.

**Comment by lemonviv** [comment]
Thank you. Sorry I forgot to close this issue.
