### ISSUE TITLE
[BUG] Element is not recognized - "PKRU".

### ISSUE THREAD

**Issue by jingleizhang** [occlum/occlum#964]
# Describe the bug
build error: Element is not recognized - "PKRU".

# To reproduce
1. cd demos/hello_cc
2. mkdir occlum_workspace && cd occlum_workspace
3. occlum init && rm -rf image
4. copy_bom -f ../hello.yaml --root image --include-dir /opt/occlum/etc/template
5. occlum build

# Logs

Element is not recognized - "PKRU".
Configuration file format is not correct.

# Environment

- HW: SGX2
- OS: Ubuntu 20.04
- Occlum version: master branch, commit 8803969f1687c31e37e3eeb3c780f1e79526ddb1
- The CPU doesn't support PKU: The cmd 'cat /proc/cpuinfo | grep pku' and 'cat /proc/cpuinfo | grep ospke' returns nothing

# Possible solution/Implementation
Not obligatory, but suggest a fix/reason for the bug.

**Comment by Bonjourz** [comment]
Hi @jingleizhang, could you show the version of docker image Occlum runs on?

**Comment by jingleizhang** [comment]
The build error is solved when I downgraded to the tag: v0.27.3.

**Comment by jingleizhang** [comment]
Hey @Bonjourz , I built them from source codes.

**Comment by Bonjourz** [comment]
I suspect the the Intel SGX SDK is not the latest one in your docker environment. 

> The build error is solved when I downgraded to the tag: v0.27.3.

This is a way to solve such issue. Glad to see you have solved it 😁.

Another way to solve it is that build the Occlum in `occlum/occlum:0.28.0-ubuntu20.04` docker images. (Start container by typing `docker run -it ... occlum/occlum:0.28.0-ubuntu20.04`).

We will upgrade the Intel SGX SDK in the latest version of docker image (`occlum/occlum:latest-ubuntu20.04`) soon. Thank you for reporting it!

**Comment by jingleizhang** [comment]
Thanks! I'll close this issue.
