### ISSUE TITLE
[BUG] docker: Error response from daemon: failed to create shim task: OCI runtime create failed

### ISSUE THREAD

**Issue by morning21** [occlum/occlum#973]
# Error: Cannot run the occlum-app image after being generated

1. I followed the first four steps from the [introduction](https://github.com/occlum/occlum#hello-occlum), and I can run hello_world successfully.
2. I followed the steps from [here](https://github.com/occlum/occlum/blob/master/docs/rune_quick_start.md#building-occlum-container-image) and generate the image successfully.
3. When I execute the following command, the error is triggered.

## Log
```bash
user@host:~/occulum-test/occlum-instance$ docker run -it --rm --runtime=rune  \
 -e ENCLAVE_TYPE=intelSgx   \
 -e ENCLAVE_RUNTIME_PATH=/opt/occlum/build/lib/libocclum-pal.so   \
 -e ENCLAVE_RUNTIME_ARGS=occlum_instance   occlum-app

docker: Error response from daemon: failed to create shim task: OCI runtime create failed: container_linux.go:309: 
starting container process caused: process_linux.go:629: enclave init caused:: unknown.
```

# Environment

- HW: [SGX2] 
- OS: [Ubuntu20.04]
- Occlum version: [0.28.0]  (follow the [guide](https://github.com/occlum/occlum/blob/master/docs/install_occlum_packages.md))

# Additional context
```bash
user@host:~/occulum-test/occlum-instance$ docker version

Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:57 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:03 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.2
  GitCommit:        de8046a5501db9e0e478e1c10cbcfb21af4c6b2d
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.0-20-g52de29d7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Looking forward to your reply. Thank you very much.

**Comment by qzheng527** [comment]
@morning21 Did you install rune in your host environment?
https://github.com/occlum/occlum/blob/master/docs/rune_quick_start.md#requirements

Also, please follow https://github.com/occlum/occlum/blob/master/docs/rune_quick_start.md#configuring-oci-runtime-rune-for-docker to configure rune.

**Comment by morning21** [comment]
@qzheng527 

Thanks for your response.
For the installation of rune, I have tried the [rune_quick_start](https://github.com/occlum/occlum/blob/master/docs/rune_quick_start.md#requirements). When I input 'sudo apt update', 'Release' does not have a Release file.

Thus, I tried the installation reference to [inclavare-container](https://github.com/inclavare-containers/inclavare-containers/tree/master/rune?spm=a2c63.p38356.0.0.3efe6cceGShw0C#rune).
Furhter, I configured the docker/daemon.json as the [tutorial link](https://github.com/occlum/occlum/blob/master/docs/rune_quick_start.md#configuring-oci-runtime-rune-for-docker).

So, that is to say, the two rune tools are different?
Currently, the rune in Occlum only supports Ubtuntu18.04, is it the reason that I cannot update the apt source?
If the problem cannot resolved, whether I can install from the command line?

**Comment by haosanzi** [comment]
@morning21 hi, right now the [debian repo of rune](https://mirrors.openanolis.org/inclavare-containers/deb-repo) only supports ubuntu 18.04. 

If you want to run rune in ubuntu 20.04, you need try the installation reference to [inclavare-container](https://github.com/inclavare-containers/inclavare-containers/tree/master/rune?spm=a2c63.p38356.0.0.3efe6cceGShw0C#rune).

These two rune tools are both based on [rune source code](https://github.com/inclavare-containers/inclavare-containers/tree/master/rune).  The `rune` release support of ubuntu 20.04 is in development.

**Comment by morning21** [comment]
Thank you @haosanzi .

My current `rune` is installed according to [inclavare-container](https://github.com/inclavare-containers/inclavare-containers/tree/master/rune?spm=a2c63.p38356.0.0.3efe6cceGShw0C#rune). And the `docker/daemon.json` is configured as [Occlum guide](https://github.com/occlum/occlum/blob/master/docs/rune_quick_start.md#configuring-oci-runtime-rune-for-docker).

But when I execute `docker run --it --rm --runtim=rune`, I still face the problem of fail of OCI creation.
Is there anything that I should check?

**Comment by haosanzi** [comment]
hi, @morning21 , please refer to [this link](https://github.com/inclavare-containers/inclavare-containers/blob/master/rune/README.md#creating-an-oci-bundle) to create rune bundle and use `rune --debug run 123` to find the detailed information.

If you meet `[ERROR] occlum-pal: Failed to create enclave with error code 0x2004: Unknown SGX error (line 152, file src/pal_enclave.c)`, the error reason is ` The enclave is signed as product enclave, and can not be created as debuggable enclave. `. please add `-e OCCLUM_RELEASE_ENCLAVE=1` in docker run command.

```sh
docker run -it --rm --runtime=rune \
  -e ENCLAVE_TYPE=intelSgx \
  -e ENCLAVE_RUNTIME_PATH=/opt/occlum/build/lib/libocclum-pal.so \
  -e ENCLAVE_RUNTIME_ARGS=occlum_instance \
  -e OCCLUM_RELEASE_ENCLAVE=1 \
  occlum-app
```

![image](https://user-images.githubusercontent.com/26923638/184136689-ec042e6f-ee1a-4bfa-a558-047c05646fc6.png)

In addition, we have Chinese guide about how to run occlum-app, please refer to [link](https://help.aliyun.com/document_detail/411174.html).

**Comment by morning21** [comment]
Thank you very much! It works now.
