### ISSUE TITLE
Does occlum support JVM application?

### ISSUE THREAD

**Issue by qiyuangong** [occlum/occlum#98]
According to https://github.com/occlum/occlum/issues/87, occlum will support JVM in 2020. 

Is this feature available now?

**Comment by tatetian** [comment]
JVM support is coming. We just released the Go support this month (see the release note [here](https://github.com/occlum/occlum/releases/tag/0.12.0)). The support for Java and Rust is expected to be released in the next month. Stay tuned.

**Comment by qiyuangong** [comment]
OK. :)

BTW, is there any example about running Python application with third-party libs, such numpy?

**Comment by tatetian** [comment]
Sure. We already have such examples internally. We will release them in a week.

**Comment by qiyuangong** [comment]
Great! Thanks

Issue closed!
