### ISSUE TITLE
"IOCTRL IOCTL_VER_DCAP_QUOTE failed" in rust

### ISSUE THREAD

**Issue by chuan-xu** [occlum/occlum#988]
在rust中使用dcap_lib，参考demos/remote_attestation/dcap/c_app/dcap_c_test.c。demo中dcap案例verify quote成功：“DCAP verify quote successfully”。但是rust按照相同逻辑写了一遍失败了，下面是用rust直接调用的源码：
```rust
fn main() {
    let mut dcap_quote = DcapQuote::new();
    let quote_size = dcap_quote.get_quote_size();
    println!("[+] quote size = {}", quote_size);
    let mut quote_buf: Vec<u8> = vec![0; quote_size as usize];
    let mut report_data = sgx_report_data_t::default();
    let mut d: [uint8_t; SGX_REPORT_DATA_SIZE] = [0; SGX_REPORT_DATA_SIZE];
    for (i, v) in "ioctl DCAP report data example"
        .as_bytes()
        .iter()
        .enumerate()
    {
        if i >= SGX_REPORT_DATA_SIZE {
            break;
        }
        d[i] = *v;
    }
    report_data.d = d;
    let ret = dcap_quote
        .generate_quote(quote_buf.as_mut_ptr(), &report_data)
        .unwrap();
    if ret != 0 {
        println!("[-] Error in dcap_generate_quote");
    } else {
        let quote_buf_cone = quote_buf.clone();
        print_quote(quote_buf_cone);
        verify_quote(quote_buf, &mut dcap_quote);
    }
}
fn verify_quote(quote: Vec<u8>, dcap_quote: &mut DcapQuote) {
    // let mut dcap_quote = DcapQuote::new();
    let supplemental_data_size = dcap_quote.get_supplemental_data_size();
    println!("[+] supplemental_size size = {}", supplemental_data_size);
    let mut collateral_expiration_status = 1_u32;
    let mut quote_verification_result = sgx_ql_qv_result_t::SGX_QL_QV_RESULT_UNSPECIFIED;
    let mut supplemental_data: sgx_ql_qv_supplemental_t = unsafe { std::mem::zeroed() };
    if std::mem::size_of::<sgx_ql_qv_supplemental_t>() as u32 == supplemental_data_size {
        println!("[+] info: sgx_qv_get_quote_supplemental_data_size successfully");
    } else {
        println!("[-] Warning: Quote supplemental data size is different between DCAP QVL and QvE, please make sure you installed DCAP QVL and QvE from same release.");
        panic!();
    }
    let p_supplemental_data = &mut supplemental_data as *mut sgx_ql_qv_supplemental_t as *mut u8;
    let mut verify_arg = IoctlVerDCAPQuoteArg {
        quote_buf: quote.as_ptr(),
        quote_size: quote.len() as u32,
        collateral_expiration_status: &mut collateral_expiration_status,
        quote_verification_result: &mut quote_verification_result,
        supplemental_data_size: supplemental_data_size,
        supplemental_data: p_supplemental_data,
    };
    dcap_quote.verify_quote(&mut verify_arg).unwrap();
}
```

下面是输出的结果：(验证失败)
[+] quote size = 4599
[+] size of sgx_quote3_t: 436
[+] EncPPID:
2d2d2d2d2d424547494e2043455254494649434154452d2d2d2d2d0a4d4949456a6a4343424453674177494241674956414d79454f4d6e514b70454b4346572f7a724d314e564c73654e704e4d416f4743437147534d343942414d430a4d484578497a416842674e5642414d4d476b6c756447567349464e48574342515130736755484a765932567a6332397949454e424d526f77474159445651514b0a4442464a626e526c6243424462334a7762334a6864476c76626a45554d424947413155454277774c553246756447456751327868636d4578437a414a42674e560a4241674d416b4e424d517377435159445651514745774a56557a4165467730794d6a41344d5445774f5441314d545661467730794f5441344d5445774f5441310a4d5456614d484178496a416742674e5642414d4d47556c756447567349464e4857434251513073675132567964476c6d61574e6864475578476a415942674e560a42416f4d45556c756447567349454e76636e4276636d4630615739754d5251
[+] PCE_ID:
7745
[+] TCBr - CPUSVN:
67594456515148444174545957353059
[+] TCBr - PCE_ISVSVN:
5342
[+] QE_ID:
d4b4c8342004627fcd90128d318f595000000000
[+] supplemental_size size = 176
[+] info: sgx_qv_get_quote_supplemental_data_size successfully
ret = -1
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "IOCTRL IOCTL_VER_DCAP_QUOTE failed"', src/main.rs:54:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by qzheng527** [comment]
For rust way DCAP, please refer to the example [`dcap_test.rs`](https://github.com/qzheng527/occlum/blob/k8s_poc/tools/toolchains/dcap_lib/examples/dcap_test.rs)

**Comment by TY-cc** [comment]
生成quote的report，你尝试过非默认生成么？

**Comment by chuan-xu** [comment]
> 生成quote的report，你尝试过非默认生成么？

非默认指的是什么？自定义report data吗？

**Comment by TY-cc** [comment]
> > 生成quote的report，你尝试过非默认生成么？
> 
> 非默认指的是什么？自定义report data吗？

对的，在demo里report都是默认的。但是怎么根据实际的enclave来生成report呢？
可以加个联系方式么？ VX: Cch_1015

**Comment by chuan-xu** [comment]
> > > 生成quote的report，你尝试过非默认生成么？
> > 
> > 
> > 非默认指的是什么？自定义report data吗？
> 
> 对的，在demo里report都是默认的。但是怎么根据实际的enclave来生成report呢？ 可以加个联系方式么？ VX: Cch_1015

```rust
pub fn new(report_data: &str) -> Self {
        let mut dcap = DcapQuote::new();
        let quote_size = dcap.get_quote_size();
        let supplemental_size = dcap.get_supplemental_data_size();
        let quote_buf: Vec<u8> = vec![0; quote_size as usize];
        let suppl_buf: Vec<u8> = vec![0; supplemental_size as usize];
        let mut req_data = sgx_report_data_t::default();

        //fill in the report data array
        for (pos, val) in report_data.as_bytes().iter().enumerate() {
            req_data.d[pos] = *val;
        }

        Self {
            dcap_quote: dcap,
            quote_size: quote_size,
            quote_buf: quote_buf,
            req_data: req_data,
            supplemental_size: supplemental_size,
            suppl_buf: suppl_buf
        }
    
```
这个demo里面可以填充report。
