### ISSUE TITLE
[BUG] occlum package does not include occlum-run binary

### ISSUE THREAD

**Issue by mythi** [occlum/occlum#994]
# Describe the bug
According to `occlum --help`:

```
   occlum package [<package_name>.tar.gz]
        Generate a minimal, self-contained package (.tar.gz) for the Occlum instance.
        The resulting package can then be copied to a deployment environment and unpacked
        as a runnable Occlum instance.
...
```

To run an Occlum instance, `occlum-run` is used. However, it looks `occlum package` does not include the binary, just a symlink to host installation path:

```
$ mkdir unpack
$ tar -C unpack/ -x -f occlum_instance.tar.gz 
$ ls -l unpack/occlum_instance/build/bin/
total 0
lrwxrwxrwx 1 user user 40 Sep  5 10:05 occlum_exec_client -> /opt/occlum/build/bin/occlum_exec_client
lrwxrwxrwx 1 user user 40 Sep  5 10:05 occlum_exec_server -> /opt/occlum/build/bin/occlum_exec_server
lrwxrwxrwx 1 user user 32 Sep  5 10:05 occlum-run -> /opt/occlum/build/bin/occlum-run
```

# To reproduce
1. see above

# Expected behavior
"The resulting package can then be copied to a deployment environment and unpacked as a runnable Occlum instance."

# Logs
N/A

# Environment
- Occlum version: 0.27.x

# Additional context
N/A 

# Possible solution/Implementation
N/A

**Comment by guzongmin** [comment]
It is the design. The user could install the runtime with the apt-get command.
Please reference the demo https://github.com/occlum/occlum/tree/master/demos/deployment

**Comment by mythi** [comment]
> It is the design. The user could install the runtime with the apt-get command. Please reference the demo https://github.com/occlum/occlum/tree/master/demos/deployment

I can give it a try but if `occlum package` builds a stand-alone installation, it's probably not clear for the user that something extra is needed especially since the documentation says that everything is included:

```
   All runtime dependencies required by the Occlum instance---except Intel SGX driver,
        enable_rdfsbase kernel module, and Intel SGX PSW---are included in the package.
```

**Comment by jessehui** [comment]
Hi @mythi, thanks for using Occlum. Sorry for the misunderstanding, you can install `occlum-runtime` package for your deployment environment. This will make the softlinks valid in the package generated with `occlum package` command.

**Comment by mythi** [comment]
I can confirm adding:
```
RUN echo "deb [arch=amd64 signed-by=/usr/share/keyrings/occlum.gpg] https://occlum.io/occlum-package-repos/debian focal main" | tee -a /etc/apt/sources.list.d/occlum.list \
 && wget -qO - https://occlum.io/occlum-package-repos/debian/public.key | gpg --dearmor --output /usr/share/keyrings/occlum.gpg \
 && apt-get update \
 && env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    occlum-runtime
```

to my container build works.
